# Generated by: Claude Sonnet 4.5
"""Setup script for Coldpress."""

from setuptools import setup, find_packages

setup(
    name="coldpress",
    version="0.2.0",
    description="AI/HPC workload orchestration for Kubernetes/OpenShift",
    packages=find_packages(),
    install_requires=[
        "click>=8.0.0",
        "pyyaml>=6.0.0",
        "pydantic>=2.0.0",
    ],
    entry_points={
        "console_scripts": [
            "coldpress=coldpress.cli:cli",
            "coldpress-setup=coldpress_setup.cli:cli",
        ],
    },
    python_requires=">=3.9",
)
