#!/bin/bash
# Generated by: Claude Sonnet 4.5
# Setup Coldpress

set -e

echo "Setting up Coldpress..."

# Create virtual environment if it doesn't exist
if [ ! -d "venv" ]; then
    echo "Creating virtual environment..."
    python3 -m venv venv
fi

# Activate virtual environment
echo "Activating virtual environment..."
source venv/bin/activate

# Upgrade pip
echo "Upgrading pip..."
pip install --upgrade pip --quiet

# Install coldpress
echo "Installing coldpress..."
pip install -e . --quiet

echo "Coldpress setup complete!"
echo ""
echo "To activate the environment, run:"
echo "  source venv/bin/activate"
echo ""
echo "To test coldpress, run:"
echo "  coldpress generate examples/vllm_guidellm_benchmark/job-spec.yaml -o ./test-job/"
