#!/bin/bash
# Generated by: Claude Sonnet 4.5
# Setup Coldpress

set -e

# Parse installation method (default: uv for development)
INSTALL_METHOD="uv"
if [ "$1" == "--pipx" ]; then
    INSTALL_METHOD="pipx"
elif [ "$1" == "--pipx-editable" ]; then
    INSTALL_METHOD="pipx-editable"
elif [ "$1" == "--uv" ]; then
    INSTALL_METHOD="uv"
elif [ -n "$1" ]; then
    echo "Usage: $0 [--uv|--pipx|--pipx-editable]"
    echo ""
    echo "Installation methods:"
    echo "  --uv              Install with uv (editable, for development) [default]"
    echo "  --pipx            Install with pipx (global, for end users)"
    echo "  --pipx-editable   Install with pipx in editable mode (global + updates)"
    echo ""
    echo "Examples:"
    echo "  $0                # Install with uv (development)"
    echo "  $0 --pipx         # Install with pipx (end user)"
    echo "  $0 --pipx-editable # Install with pipx editable (end user + dev)"
    exit 1
fi

echo "Setting up Coldpress with $INSTALL_METHOD..."
echo ""

# Check for kubectl or oc (required for all Coldpress operations)
if ! command -v oc &> /dev/null && ! command -v kubectl &> /dev/null; then
    echo "ERROR: Neither kubectl nor oc found in PATH"
    echo ""
    echo "Coldpress requires kubectl or oc to interact with Kubernetes/OpenShift clusters."
    echo "Please install one of the following:"
    echo "  - kubectl: https://kubernetes.io/docs/tasks/tools/"
    echo "  - oc (OpenShift CLI): https://docs.openshift.com/container-platform/latest/cli_reference/openshift_cli/getting-started-cli.html"
    exit 1
fi

if command -v oc &> /dev/null; then
    echo "Found oc: $(which oc)"
elif command -v kubectl &> /dev/null; then
    echo "Found kubectl: $(which kubectl)"
fi

if [ "$INSTALL_METHOD" == "uv" ]; then
    # UV installation (development)
    if ! command -v uv &> /dev/null; then
        echo "uv not found. Installing uv..."
        python3 -m pip install --user uv
    fi

    if [ ! -d ".venv" ]; then
        echo "Creating virtual environment with uv..."
        uv venv
    fi

    echo "Installing coldpress in editable mode..."
    uv pip install -e .

    echo ""
    echo "Coldpress setup complete!"
    echo ""
    echo "To activate the environment, run:"
    echo "  source .venv/bin/activate"
    echo ""
    echo "Then test coldpress:"
    echo "  coldpress --version"
    echo "  coldpress generate examples/vllm_guidellm_benchmark/job-spec.yaml -o ./test-job/"

elif [ "$INSTALL_METHOD" == "pipx" ] || [ "$INSTALL_METHOD" == "pipx-editable" ]; then
    # pipx installation (end users)
    if ! command -v pipx &> /dev/null; then
        echo "pipx not found. Installing pipx..."
        python3 -m pip install --user pipx
        python3 -m pipx ensurepath
        echo ""
        echo "NOTE: You may need to restart your shell or run:"
        echo "  export PATH=\"\$HOME/.local/bin:\$PATH\""
        echo ""
    fi

    if [ "$INSTALL_METHOD" == "pipx-editable" ]; then
        echo "Installing coldpress with pipx (editable mode)..."
        pipx install --editable --force .
    else
        echo "Installing coldpress with pipx..."
        pipx install --force .
    fi

    echo ""
    echo "Coldpress setup complete!"
    echo ""
    echo "Commands are now globally available (no activation needed):"
    echo "  coldpress --version"
    echo "  coldpress-setup --version"
    echo ""
    echo "Test coldpress:"
    echo "  coldpress generate examples/vllm_guidellm_benchmark/job-spec.yaml -o ./test-job/"
    echo ""
    if [ "$INSTALL_METHOD" == "pipx-editable" ]; then
        echo "Installed in editable mode - changes to code will be reflected immediately."
    fi
fi
