# Generated by: Claude Sonnet 4.5
"""
Pytest configuration for test suite.
Handles loading of operator module with mocked Kubernetes config.
"""

import sys
from pathlib import Path
import importlib.util
from unittest.mock import patch


def pytest_configure(config):
    """
    Load operator module before test collection.
    This prevents Kubernetes connection attempts during module import.
    """
    # Mock Kubernetes config before loading operator module
    with (
        patch("kubernetes.config.load_incluster_config"),
        patch("kubernetes.config.load_kube_config"),
    ):
        # Load our local operator.py module (avoiding stdlib operator conflict)
        operator_path = Path(__file__).parent.parent / "operator.py"
        spec = importlib.util.spec_from_file_location(
            "coldpress_operator", operator_path
        )
        operator_module = importlib.util.module_from_spec(spec)
        sys.modules["coldpress_operator"] = operator_module
        spec.loader.exec_module(operator_module)
