# Generated by: Claude Sonnet 4.5
"""
Test suite for operator.py - covers security boundaries, node allocation,
and template rendering logic.
"""

import pytest
from unittest.mock import MagicMock, patch
import kopf
import sys

# Import from the pre-loaded coldpress_operator module (loaded in conftest.py)
# This avoids stdlib operator conflict and K8s connection issues
operator_module = sys.modules["coldpress_operator"]
render_template = operator_module.render_template
get_node_ip = operator_module.get_node_ip
allocate_node = operator_module.allocate_node
get_node_demand_score = operator_module.get_node_demand_score
create_compute_job = operator_module.create_compute_job
handle_allocator = operator_module.handle_allocator
create_discovery = operator_module.create_discovery


# This fixture automatically runs before every test,
# keeping the config functions mocked while the tests execute.
@pytest.fixture(autouse=True)
def mock_k8s_config():
    with (
        patch("kubernetes.config.load_incluster_config"),
        patch("kubernetes.config.load_kube_config"),
    ):
        yield


class TestTemplateSecurity:
    """Tests for template rendering security boundaries."""

    @patch("kubernetes.client.CustomObjectsApi")
    def test_render_template_from_admin_namespace_only(self, mock_custom_api_cls):
        """Verifies templates are ALWAYS fetched from coldpress-admin namespace."""
        mock_api = MagicMock()
        mock_custom_api_cls.return_value = mock_api

        # Mock template response
        mock_template = {
            "spec": {
                "image": "test-image:latest",
                "command": ["python"],
                "args": ["--model={model}"],
                "env": [{"name": "PORT", "value": "{port}"}],
                "resources": {"limits": {"nvidia.com/gpu": "1"}},
            }
        }
        mock_api.get_namespaced_custom_object.return_value = mock_template

        # Call render_template - should use admin namespace
        user_params = {"model": "gpt-4", "port": "8000"}
        result = render_template(
            "vllm-parser", "researcher-a", user_params, "coldpress-admin"
        )

        # Assert API called with admin namespace (hardcoded security boundary)
        mock_api.get_namespaced_custom_object.assert_called_once_with(
            "coldpress.io", "v1", "coldpress-admin", "workload-templates", "vllm-parser"
        )

        # Verify params were interpolated
        assert result["args"] == ["--model=gpt-4"]
        assert result["env"][0]["value"] == "8000"

    @patch("kubernetes.client.CustomObjectsApi")
    def test_render_template_missing_template_raises_error(self, mock_custom_api_cls):
        """Verifies missing template raises PermanentError."""
        mock_api = MagicMock()
        mock_custom_api_cls.return_value = mock_api
        mock_api.get_namespaced_custom_object.side_effect = Exception(
            "Template not found"
        )

        with pytest.raises(kopf.PermanentError) as exc_info:
            render_template("nonexistent-parser", "researcher-a", {})

        assert "not found in admin namespace" in str(exc_info.value)


class TestParserAllowlistEnforcement:
    """Tests for namespace-level parser authorization."""

    @patch("kubernetes.client.CustomObjectsApi")
    @patch("kubernetes.client.CoreV1Api")
    @patch("coldpress_operator.rt")
    def test_compute_job_parser_allowlist_enforcement(
        self, mock_rt, mock_core_api_cls, mock_custom_api_cls
    ):
        """Verifies namespace annotation coldpress.io/allowed-compute-parsers is enforced."""

        mock_core_api = MagicMock()
        mock_core_api_cls.return_value = mock_core_api

        # Mock namespace with allowlist
        mock_namespace = MagicMock()
        mock_namespace.metadata.annotations = {
            "coldpress.io/allowed-compute-parsers": "vllm-parser,pytorch-parser"
        }
        mock_core_api.read_namespace.return_value = mock_namespace

        # Mock nodes
        mock_rt.get_nodes.return_value = {
            "0": {"name": "worker-0", "gpus": {"0": False}}
        }

        # Test with unauthorized parser
        spec = {
            "tasks": [
                {
                    "name": "task1",
                    "template": "unauthorized-parser",
                    "node": 0,
                    "params": {},
                }
            ],
            "storage": {"results": "test-pvc"},
        }

        with pytest.raises(kopf.PermanentError) as exc_info:
            create_compute_job(spec, "test-job", "researcher-a", {})

        assert "Security Violation" in str(exc_info.value)
        assert "unauthorized-parser" in str(exc_info.value)

    @patch("kubernetes.client.CustomObjectsApi")
    @patch("kubernetes.client.CoreV1Api")
    @patch("coldpress_operator.rt")
    def test_allocator_parser_allowlist_enforcement(
        self, mock_rt, mock_core_api_cls, mock_custom_api_cls
    ):
        """Verifies namespace annotation coldpress.io/allowed-allocator-parsers is enforced."""

        mock_core_api = MagicMock()
        mock_core_api_cls.return_value = mock_core_api

        # Mock namespace with allocator allowlist
        mock_namespace = MagicMock()
        mock_namespace.metadata.annotations = {
            "coldpress.io/allowed-allocator-parsers": "distributed-training"
        }
        mock_core_api.read_namespace.return_value = mock_namespace

        spec = {
            "tasks": [
                {"name": "task1", "template": "unauthorized-allocator", "params": {}}
            ],
            "storage": {"results": "test-pvc"},
        }

        with pytest.raises(kopf.PermanentError) as exc_info:
            handle_allocator(spec, "test-allocator", "researcher-a", body={})

        assert "Security Violation" in str(exc_info.value)
        assert "unauthorized-allocator" in str(exc_info.value)

    @patch("kubernetes.client.CustomObjectsApi")
    @patch("kubernetes.client.CoreV1Api")
    @patch("coldpress_operator.rt")
    def test_wildcard_allows_all_parsers(
        self, mock_rt, mock_core_api_cls, mock_custom_api_cls
    ):
        """Verifies '*' in allowlist permits any parser."""

        mock_core_api = MagicMock()
        mock_core_api_cls.return_value = mock_core_api
        mock_custom_api = MagicMock()
        mock_custom_api_cls.return_value = mock_custom_api

        # Mock namespace with wildcard allowlist
        mock_namespace = MagicMock()
        mock_namespace.metadata.annotations = {
            "coldpress.io/allowed-compute-parsers": "*"
        }
        mock_core_api.read_namespace.return_value = mock_namespace

        # Mock nodes and template
        mock_rt.get_nodes.return_value = {
            "0": {"name": "worker-0", "gpus": {"0": False}}
        }
        mock_custom_api.get_namespaced_custom_object.return_value = {
            "spec": {
                "image": "test:latest",
                "args": [],
                "env": [],
            }
        }

        spec = {
            "tasks": [
                {
                    "name": "task1",
                    "template": "any-parser-should-work",
                    "node": 0,
                    "params": {},
                }
            ],
            "storage": {"results": "test-pvc"},
        }

        # Should NOT raise error with wildcard
        try:
            result = create_compute_job(spec, "test-job", "researcher-a", {})
            # If we get here, wildcard worked
            assert result is not None
        except kopf.PermanentError as e:
            # Should NOT be a security violation
            assert "Security Violation" not in str(e)

    @patch("kubernetes.client.CustomObjectsApi")
    @patch("kubernetes.client.CoreV1Api")
    def test_discovery_job_authorization(self, mock_core_api_cls, mock_custom_api_cls):
        """Verifies discovery jobs check coldpress.io/allowed-parsers."""

        mock_core_api = MagicMock()
        mock_core_api_cls.return_value = mock_core_api

        # Mock namespace with discovery parser allowlist
        mock_namespace = MagicMock()
        mock_namespace.metadata.annotations = {
            "coldpress.io/allowed-parsers": "gpu-info-discovery"
        }
        mock_core_api.read_namespace.return_value = mock_namespace

        spec = {"template": "unauthorized-discovery"}

        with pytest.raises(kopf.PermanentError) as exc_info:
            create_discovery(spec, "test-discovery", "researcher-a", {})

        assert "Security Violation" in str(exc_info.value)
        assert "unauthorized-discovery" in str(exc_info.value)


class TestNodeAllocation:
    """Tests for node allocation algorithm."""

    @patch("coldpress_operator.rt")
    def test_allocate_node_selects_sufficient_gpus(self, mock_rt):
        """Verifies allocate_node() only selects nodes with enough GPUs."""
        # Mock nodes: node0 has 1 GPU, node1 has 4 GPUs
        mock_rt.get_nodes.return_value = {
            "0": {"name": "worker-0", "gpus": {"0": False}},
            "1": {
                "name": "worker-1",
                "gpus": {"0": False, "1": False, "2": False, "3": False},
            },
        }

        with patch("coldpress_operator.get_node_demand_score", return_value=0):
            # Request 2 GPUs - should select node1
            selected_node = allocate_node(req_gpus=2, req_nics=0)
            assert selected_node == "1"

    @patch("coldpress_operator.rt")
    def test_allocate_node_fails_insufficient_resources(self, mock_rt):
        """Verifies allocation fails when no node meets requirements."""
        # Mock nodes with only 1 GPU each
        mock_rt.get_nodes.return_value = {
            "0": {"name": "worker-0", "gpus": {"0": False}},
            "1": {"name": "worker-1", "gpus": {"0": False}},
        }

        # Request 4 GPUs - should fail
        with pytest.raises(kopf.PermanentError) as exc_info:
            allocate_node(req_gpus=4, req_nics=0)

        assert "No nodes found satisfying requirements" in str(exc_info.value)

    @patch("kubernetes.client.CustomObjectsApi")
    def test_get_node_demand_score_calculation(self, mock_custom_api_cls):
        """Verifies scoring algorithm weighs GPU/NIC/CPU usage correctly."""
        mock_api = MagicMock()
        mock_custom_api_cls.return_value = mock_api

        # Mock Kueue ClusterQueue status with resource usage
        mock_cq = {
            "status": {
                "flavorsUsage": [
                    {
                        "name": "node0",
                        "resources": [
                            {"name": "nvidia.com/gpu", "total": "2"},
                            {"name": "rdma/roce", "total": "1"},
                            {"name": "cpu", "total": "4000m"},
                        ],
                    }
                ]
            }
        }
        mock_api.get_cluster_custom_object.return_value = mock_cq

        # Request 2 GPUs, 1 NIC
        score = get_node_demand_score(node_id="0", req_gpus=2, req_nics=1)

        # Score should be: (2/2)*10 + (1/1)*5 + (4)*0.1 = 10 + 5 + 0.4 = 15.4
        assert score == pytest.approx(15.4, rel=0.1)

    @patch("kubernetes.client.CustomObjectsApi")
    @patch("coldpress_operator.rt")
    def test_allocation_prefers_least_utilized_node(self, mock_rt, mock_custom_api_cls):
        """Verifies allocator picks node with lowest demand score."""
        mock_rt.get_nodes.return_value = {
            "0": {"name": "worker-0", "gpus": {"0": False, "1": False}},
            "1": {"name": "worker-1", "gpus": {"0": False, "1": False}},
        }

        # Mock node0 as busy (high score), node1 as idle (low score)
        def mock_score(node_id, req_gpus, req_nics):
            return 50.0 if node_id == "0" else 5.0

        with patch("coldpress_operator.get_node_demand_score", side_effect=mock_score):
            selected_node = allocate_node(req_gpus=1, req_nics=0)
            # Should prefer node1 (lower score)
            assert selected_node == "1"


class TestTemplateRendering:
    """Tests for template parameter interpolation."""

    @patch("kubernetes.client.CustomObjectsApi")
    def test_render_template_parameter_interpolation(self, mock_custom_api_cls):
        """Verifies user params are correctly interpolated into template."""
        mock_api = MagicMock()
        mock_custom_api_cls.return_value = mock_api

        # Template with placeholders
        mock_template = {
            "spec": {
                "image": "vllm:latest",
                "command": ["python", "-m", "vllm.entrypoints.api_server"],
                "args": [
                    "--model={model}",
                    "--port={port}",
                    "--tensor-parallel-size={num_gpus}",
                ],
                "env": [
                    {"name": "MODEL_NAME", "value": "{model}"},
                    {"name": "PORT", "value": "{port}"},
                ],
                "resources": {"limits": {"nvidia.com/gpu": "{num_gpus}"}},
            }
        }
        mock_api.get_namespaced_custom_object.return_value = mock_template

        user_params = {"model": "llama-3", "port": "8080", "num_gpus": "4"}
        result = render_template("vllm-parser", "researcher-a", user_params)

        # Verify interpolation
        assert result["args"] == [
            "--model=llama-3",
            "--port=8080",
            "--tensor-parallel-size=4",
        ]
        assert result["env"][0]["value"] == "llama-3"
        assert result["env"][1]["value"] == "8080"
        assert result["resources"]["limits"]["nvidia.com/gpu"] == "4"


class TestServiceDiscovery:
    """Tests for inter-task service discovery."""

    def test_get_node_ip_returns_service_dns(self):
        """Verifies get_node_ip() generates correct service DNS."""
        node_task_map = {"0": 0, "1": 1}
        result = get_node_ip(
            target_node=0,
            namespace="researcher-a",
            job_id="test-job",
            node_task_map=node_task_map,
        )
        assert result == "s-test-job-0.researcher-a.svc"

    def test_get_node_ip_fallback_localhost(self):
        """Verifies fallback to localhost when target not in node_task_map."""
        node_task_map = {"0": 0, "1": 1}
        # Request node 99 which doesn't exist
        result = get_node_ip(
            target_node=99,
            namespace="researcher-a",
            job_id="test-job",
            node_task_map=node_task_map,
        )
        assert result == "127.0.0.1"
