# Generated by: Claude Sonnet 4.5
"""Coldpress Setup CLI - Generate manifests for cluster setup and configuration."""

import click
import yaml
import os
import shutil
from datetime import datetime, timezone

from .generator import manifests_to_yaml
from coldpress_common import (
    validate_project_config,
    validate_user_config,
    validate_cluster_config,
)
from pydantic import ValidationError

# Default directories (can be overridden with environment variables)
PROJECT_DIR = os.getenv("COLDPRESS_PROJECT_DIR", "projects")
CLUSTER_DIR = os.getenv("COLDPRESS_CLUSTER_DIR", "cluster")
USER_DIR = os.getenv("COLDPRESS_USER_DIR", "users")
MANIFESTS_DIR = os.getenv("COLDPRESS_MANIFESTS_DIR", "manifests")


def _resolve_config_path(config_file, config_type):
    """Resolve config file path by checking standard directories."""
    # If file exists as-is, use it
    if os.path.exists(config_file):
        return config_file

    # Otherwise, check in the standard directory for this config type
    standard_dirs = {
        "cluster": CLUSTER_DIR,
        "project": PROJECT_DIR,
        "user": USER_DIR,
    }

    if config_type in standard_dirs:
        dir_path = standard_dirs[config_type]
        full_path = os.path.join(dir_path, config_file)
        if os.path.exists(full_path):
            return full_path

    # If not found, return original (will fail with helpful error)
    return config_file


def _generate_manifest_filename(subcommand, config_file):
    """Generate timestamped manifest filename.

    Format: {subcommand}-{config-basename}-{timestamp}.yaml
    Example: project-coldpress-project-20260413-143022.yaml
    """
    # Extract basename without extension
    config_basename = os.path.splitext(os.path.basename(config_file))[0]

    # Generate timestamp (YYYYMMDD-HHMMSS in UTC)
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")

    return f"{subcommand}-{config_basename}-{timestamp}.yaml"


@click.group()
@click.version_option(version="0.2.0")
def cli():
    """Coldpress Setup - Generate manifests for cluster setup and configuration."""
    pass


@cli.group()
def generate():
    """
    Generate manifests for cluster, project, or user configuration.

    Manifests are written to the output directory (default: manifests/).
    The admin is responsible for reviewing and applying them.

    Use subcommands to specify the type of configuration:
        coldpress-setup generate cluster <config.yaml>
        coldpress-setup generate project <config.yaml>
        coldpress-setup generate user <config.yaml>
    """
    pass


@generate.command()
@click.argument("config_file", type=click.Path())
@click.option(
    "--output-dir",
    "-o",
    type=click.Path(),
    default=None,
    help=f"Output directory for manifests (default: {MANIFESTS_DIR})",
)
def cluster(config_file, output_dir):
    """
    Generate cluster-wide configuration manifests.

    Cluster config: YAML file with Kueue/JobSet operators and resources (copied as-is)

    The manifests are written to the output directory. The admin is responsible for applying them.

    Examples:
        coldpress-setup generate cluster ocp-test-nerc-mghpcc.yaml
        coldpress-setup generate cluster ocp-test-nerc-mghpcc.yaml --output-dir /path/to/manifests
    """
    # Resolve config file path
    config_file = _resolve_config_path(config_file, "cluster")
    if not os.path.exists(config_file):
        click.echo(f"Error: Config file not found: {config_file}", err=True)
        raise SystemExit(1)

    raise SystemExit(generate_cluster_config(config_file, output_dir))


@generate.command()
@click.argument("config_file", type=click.Path())
@click.option(
    "--output-dir",
    "-o",
    type=click.Path(),
    default=None,
    help=f"Output directory for manifests (default: {MANIFESTS_DIR})",
)
def project(config_file, output_dir):
    """
    Generate project configuration manifests.

    Project config: Generate namespace resources (Namespace, PVC, LocalQueue, RBAC)

    The manifests are written to the output directory. The admin is responsible for applying them.

    Examples:
        coldpress-setup generate project coldpress-project.yaml
        coldpress-setup generate project coldpress-project.yaml --output-dir /path/to/manifests
    """
    # Resolve config file path
    config_file = _resolve_config_path(config_file, "project")
    if not os.path.exists(config_file):
        click.echo(f"Error: Config file not found: {config_file}", err=True)
        raise SystemExit(1)

    # Load and validate project config
    with open(config_file, "r") as f:
        config_data = yaml.safe_load(f)

    try:
        validated_config = validate_project_config(config_data)
        # Convert back to dict for compatibility with downstream code
        config = config_data
    except ValidationError as e:
        click.echo(f"Error: Project config validation failed:\n{e}", err=True)
        raise SystemExit(1)

    raise SystemExit(generate_project_config(config, config_file, output_dir))


@generate.command()
@click.argument("config_file", type=click.Path())
@click.option(
    "--output-dir",
    "-o",
    type=click.Path(),
    default=None,
    help=f"Output directory for manifests (default: {MANIFESTS_DIR})",
)
def user(config_file, output_dir):
    """
    Generate user configuration manifests.

    User config: Generate user RBAC (RoleBindings across namespaces)

    The manifests are written to the output directory. The admin is responsible for applying them.

    Examples:
        coldpress-setup generate user coldpress-user.yaml
        coldpress-setup generate user coldpress-user.yaml --output-dir /path/to/manifests
    """
    # Resolve config file path
    config_file = _resolve_config_path(config_file, "user")
    if not os.path.exists(config_file):
        click.echo(f"Error: Config file not found: {config_file}", err=True)
        raise SystemExit(1)

    # Load and validate user config
    with open(config_file, "r") as f:
        config_data = yaml.safe_load(f)

    try:
        validated_config = validate_user_config(config_data)
        # Convert back to dict for compatibility with downstream code
        config = config_data
    except ValidationError as e:
        click.echo(f"Error: User config validation failed:\n{e}", err=True)
        raise SystemExit(1)

    raise SystemExit(generate_user_config(config, config_file, output_dir))


def generate_cluster_config(config_file, output_dir):
    """Generate cluster-wide configuration manifests."""
    click.echo("Generating cluster configuration manifests...")
    click.echo(f"Config file: {config_file}")

    # Load and parse cluster config
    with open(config_file, "r") as f:
        # Load all YAML documents
        all_docs = list(yaml.safe_load_all(f))

    # First document should be the config with nodes
    config_data = all_docs[0] if all_docs else {}

    # Validate cluster config (extract nodes section)
    nodes = []
    try:
        validated_config = validate_cluster_config(config_data)
        nodes = [
            {"hostname": node.hostname, "gpus": node.gpus, "roce_nics": node.roce_nics}
            for node in validated_config.nodes
        ]
    except ValidationError as e:
        click.echo(f"Warning: Could not validate cluster config: {e}", err=True)
        click.echo("Continuing without node labeling commands...", err=True)

    # Use default output directory if not specified
    output_dir = output_dir or MANIFESTS_DIR

    # Create output directory
    os.makedirs(output_dir, exist_ok=True)

    # Generate timestamped filename
    manifest_filename = _generate_manifest_filename("cluster", config_file)
    output_path = os.path.join(output_dir, manifest_filename)

    # Copy cluster config to output directory (all documents except the first config one)
    with open(output_path, "w") as f:
        # Write only the Kubernetes manifests (skip the config section)
        yaml.dump_all(all_docs[1:], f, default_flow_style=False, sort_keys=False)

    # Generate node labeling script if nodes were found
    label_script_path = None
    if nodes:
        # Use same timestamp as manifest for consistency
        config_basename = os.path.splitext(os.path.basename(config_file))[0]
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
        label_script_path = os.path.join(
            output_dir, f"label-nodes-{config_basename}-{timestamp}.sh"
        )
        with open(label_script_path, "w") as f:
            f.write("#!/bin/bash\n")
            f.write(f"# Generated by coldpress-setup on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write("# Label cluster nodes with coldpress.node IDs\n\n")
            f.write("set -e\n\n")
            f.write("echo 'Labeling cluster nodes...'\n\n")
            for node_id, node in enumerate(nodes):
                f.write(f"# Node {node_id}: {node['hostname']}\n")
                f.write(f"oc label node {node['hostname']} coldpress.node={node_id} --overwrite\n")
            f.write("\necho ''\n")
            f.write("echo 'Verifying labels...'\n")
            f.write("oc get nodes --show-labels | grep coldpress.node\n")
            f.write("\necho ''\n")
            f.write("echo 'Node labeling complete!'\n")
        os.chmod(label_script_path, 0o755)

    click.echo(f"\nCluster manifest written to: {output_path}")
    if label_script_path:
        click.echo(f"Node labeling script written to: {label_script_path}")
    click.echo("\nResources in manifest:")
    click.echo("  - Kueue operator")
    click.echo("  - JobSet operator")
    click.echo("  - ResourceFlavors")
    click.echo("  - ClusterQueue")
    if nodes:
        click.echo(f"\nNodes to be labeled: {len(nodes)}")
        for node_id, node in enumerate(nodes):
            click.echo(f"  - {node['hostname']} → coldpress.node={node_id}")
    click.echo("\nNext steps:")
    click.echo(f"  1. Review manifests: cat {output_path}")
    if label_script_path:
        click.echo(f"  2. Label nodes: {label_script_path}")
        click.echo(f"  3. Apply manifests: oc apply -f {output_path}")
    else:
        click.echo(f"  2. Apply: oc apply -f {output_path}")
    click.echo("  4. Verify: oc get clusterqueues")
    click.echo(
        "  5. Generate project manifests: coldpress-setup generate project <project-config.yaml>"
    )

    return 0


def _generate_and_display_manifests(config, manifest_generator):
    """Generate manifests and display summary."""
    manifests = manifest_generator(config)

    ns_count = len(manifests.get("namespaces", []))
    kueue_count = len(manifests.get("kueue", []))
    storage_count = len(manifests.get("storage", []))
    rbac_count = len(manifests.get("rbac", []))

    click.echo(f"  Namespace: {ns_count}")
    click.echo(f"  LocalQueue: {kueue_count}")
    click.echo(f"  PVC: {storage_count}")
    click.echo(f"  RBAC: {rbac_count}")

    return manifests


def generate_project_config(config, config_file, output_dir):
    """Generate project configuration manifests."""
    from .generator import generate_project_manifests

    namespace = config.get("namespace")
    if not namespace:
        click.echo("Error: Project config must include 'namespace'", err=True)
        return 1

    click.echo("Generating project configuration manifests...")
    click.echo(f"Namespace: {namespace}")
    click.echo("\nGenerating resources...")

    manifests = _generate_and_display_manifests(config, generate_project_manifests)

    # Use default output directory if not specified
    output_dir = output_dir or MANIFESTS_DIR

    # Create output directory
    os.makedirs(output_dir, exist_ok=True)

    # Generate timestamped filename
    manifest_filename = _generate_manifest_filename("project", config_file)
    output_path = os.path.join(output_dir, manifest_filename)

    # Write manifests to file
    yaml_content = manifests_to_yaml(manifests)
    with open(output_path, "w") as f:
        f.write(yaml_content)

    click.echo(f"\nProject manifest written to: {output_path}")
    click.echo("\nNext steps:")
    click.echo(f"  1. Review: cat {output_path}")
    click.echo(f"  2. Apply: oc apply -f {output_path}")
    click.echo(f"  3. Verify: oc get namespace {namespace}")
    click.echo(
        "  4. Generate user manifests: coldpress-setup generate user <user-config.yaml>"
    )

    return 0


def _validate_user_config(config):
    """Validate user configuration."""
    username = config.get("username")
    namespaces = config.get("namespaces", [])

    if not username:
        raise ValueError("User config must include 'username'")
    if not namespaces:
        raise ValueError("User config must include 'namespaces' list")

    return username, namespaces


def generate_user_config(config, config_file, output_dir):
    """Generate user configuration manifests."""
    from .generator import generate_user_rbac

    try:
        username, namespaces = _validate_user_config(config)

        click.echo("Generating user configuration manifests...")
        click.echo(f"Username: {username}")
        click.echo(f"Namespaces: {', '.join(namespaces)}")

        click.echo("\nGenerating user RBAC...")
        rbac_manifests = generate_user_rbac(username, namespaces)
        click.echo(f"  RoleBindings: {len(rbac_manifests)}")

        manifests = {"rbac": rbac_manifests}

        # Use default output directory if not specified
        output_dir = output_dir or MANIFESTS_DIR

        # Create output directory
        os.makedirs(output_dir, exist_ok=True)

        # Generate timestamped filename
        manifest_filename = _generate_manifest_filename("user", config_file)
        output_path = os.path.join(output_dir, manifest_filename)

        # Write manifests to file
        yaml_content = manifests_to_yaml(manifests)
        with open(output_path, "w") as f:
            f.write(yaml_content)

        click.echo(f"\nUser manifest written to: {output_path}")
        click.echo("\nNext steps:")
        click.echo(f"  1. Review: cat {output_path}")
        click.echo(f"  2. Apply: oc apply -f {output_path}")
        click.echo(f"  3. User {username} can now submit jobs to granted namespaces")

        return 0

    except ValueError as e:
        click.echo(f"Error: {e}", err=True)
        return 1


if __name__ == "__main__":
    import sys
    sys.exit(cli())
