# Generated by: Claude Sonnet 4.5
"""Coldpress Setup CLI - One-time cluster setup and configuration."""

import click
import yaml
import os
from kubernetes import client, config as k8s_config

from .generator import manifests_to_yaml

# Default directories (can be overridden with environment variables)
PROJECT_DIR = os.getenv("COLDPRESS_PROJECT_DIR", "projects")


@click.group()
@click.version_option(version="2.0.0")
def cli():
    """Coldpress Setup - One-time cluster setup and configuration."""
    pass


@cli.command()
@click.argument("config_file", type=click.Path(exists=True))
@click.option(
    "--output",
    "-o",
    type=click.Path(),
    help="Output manifests to file instead of applying to cluster",
)
@click.option(
    "--dry-run", is_flag=True, help="Generate manifests but don't apply to cluster"
)
def apply(config_file, output, dry_run):
    """
    Apply cluster, project, or user configuration.

    Cluster config: YAML file with Kueue/JobSet operators and resources (apply as-is)
    Project config: Generate namespace resources (Namespace, PVC, LocalQueue, RBAC)
    User config: Generate user RBAC (RoleBindings across namespaces)

    Examples:
        coldpress-setup apply cluster/ocp-test-nerc-mghpcc.yaml
        coldpress-setup apply projects/researcher-a.yaml
        coldpress-setup apply users/asanaullah.yaml
        coldpress-setup apply projects/researcher-a.yaml --dry-run
    """
    # Detect config type by checking directory
    is_cluster_config = "/cluster/" in config_file or config_file.startswith("cluster/")
    is_user_config = "/users/" in config_file or config_file.startswith("users/")

    # Load kubeconfig
    try:
        k8s_config.load_incluster_config()
    except Exception:
        k8s_config.load_kube_config()

    if is_cluster_config:
        return apply_cluster_config(config_file, output, dry_run)
    elif is_user_config:
        # Load user config
        with open(config_file, "r") as f:
            config = yaml.safe_load(f)

        if "username" not in config:
            click.echo("Error: User config must include 'username'", err=True)
            return 1

        return apply_user_config(config, output, dry_run)
    else:
        # Load project config
        with open(config_file, "r") as f:
            config = yaml.safe_load(f)

        if "namespace" not in config:
            click.echo("Error: Project config must include 'namespace'", err=True)
            return 1

        return apply_project_config(config, output, dry_run)


def apply_cluster_config(config_file, output, dry_run):
    """Apply cluster-wide configuration (operators and Kueue resources)."""
    import subprocess
    import shutil

    click.echo("Applying cluster configuration...")
    click.echo(f"Config file: {config_file}")

    # If output specified, just copy the file
    if output:
        import shutil

        shutil.copy(config_file, output)
        click.echo(f"\nCluster config copied to: {output}")
        return 0

    if dry_run:
        click.echo("\nDry run - would apply the following:")
        with open(config_file, "r") as f:
            click.echo(f.read())
        return 0

    # Detect kubectl or oc
    kubectl_cmd = "kubectl"
    if shutil.which("oc"):
        kubectl_cmd = "oc"
    elif not shutil.which("kubectl"):
        click.echo("Error: Neither kubectl nor oc found in PATH", err=True)
        return 1

    click.echo(f"\nUsing {kubectl_cmd} to apply cluster config (as system:admin)...")
    result = subprocess.run(
        [kubectl_cmd, "apply", "--as", "system:admin", "-f", config_file],
        capture_output=True,
        text=True,
    )

    if result.returncode == 0:
        click.echo(result.stdout)
        click.echo("\nCluster configuration applied successfully!")
        click.echo("\nResources created:")
        click.echo("  - Kueue operator")
        click.echo("  - JobSet operator")
        click.echo("  - ResourceFlavors (node0, node1)")
        click.echo("  - ClusterQueue (cluster-queue-coldpress)")
    else:
        click.echo(f"Error applying cluster config:\n{result.stderr}", err=True)
        return 1

    click.echo("\nNext steps:")
    click.echo("  1. Verify: oc get clusterqueues")
    click.echo("  2. Verify: oc get resourceflavors")
    click.echo(
        "  3. Apply project configs: coldpress-setup apply projects/<project>.yaml"
    )

    return 0


def apply_project_config(config, output, dry_run):
    """Apply project configuration (Namespace, PVC, LocalQueue, RBAC)."""
    from .generator import generate_project_manifests

    namespace = config.get("namespace")
    if not namespace:
        click.echo("Error: Project config must include 'namespace'", err=True)
        return 1

    click.echo("Applying project configuration...")
    click.echo(f"Namespace: {namespace}")

    # Generate manifests
    click.echo("\nGenerating project manifests...")
    manifests = generate_project_manifests(config)

    ns_count = len(manifests.get("namespaces", []))
    kueue_count = len(manifests.get("kueue", []))
    storage_count = len(manifests.get("storage", []))
    rbac_count = len(manifests.get("rbac", []))

    click.echo(f"  Namespace: {ns_count}")
    click.echo(f"  LocalQueue: {kueue_count}")
    click.echo(f"  PVC: {storage_count}")
    click.echo(f"  RBAC: {rbac_count}")

    # Output to file if requested
    if output:
        yaml_content = manifests_to_yaml(manifests)
        with open(output, "w") as f:
            f.write(yaml_content)
        click.echo(f"\nManifests written to: {output}")
        return 0

    if dry_run:
        click.echo("\nDry run complete (no changes applied)")
        return 0

    # Apply manifests
    return apply_manifests_to_cluster(manifests, "project", namespace)


def apply_user_config(config, output, dry_run):
    """Apply user configuration (RBAC RoleBindings)."""
    from .generator import generate_user_rbac

    username = config.get("username")
    namespaces = config.get("namespaces", [])

    if not username:
        click.echo("Error: User config must include 'username'", err=True)
        return 1

    if not namespaces:
        click.echo("Error: User config must include 'namespaces' list", err=True)
        return 1

    click.echo("Applying user configuration...")
    click.echo(f"Username: {username}")
    click.echo(f"Namespaces: {', '.join(namespaces)}")

    # Generate RBAC manifests
    click.echo("\nGenerating user RBAC...")
    rbac_manifests = generate_user_rbac(username, namespaces)
    click.echo(f"  RoleBindings: {len(rbac_manifests)}")

    manifests = {"rbac": rbac_manifests}

    # Output to file if requested
    if output:
        yaml_content = manifests_to_yaml(manifests)
        with open(output, "w") as f:
            f.write(yaml_content)
        click.echo(f"\nManifests written to: {output}")
        return 0

    if dry_run:
        click.echo("\nDry run complete (no changes applied)")
        return 0

    # Apply manifests
    return apply_manifests_to_cluster(manifests, "user", username)


def apply_manifests_to_cluster(manifests, config_type, namespace=None):
    """Apply manifests to cluster using oc/kubectl."""
    import subprocess
    import shutil

    click.echo("\nApplying manifests...")
    temp_file = "/tmp/coldpress-manifests.yaml"
    yaml_content = manifests_to_yaml(manifests)

    with open(temp_file, "w") as f:
        f.write(yaml_content)

    # Detect kubectl or oc
    kubectl_cmd = "kubectl"
    if shutil.which("oc"):
        kubectl_cmd = "oc"
    elif not shutil.which("kubectl"):
        click.echo("Error: Neither kubectl nor oc found in PATH", err=True)
        return 1

    click.echo(f"Using {kubectl_cmd} to apply manifests (as system:admin)...")
    result = subprocess.run(
        [kubectl_cmd, "apply", "--as", "system:admin", "-f", temp_file],
        capture_output=True,
        text=True,
    )

    if result.returncode == 0:
        click.echo(result.stdout)
        click.echo("\nConfiguration applied successfully!")
    else:
        click.echo(f"Error applying manifests:\n{result.stderr}", err=True)
        return 1

    # Cleanup temp file
    os.remove(temp_file)

    # Summary
    if config_type == "cluster":
        kueue_count = len(manifests.get("kueue", []))
        click.echo("\nCluster Configuration Summary:")
        click.echo(f"  Kueue resources: {kueue_count}")
        click.echo("")
        click.echo("Next steps:")
        click.echo("  1. Verify: oc get clusterqueues")
        click.echo("  2. Verify: oc get resourceflavors")
        click.echo(
            "  3. Apply project configs: coldpress-setup apply projects/<project>.yaml"
        )
    elif config_type == "user":
        rbac_count = len(manifests.get("rbac", []))
        click.echo("\nUser Configuration Summary:")
        click.echo(f"  Username: {namespace}")  # namespace param is reused for username
        click.echo(f"  RoleBindings: {rbac_count}")
        click.echo("")
        click.echo("Next steps:")
        click.echo("  1. User can now submit JobSets to granted namespaces")
        click.echo(
            "  2. Generate jobs: coldpress generate --config examples/job/config.yaml"
        )
    else:  # project
        click.echo("\nProject Configuration Summary:")
        click.echo(f"  Namespace: {namespace}")
        click.echo("")
        click.echo("Next steps:")
        click.echo(f"  1. Verify: oc get namespace {namespace}")
        click.echo(f"  2. Verify: oc get pvc -n {namespace}")
        click.echo(
            "  3. Apply user configs: coldpress-setup apply users/<username>.yaml"
        )

    return 0


@cli.command()
def verify():
    """
    Verify project resources exist in the cluster.

    Checks namespaces, PVCs, and permissions for all projects in $COLDPRESS_PROJECT_DIR (default: projects/).

    Examples:
        coldpress-setup verify
        COLDPRESS_PROJECT_DIR=/path/to/projects coldpress-setup verify
    """
    # Load all project configs
    if not os.path.exists(PROJECT_DIR):
        click.echo(
            f"Error: Project config directory not found: {PROJECT_DIR}", err=True
        )
        click.echo(
            f"Set COLDPRESS_PROJECT_DIR environment variable or create {PROJECT_DIR}/",
            err=True,
        )
        return 1

    project_files = [f for f in os.listdir(PROJECT_DIR) if f.endswith(".yaml")]
    if not project_files:
        click.echo(f"No project configs found in: {PROJECT_DIR}", err=True)
        return 1

    click.echo(f"Verifying {len(project_files)} project(s) from {PROJECT_DIR}...\n")

    # Load kubeconfig
    try:
        k8s_config.load_incluster_config()
    except Exception:
        k8s_config.load_kube_config()

    v1 = client.CoreV1Api()

    all_ok = True
    for project_file in sorted(project_files):
        project_path = os.path.join(PROJECT_DIR, project_file)
        with open(project_path, "r") as f:
            project_config = yaml.safe_load(f)

        project_name = project_config.get("project")
        namespace = project_config.get("namespace")
        storage = project_config.get("storage", {})

        click.echo(f"Project: {project_name}")
        click.echo(f"  Config: {project_file}")

        # Check namespace
        try:
            v1.read_namespace(namespace)
            click.echo(f"  ✓ Namespace: {namespace}")
        except Exception:
            click.echo(f"  ✗ Namespace: {namespace} (NOT FOUND)", err=True)
            all_ok = False

        # Check PVCs
        for pvc_type, pvc_name in storage.items():
            try:
                v1.read_namespaced_persistent_volume_claim(pvc_name, namespace)
                click.echo(f"  ✓ PVC ({pvc_type}): {pvc_name}")
            except Exception:
                # Check if it's a shared PVC in different namespace (like coldpress-model-storage)
                if pvc_type == "models":
                    click.echo(
                        f"  ⚠ PVC ({pvc_type}): {pvc_name} (check if shared PVC exists)"
                    )
                else:
                    click.echo(
                        f"  ✗ PVC ({pvc_type}): {pvc_name} (NOT FOUND)", err=True
                    )
                    all_ok = False

        click.echo("")

    if all_ok:
        click.echo("✓ All project resources verified successfully!")
        return 0
    else:
        click.echo(
            "✗ Some resources are missing. Run 'coldpress-setup apply' to create them.",
            err=True,
        )
        return 1


if __name__ == "__main__":
    cli()
