# Generated by: Claude Sonnet 4.5
"""Generate Kubernetes manifests for Coldpress cluster setup."""

import json
import yaml

# Standard labels for all Coldpress-managed resources
COLDPRESS_LABELS = {
    "app.kubernetes.io/managed-by": "coldpress",
    "app.kubernetes.io/version": "0.2.0",
}


def generate_kueue_resource_flavors(nodes):
    """Generate Kueue ResourceFlavor manifests for each node.

    Args:
        nodes: List of node configs. Node ID is assigned based on position in list.
    """
    flavors = []
    for node_id, node in enumerate(nodes):
        flavor = {
            "apiVersion": "kueue.x-k8s.io/v1beta1",
            "kind": "ResourceFlavor",
            "metadata": {
                "name": f"node{node_id}",
                "labels": COLDPRESS_LABELS.copy(),
            },
            "spec": {"nodeLabels": {"coldpress.node": str(node_id)}},
        }
        flavors.append(flavor)

    return flavors


def generate_cluster_queue(name, nodes):
    """Generate Kueue ClusterQueue manifest.

    Args:
        name: ClusterQueue name
        nodes: List of node configs. Node ID is assigned based on position in list.

    Note:
        RoCE NIC resources are currently disabled. The roce_nics field in cluster
        config is kept for reference but not used in resource generation.
    """
    # Build list of all covered resources across all nodes
    covered_resources = ["cpu", "memory", "nvidia.com/gpu"]

    # NOTE: RoCE NIC resources disabled for now
    # Keep roce_nics in cluster config for reference, but don't generate resources

    # Build flavors list with resources for each node
    flavors = []
    for node_id, node in enumerate(nodes):
        gpus = node.get("gpus", 0)
        # roce_nics = node.get("roce_nics", 0)  # Kept in config but not used

        resources = [
            {"name": "cpu", "nominalQuota": "256"},
            {"name": "memory", "nominalQuota": "1024Gi"},
            {"name": "nvidia.com/gpu", "nominalQuota": str(gpus)},
        ]

        # NOTE: RoCE NIC resources disabled - not added to resources list

        flavors.append({"name": f"node{node_id}", "resources": resources})

    # Create single resourceGroup with all flavors
    cluster_queue = {
        "apiVersion": "kueue.x-k8s.io/v1beta1",
        "kind": "ClusterQueue",
        "metadata": {
            "name": name,
            "labels": COLDPRESS_LABELS.copy(),
        },
        "spec": {
            "namespaceSelector": {},
            "resourceGroups": [
                {"coveredResources": covered_resources, "flavors": flavors}
            ],
        },
    }

    return cluster_queue


def generate_namespace(name, storage_size, privileged=False):
    """Generate namespace manifest with labels and annotations."""
    # Merge standard labels with namespace-specific labels
    ns_labels = COLDPRESS_LABELS.copy()
    ns_labels["kueue.openshift.io/managed"] = "true"

    if privileged:
        ns_labels["pod-security.kubernetes.io/enforce"] = "privileged"
        ns_labels["pod-security.kubernetes.io/audit"] = "privileged"
        ns_labels["pod-security.kubernetes.io/warn"] = "privileged"
    else:
        ns_labels["pod-security.kubernetes.io/enforce"] = "restricted"

    namespace = {
        "apiVersion": "v1",
        "kind": "Namespace",
        "metadata": {"name": name, "labels": ns_labels},
    }

    return namespace


def generate_local_queue(namespace, cluster_queue_name):
    """Generate LocalQueue manifest for a namespace."""
    local_queue = {
        "apiVersion": "kueue.x-k8s.io/v1beta1",
        "kind": "LocalQueue",
        "metadata": {
            "name": f"coldpress-local-queue-{namespace}",
            "namespace": namespace,
            "labels": COLDPRESS_LABELS.copy(),
        },
        "spec": {"clusterQueue": cluster_queue_name},
    }

    return local_queue


def generate_pvc(name, namespace, storage_size, storage_class):
    """Generate PersistentVolumeClaim manifest."""
    pvc = {
        "apiVersion": "v1",
        "kind": "PersistentVolumeClaim",
        "metadata": {
            "name": name,
            "namespace": namespace,
            "labels": COLDPRESS_LABELS.copy(),
        },
        "spec": {
            "accessModes": ["ReadWriteMany"],
            "storageClassName": storage_class,
            "resources": {"requests": {"storage": storage_size}},
        },
    }

    return pvc


def generate_rbac(namespace, targets="jobset"):
    """Generate RBAC manifests for namespace (ServiceAccount, Role, RoleBinding).

    Args:
        namespace: Kubernetes namespace name
        targets: Comma-separated list of target platforms (jobset, kubeflow)
    """
    rbac = []

    # ServiceAccount
    sa = {
        "apiVersion": "v1",
        "kind": "ServiceAccount",
        "metadata": {
            "name": "coldpress-user",
            "namespace": namespace,
            "labels": COLDPRESS_LABELS.copy(),
        },
    }
    rbac.append(sa)

    # Parse targets
    target_list = [t.strip() for t in targets.split(",")]
    enable_jobset = "jobset" in target_list
    enable_kubeflow = "kubeflow" in target_list

    # Build RBAC rules based on enabled targets
    rules = []

    # JobSet permissions
    if enable_jobset:
        rules.append(
            {
                "apiGroups": ["jobset.x-k8s.io"],
                "resources": ["jobsets"],
                "verbs": ["create", "get", "list", "watch", "delete"],
            }
        )

    # Kubeflow Training Operator permissions
    if enable_kubeflow:
        rules.append(
            {
                "apiGroups": ["kubeflow.org"],
                "resources": ["pytorchjobs", "tfjobs", "mpijobs", "xgboostjobs"],
                "verbs": ["create", "get", "list", "watch", "delete"],
            }
        )
        # KServe permissions
        rules.append(
            {
                "apiGroups": ["serving.kserve.io"],
                "resources": ["inferenceservices"],
                "verbs": ["create", "get", "list", "watch", "delete"],
            }
        )

    # Common permissions (always needed)
    rules.extend(
        [
            {
                "apiGroups": ["batch"],
                "resources": ["jobs"],
                "verbs": ["get", "list", "watch"],
            },
            {
                "apiGroups": [""],
                "resources": ["pods", "pods/log"],
                "verbs": ["create", "get", "list", "watch", "delete"],
            },
            {"apiGroups": [""], "resources": ["pods/exec"], "verbs": ["create"]},
            {
                "apiGroups": [""],
                "resources": ["services"],
                "verbs": ["create", "get", "list", "watch", "delete"],
            },
            {
                "apiGroups": [""],
                "resources": ["configmaps"],
                "verbs": [
                    "create",
                    "get",
                    "list",
                    "watch",
                    "update",
                    "patch",
                    "delete",
                ],
            },
        ]
    )

    # Role - allow managing resources based on enabled targets
    role = {
        "apiVersion": "rbac.authorization.k8s.io/v1",
        "kind": "Role",
        "metadata": {
            "name": "coldpress-user-role",
            "namespace": namespace,
            "labels": COLDPRESS_LABELS.copy(),
        },
        "rules": rules,
    }
    rbac.append(role)

    # RoleBinding for ServiceAccount (used by pods)
    binding = {
        "apiVersion": "rbac.authorization.k8s.io/v1",
        "kind": "RoleBinding",
        "metadata": {
            "name": "coldpress-user-binding",
            "namespace": namespace,
            "labels": COLDPRESS_LABELS.copy(),
        },
        "roleRef": {
            "apiGroup": "rbac.authorization.k8s.io",
            "kind": "Role",
            "name": "coldpress-user-role",
        },
        "subjects": [
            {"kind": "ServiceAccount", "name": "coldpress-user", "namespace": namespace}
        ],
    }
    rbac.append(binding)

    return rbac


def generate_user_rbac(username, namespaces):
    """Generate RBAC RoleBindings for a user across multiple namespaces.

    Args:
        username: Username to grant permissions
        namespaces: List of namespace names

    Returns:
        list: RoleBinding manifests
    """
    rbac = []

    for namespace in namespaces:
        binding = {
            "apiVersion": "rbac.authorization.k8s.io/v1",
            "kind": "RoleBinding",
            "metadata": {
                "name": f"coldpress-user-{username}",
                "namespace": namespace,
                "labels": COLDPRESS_LABELS.copy(),
            },
            "roleRef": {
                "apiGroup": "rbac.authorization.k8s.io",
                "kind": "Role",
                "name": "coldpress-user-role",
            },
            "subjects": [
                {
                    "kind": "User",
                    "name": username,
                    "apiGroup": "rbac.authorization.k8s.io",
                }
            ],
        }
        rbac.append(binding)

    return rbac


def generate_privileged_scc_binding(namespace):
    """Generate RoleBinding for privileged SCC (OpenShift only)."""
    return {
        "apiVersion": "rbac.authorization.k8s.io/v1",
        "kind": "RoleBinding",
        "metadata": {
            "name": f"{namespace}-privileged-binding",
            "namespace": namespace,
            "labels": COLDPRESS_LABELS.copy(),
        },
        "roleRef": {
            "apiGroup": "rbac.authorization.k8s.io",
            "kind": "ClusterRole",
            "name": "system:openshift:scc:privileged",
        },
        "subjects": [
            {"kind": "ServiceAccount", "name": "default", "namespace": namespace}
        ],
    }


def generate_sriov_network_attachments(namespace, roce_nics):
    """Generate NetworkAttachmentDefinitions for SRIOV RDMA networks.

    NOTE: This function is currently disabled. RoCE NIC support is kept in
    cluster config for reference but NetworkAttachmentDefinitions are not
    generated. This function is preserved for future use.
    """
    attachments = []
    for nic_id in range(roce_nics):
        nic_name = f"eno{5 + nic_id}"

        # Build CNI config using json.dumps to prevent injection
        cni_config = {
            "cniVersion": "0.3.1",
            "name": f"sriov-rdma-net-{nic_name}",
            "type": "sriov",
            "ipam": {"type": "whereabouts", "range": "192.168.1.0/24"},
        }

        attachment = {
            "apiVersion": "k8s.cni.cncf.io/v1",
            "kind": "NetworkAttachmentDefinition",
            "metadata": {
                "name": f"sriov-rdma-net-{nic_name}",
                "namespace": namespace,
                "labels": COLDPRESS_LABELS.copy(),
                "annotations": {
                    "k8s.v1.cni.cncf.io/resourceName": f"openshift.io/{nic_name}np0rdma"
                },
            },
            "spec": {"config": json.dumps(cni_config)},
        }
        attachments.append(attachment)
    return attachments


def generate_cluster_manifests(config):
    """
    Generate cluster-wide Kueue manifests (ResourceFlavors, ClusterQueue).

    Args:
        config: Cluster config with nodes and cluster_queue

    Returns:
        dict: Categorized manifests with 'kueue' key
    """
    nodes = config.get("nodes", [])
    cluster_queue_name = config.get("cluster_queue", "cluster-queue-default")

    manifests = {"kueue": []}

    # Kueue ResourceFlavors (one per node)
    manifests["kueue"].extend(generate_kueue_resource_flavors(nodes))

    # ClusterQueue (aggregates all nodes)
    manifests["kueue"].append(generate_cluster_queue(cluster_queue_name, nodes))

    return manifests


def generate_project_manifests(config):
    """
    Generate project-level manifests (Namespace, LocalQueue, PVC).

    Args:
        config: Project config with namespace, storage

    Returns:
        dict: Categorized manifests
    """
    namespace = config.get("namespace")
    storage_config = config.get("storage", {})
    cluster_queue_name = config.get("cluster_queue", "cluster-queue-test")
    storage_class = config.get("storage_class", "nfs-csi")

    # Get storage size for results PVC
    storage_size = storage_config.get("size", "100Gi")
    privileged = config.get("privileged", False)

    manifests = {"namespaces": [], "kueue": [], "storage": [], "rbac": []}

    # Namespace with consistent labels (using shared function)
    manifests["namespaces"].append(
        generate_namespace(namespace, storage_size, privileged)
    )

    # LocalQueue (needed for both jobset and kubeflow targets)
    # Both JobSet and Kubeflow Training Operator jobs use Kueue for resource management
    manifests["kueue"].append(generate_local_queue(namespace, cluster_queue_name))

    # Storage PVC (for results)
    if storage_config.get("results"):
        pvc_name = storage_config["results"]
        manifests["storage"].append(
            generate_pvc(pvc_name, namespace, storage_size, storage_class)
        )

    # RBAC (ServiceAccount, Role, RoleBinding)
    targets = config.get("targets", "jobset")
    manifests["rbac"].extend(generate_rbac(namespace, targets))

    return manifests


def generate_all_manifests(config):
    """
    Generate all Kubernetes manifests from config (legacy/combined mode).

    Returns:
        dict: Categorized manifests
    """
    nodes = config.get("nodes", [])
    namespaces_config = config.get("namespaces", [])
    cluster_queue_name = config.get("cluster_queue", "cluster-queue-default")
    storage_class = config.get("storage_class", "nfs-csi")

    # NOTE: RoCE NIC support disabled - roce_nics field kept in config for reference only
    # max_roce_nics = max([node.get("roce_nics", 0) for node in nodes], default=0)

    manifests = {
        "kueue": [],
        "namespaces": [],
        "storage": [],
        "rbac": [],
        # "network": [],  # RoCE NIC NetworkAttachments disabled
    }

    # Kueue ResourceFlavors
    manifests["kueue"].extend(generate_kueue_resource_flavors(nodes))

    # ClusterQueue
    manifests["kueue"].append(generate_cluster_queue(cluster_queue_name, nodes))

    # Namespaces, LocalQueues, PVCs, RBAC, NetworkAttachments
    for ns_config in namespaces_config:
        ns_name = ns_config["name"]
        storage_size = ns_config.get("storage", "100Gi")
        privileged = ns_config.get("privileged", False)

        # Namespace
        manifests["namespaces"].append(
            generate_namespace(ns_name, storage_size, privileged)
        )

        # LocalQueue
        manifests["namespaces"].append(
            generate_local_queue(ns_name, cluster_queue_name)
        )

        # Storage PVC
        manifests["storage"].append(
            generate_pvc(
                f"coldpress-{ns_name}-storage", ns_name, storage_size, storage_class
            )
        )

        # RBAC
        if privileged:
            # Privileged SCC binding for admin namespaces (OpenShift)
            manifests["rbac"].append(generate_privileged_scc_binding(ns_name))
        else:
            # Regular user RBAC
            manifests["rbac"].extend(generate_rbac(ns_name))

        # NOTE: NetworkAttachmentDefinitions for SRIOV disabled
        # RoCE NIC support kept in cluster config for reference only
        # if max_roce_nics > 0 and not privileged:
        #     manifests["network"].extend(
        #         generate_sriov_network_attachments(ns_name, max_roce_nics)
        #     )

    return manifests


def manifests_to_yaml(manifests):
    """Convert manifests dict to YAML string."""
    all_docs = []

    # Combine in order: kueue, namespaces, storage, rbac
    # Note: "network" category removed (RoCE NIC support disabled)
    for category in ["kueue", "namespaces", "storage", "rbac"]:
        all_docs.extend(manifests.get(category, []))

    return yaml.dump_all(all_docs, default_flow_style=False, sort_keys=False)
