# Generated by: Claude Sonnet 4.5
"""Generate Kubernetes manifests for Coldpress cluster setup."""

import yaml


def generate_kueue_resource_flavors(nodes):
    """Generate Kueue ResourceFlavor manifests for each node.

    Args:
        nodes: List of node configs. Node ID is assigned based on position in list.
    """
    flavors = []
    for node_id, node in enumerate(nodes):
        flavor = {
            "apiVersion": "kueue.x-k8s.io/v1beta1",
            "kind": "ResourceFlavor",
            "metadata": {"name": f"node{node_id}"},
            "spec": {"nodeLabels": {"coldpress.node": str(node_id)}},
        }
        flavors.append(flavor)

    return flavors


def generate_cluster_queue(name, nodes):
    """Generate Kueue ClusterQueue manifest.

    Args:
        name: ClusterQueue name
        nodes: List of node configs. Node ID is assigned based on position in list.
    """
    # Build list of all covered resources across all nodes
    covered_resources = ["cpu", "memory", "nvidia.com/gpu"]

    # Check if any node has RoCE NICs and add them to covered resources
    max_roce_nics = max([node.get("roce_nics", 0) for node in nodes], default=0)
    if max_roce_nics > 0:
        for nic_id in range(max_roce_nics):
            covered_resources.append(f"openshift.io/eno{5 + nic_id}np0rdma")

    # Build flavors list with resources for each node
    flavors = []
    for node_id, node in enumerate(nodes):
        gpus = node.get("gpus", 0)
        roce_nics = node.get("roce_nics", 0)

        resources = [
            {"name": "cpu", "nominalQuota": "256"},
            {"name": "memory", "nominalQuota": "1024Gi"},
            {"name": "nvidia.com/gpu", "nominalQuota": str(gpus)},
        ]

        # Add RoCE NICs if present
        if max_roce_nics > 0:
            for nic_id in range(max_roce_nics):
                # Set quota to 1 if this node has this NIC, 0 otherwise
                quota = "1" if nic_id < roce_nics else "0"
                resources.append(
                    {
                        "name": f"openshift.io/eno{5 + nic_id}np0rdma",
                        "nominalQuota": quota,
                    }
                )

        flavors.append({"name": f"node{node_id}", "resources": resources})

    # Create single resourceGroup with all flavors
    cluster_queue = {
        "apiVersion": "kueue.x-k8s.io/v1beta1",
        "kind": "ClusterQueue",
        "metadata": {"name": name},
        "spec": {
            "namespaceSelector": {},
            "resourceGroups": [
                {"coveredResources": covered_resources, "flavors": flavors}
            ],
        },
    }

    return cluster_queue


def generate_namespace(name, storage_size, privileged=False):
    """Generate namespace manifest with labels and annotations."""
    namespace = {
        "apiVersion": "v1",
        "kind": "Namespace",
        "metadata": {"name": name, "labels": {"kueue.openshift.io/managed": "true"}},
    }

    if privileged:
        namespace["metadata"]["labels"]["pod-security.kubernetes.io/enforce"] = (
            "privileged"
        )
        namespace["metadata"]["labels"]["pod-security.kubernetes.io/audit"] = (
            "privileged"
        )
        namespace["metadata"]["labels"]["pod-security.kubernetes.io/warn"] = (
            "privileged"
        )
    else:
        namespace["metadata"]["labels"]["pod-security.kubernetes.io/enforce"] = (
            "restricted"
        )

    return namespace


def generate_local_queue(namespace, cluster_queue_name):
    """Generate LocalQueue manifest for a namespace."""
    local_queue = {
        "apiVersion": "kueue.x-k8s.io/v1beta1",
        "kind": "LocalQueue",
        "metadata": {"name": f"local-queue-{namespace}", "namespace": namespace},
        "spec": {"clusterQueue": cluster_queue_name},
    }

    return local_queue


def generate_pvc(name, namespace, storage_size, storage_class):
    """Generate PersistentVolumeClaim manifest."""
    pvc = {
        "apiVersion": "v1",
        "kind": "PersistentVolumeClaim",
        "metadata": {"name": name, "namespace": namespace},
        "spec": {
            "accessModes": ["ReadWriteMany"],
            "storageClassName": storage_class,
            "resources": {"requests": {"storage": storage_size}},
        },
    }

    return pvc


def generate_rbac(namespace):
    """Generate RBAC manifests for namespace (ServiceAccount, Role, RoleBinding)."""
    rbac = []

    # ServiceAccount
    sa = {
        "apiVersion": "v1",
        "kind": "ServiceAccount",
        "metadata": {"name": "coldpress-user", "namespace": namespace},
    }
    rbac.append(sa)

    # Role - allow managing JobSets and viewing related resources
    role = {
        "apiVersion": "rbac.authorization.k8s.io/v1",
        "kind": "Role",
        "metadata": {"name": "coldpress-user-role", "namespace": namespace},
        "rules": [
            {
                "apiGroups": ["jobset.x-k8s.io"],
                "resources": ["jobsets"],
                "verbs": ["create", "get", "list", "watch", "delete"],
            },
            {
                "apiGroups": ["batch"],
                "resources": ["jobs"],
                "verbs": ["get", "list", "watch"],
            },
            {
                "apiGroups": [""],
                "resources": ["pods", "pods/log"],
                "verbs": ["create", "get", "list", "watch", "delete"],
            },
            {"apiGroups": [""], "resources": ["pods/exec"], "verbs": ["create"]},
            {
                "apiGroups": [""],
                "resources": ["services"],
                "verbs": ["create", "get", "list", "watch", "delete"],
            },
            {
                "apiGroups": [""],
                "resources": ["configmaps"],
                "verbs": ["create", "get", "list", "watch", "delete"],
            },
        ],
    }
    rbac.append(role)

    # RoleBinding for ServiceAccount (used by pods)
    binding = {
        "apiVersion": "rbac.authorization.k8s.io/v1",
        "kind": "RoleBinding",
        "metadata": {"name": "coldpress-user-binding", "namespace": namespace},
        "roleRef": {
            "apiGroup": "rbac.authorization.k8s.io",
            "kind": "Role",
            "name": "coldpress-user-role",
        },
        "subjects": [
            {"kind": "ServiceAccount", "name": "coldpress-user", "namespace": namespace}
        ],
    }
    rbac.append(binding)

    return rbac


def generate_user_rbac(username, namespaces):
    """Generate RBAC RoleBindings for a user across multiple namespaces.

    Args:
        username: Username to grant permissions
        namespaces: List of namespace names

    Returns:
        list: RoleBinding manifests
    """
    rbac = []

    for namespace in namespaces:
        binding = {
            "apiVersion": "rbac.authorization.k8s.io/v1",
            "kind": "RoleBinding",
            "metadata": {"name": f"coldpress-user-{username}", "namespace": namespace},
            "roleRef": {
                "apiGroup": "rbac.authorization.k8s.io",
                "kind": "Role",
                "name": "coldpress-user-role",
            },
            "subjects": [
                {
                    "kind": "User",
                    "name": username,
                    "apiGroup": "rbac.authorization.k8s.io",
                }
            ],
        }
        rbac.append(binding)

    return rbac


def generate_privileged_scc_binding(namespace):
    """Generate RoleBinding for privileged SCC (OpenShift only)."""
    return {
        "apiVersion": "rbac.authorization.k8s.io/v1",
        "kind": "RoleBinding",
        "metadata": {"name": f"{namespace}-privileged-binding", "namespace": namespace},
        "roleRef": {
            "apiGroup": "rbac.authorization.k8s.io",
            "kind": "ClusterRole",
            "name": "system:openshift:scc:privileged",
        },
        "subjects": [
            {"kind": "ServiceAccount", "name": "default", "namespace": namespace}
        ],
    }


def generate_sriov_network_attachments(namespace, roce_nics):
    """Generate NetworkAttachmentDefinitions for SRIOV RDMA networks."""
    attachments = []
    for nic_id in range(roce_nics):
        nic_name = f"eno{5 + nic_id}"
        attachment = {
            "apiVersion": "k8s.cni.cncf.io/v1",
            "kind": "NetworkAttachmentDefinition",
            "metadata": {
                "name": f"sriov-rdma-net-{nic_name}",
                "namespace": namespace,
                "annotations": {
                    "k8s.v1.cni.cncf.io/resourceName": f"openshift.io/{nic_name}np0rdma"
                },
            },
            "spec": {
                "config": f'{{"cniVersion": "0.3.1", "name": "sriov-rdma-net-{nic_name}", "type": "sriov", "ipam": {{"type": "whereabouts", "range": "192.168.1.0/24"}}}}'
            },
        }
        attachments.append(attachment)
    return attachments


def generate_cluster_manifests(config):
    """
    Generate cluster-wide Kueue manifests (ResourceFlavors, ClusterQueue).

    Args:
        config: Cluster config with nodes and cluster_queue

    Returns:
        dict: Categorized manifests with 'kueue' key
    """
    nodes = config.get("nodes", [])
    cluster_queue_name = config.get("cluster_queue", "cluster-queue-default")

    manifests = {"kueue": []}

    # Kueue ResourceFlavors (one per node)
    manifests["kueue"].extend(generate_kueue_resource_flavors(nodes))

    # ClusterQueue (aggregates all nodes)
    manifests["kueue"].append(generate_cluster_queue(cluster_queue_name, nodes))

    return manifests


def generate_project_manifests(config):
    """
    Generate project-level manifests (Namespace, LocalQueue, PVC).

    Args:
        config: Project config with namespace, storage

    Returns:
        dict: Categorized manifests
    """
    namespace = config.get("namespace")
    storage_config = config.get("storage", {})
    cluster_queue_name = config.get("cluster_queue", "cluster-queue-test")
    storage_class = config.get("storage_class", "nfs-csi")

    # Get storage size for results PVC
    storage_size = storage_config.get("size", "100Gi")

    manifests = {"namespaces": [], "kueue": [], "storage": [], "rbac": []}

    # Namespace with kueue.openshift.io/managed label
    namespace_manifest = {
        "apiVersion": "v1",
        "kind": "Namespace",
        "metadata": {
            "name": namespace,
            "labels": {"kueue.openshift.io/managed": "true"},
        },
    }
    manifests["namespaces"].append(namespace_manifest)

    # LocalQueue
    manifests["kueue"].append(generate_local_queue(namespace, cluster_queue_name))

    # Storage PVC (for results)
    if storage_config.get("results"):
        pvc_name = storage_config["results"]
        manifests["storage"].append(
            generate_pvc(pvc_name, namespace, storage_size, storage_class)
        )

    # RBAC (ServiceAccount, Role, RoleBinding)
    manifests["rbac"].extend(generate_rbac(namespace))

    return manifests


def generate_all_manifests(config):
    """
    Generate all Kubernetes manifests from config (legacy/combined mode).

    Returns:
        dict: Categorized manifests
    """
    nodes = config.get("nodes", [])
    namespaces_config = config.get("namespaces", [])
    cluster_queue_name = config.get("cluster_queue", "cluster-queue-default")
    storage_class = config.get("storage_class", "nfs-csi")

    # Check if any node has RoCE NICs
    max_roce_nics = max([node.get("roce_nics", 0) for node in nodes], default=0)

    manifests = {
        "kueue": [],
        "namespaces": [],
        "storage": [],
        "rbac": [],
        "network": [],
    }

    # Kueue ResourceFlavors
    manifests["kueue"].extend(generate_kueue_resource_flavors(nodes))

    # ClusterQueue
    manifests["kueue"].append(generate_cluster_queue(cluster_queue_name, nodes))

    # Namespaces, LocalQueues, PVCs, RBAC, NetworkAttachments
    for ns_config in namespaces_config:
        ns_name = ns_config["name"]
        storage_size = ns_config.get("storage", "100Gi")
        privileged = ns_config.get("privileged", False)

        # Namespace
        manifests["namespaces"].append(
            generate_namespace(ns_name, storage_size, privileged)
        )

        # LocalQueue
        manifests["namespaces"].append(
            generate_local_queue(ns_name, cluster_queue_name)
        )

        # Storage PVC
        manifests["storage"].append(
            generate_pvc(f"{ns_name}-storage", ns_name, storage_size, storage_class)
        )

        # RBAC
        if privileged:
            # Privileged SCC binding for admin namespaces (OpenShift)
            manifests["rbac"].append(generate_privileged_scc_binding(ns_name))
        else:
            # Regular user RBAC
            manifests["rbac"].extend(generate_rbac(ns_name))

        # NetworkAttachmentDefinitions for SRIOV (if cluster has RoCE NICs)
        if max_roce_nics > 0 and not privileged:
            manifests["network"].extend(
                generate_sriov_network_attachments(ns_name, max_roce_nics)
            )

    return manifests


def manifests_to_yaml(manifests):
    """Convert manifests dict to YAML string."""
    all_docs = []

    # Combine in order: kueue, namespaces, storage, network, rbac
    for category in ["kueue", "namespaces", "storage", "network", "rbac"]:
        all_docs.extend(manifests.get(category, []))

    return yaml.dump_all(all_docs, default_flow_style=False, sort_keys=False)
