# Generated by: Claude Sonnet 4.5
"""Coldpress CLI - Generate JobSet and Kubeflow manifests for AI/HPC workloads."""

import click
import yaml
import os
import json
from datetime import datetime, timezone

from .jobset_generator import (
    generate_jobset_from_intent,
    jobset_to_yaml,
    services_to_yaml,
)
from .kubeflow_generator import kubeflow_to_yaml
from .script_gen import write_scripts
from coldpress_common import (
    validate_config,
    validate_intent,
    validate_project_config,
    validate_task_specs,
)
from pydantic import ValidationError

# Default directories (can be overridden with environment variables)
DISCOVERY_DIR = os.getenv("COLDPRESS_DISCOVERY_DIR", "discovery")
PROJECT_DIR = os.getenv("COLDPRESS_PROJECT_DIR", "projects")
OUTPUT_DIR = os.getenv("COLDPRESS_OUTPUT_DIR", "output")


@click.group()
@click.version_option(version="0.2.0")
def cli():
    """Coldpress - AI/HPC workload orchestration for Kubernetes/OpenShift."""
    pass


def _load_and_validate_config(
    config_path, project_override, discovery_override, output_override
):
    """Load and validate configuration from file and CLI args."""
    with open(config_path, "r") as f:
        config_data = yaml.safe_load(f)

    # Validate config schema
    try:
        validated_config = validate_config(config_data)
    except ValidationError as e:
        raise ValueError(f"Config validation failed: {e}") from e

    config_dir = os.path.dirname(os.path.abspath(config_path))
    project = project_override or validated_config.project

    # Handle discovery - CLI override or config (could be string or DiscoveryConfig)
    if discovery_override:
        # CLI override is always a simple string, convert to DiscoveryConfig format
        discovery = {"template": discovery_override, "tasks": "all"}
    elif validated_config.discovery:
        # From config file - already validated as DiscoveryConfig
        if isinstance(validated_config.discovery, str):
            discovery = {"template": validated_config.discovery, "tasks": "all"}
        else:
            discovery = {
                "template": validated_config.discovery.template,
                "tasks": validated_config.discovery.tasks,
            }
    else:
        discovery = None

    output_name = output_override or validated_config.output
    nodes_from_config = validated_config.nodes

    if not project:
        raise ValueError("Must provide --project or specify 'project' in config")

    return config_data, config_dir, project, discovery, output_name, nodes_from_config


def _load_intent(intent_path):
    """Load and validate intent.yaml."""
    if not os.path.exists(intent_path):
        raise FileNotFoundError(f"Could not find intent.yaml at {intent_path}")

    with open(intent_path, "r") as f:
        intent_data = yaml.safe_load(f)

    # Validate intent schema
    try:
        validated_intent = validate_intent(intent_data)
    except ValidationError as e:
        raise ValueError(f"Intent validation failed: {e}") from e

    return validated_intent


def _load_vk8s_jobs(job_spec_path):
    """Load vanilla Kubernetes Jobs from job-spec.yaml."""
    if not os.path.exists(job_spec_path):
        raise FileNotFoundError(f"Could not find job-spec.yaml at {job_spec_path}")

    with open(job_spec_path, "r") as f:
        manifests = list(yaml.safe_load_all(f))

    if not manifests:
        raise ValueError("job-spec.yaml is empty")

    # Extract Jobs and pass through other resources
    jobs = {}
    other_resources = []

    for manifest in manifests:
        if manifest.get("kind") == "Job" and manifest.get("apiVersion") == "batch/v1":
            job_name = manifest.get("metadata", {}).get("name")
            if not job_name:
                raise ValueError("Job manifest missing metadata.name")
            jobs[job_name] = manifest
        else:
            # Pass through non-Job resources (Services, ConfigMaps, etc.)
            other_resources.append(manifest)

    if not jobs:
        raise ValueError("No batch/v1 Jobs found in job-spec.yaml")

    return jobs, other_resources


def _load_task_specs(config_dir):
    """Load and validate task specifications from job-spec.yaml (legacy format)."""
    job_spec_path = os.path.join(config_dir, "job-spec.yaml")
    if not os.path.exists(job_spec_path):
        raise FileNotFoundError(f"Could not find job-spec.yaml in {config_dir}")

    with open(job_spec_path, "r") as f:
        task_specs_data = list(yaml.safe_load_all(f))

    if not task_specs_data:
        raise ValueError("Job spec file is empty")

    # Validate task specifications
    try:
        validated_tasks = validate_task_specs(task_specs_data)
    except ValidationError as e:
        raise ValueError(f"Task spec validation failed: {e}") from e

    # Convert back to dict for compatibility with rest of code
    return [
        task.model_dump(by_alias=True, exclude_none=True) for task in validated_tasks
    ]


def _determine_job_name(task_specs):
    """Determine job name from task specifications."""
    if len(task_specs) == 1:
        return task_specs[0]["name"]
    return f"{task_specs[0]['name']}-workflow"


def _load_project_config(project_name):
    """Load project configuration file."""
    project_config_file = os.path.join(PROJECT_DIR, f"{project_name}.yaml")
    if not os.path.exists(project_config_file):
        raise FileNotFoundError(f"Project config not found: {project_config_file}")

    with open(project_config_file, "r") as f:
        project_config_data = yaml.safe_load(f)

    # Validate project config
    try:
        validated_project = validate_project_config(project_config_data)
    except ValidationError as e:
        raise ValueError(f"Project config validation failed: {e}") from e

    # Convert back to dict for compatibility
    project_config = validated_project.model_dump(by_alias=True, exclude_none=True)
    namespace = validated_project.namespace

    return project_config, namespace


def _prepare_configmap_files(config_dir, files_list, job_name):
    """Read and prepare files for ConfigMap."""
    if not files_list:
        return None

    configmap_name = f"coldpress-{job_name}-files"
    file_data = {}
    for file_name in files_list:
        file_path = os.path.join(config_dir, file_name)
        if not os.path.exists(file_path):
            raise FileNotFoundError(f"File not found: {file_path}")
        with open(file_path, "r") as f:
            file_data[file_name] = f.read()

    return {
        "name": configmap_name,
        "files": list(file_data.keys()),
        "data": file_data,
    }


def _allocate_nodes_for_tasks(task_specs, manual_nodes):
    """Allocate nodes for each task."""
    node_assignments = {}

    if manual_nodes:
        # User provided explicit node assignments
        for task_id, node_id in enumerate(manual_nodes):
            if task_id < len(task_specs):
                node_assignments[task_id] = node_id
        return node_assignments

    # Default: let Kubernetes scheduler decide (use "any" coldpress node)
    for task_id in range(len(task_specs)):
        node_assignments[task_id] = "any"

    return node_assignments


def _write_output_files(
    output_dir,
    manifest,
    services,
    job_spec,
    base_dir,
    config_dir,
    task_specs,
    node_assignments,
    manifest_type="jobset",
):
    """Write all generated files to output directory."""
    os.makedirs(output_dir, exist_ok=True)

    # Write manifest YAML based on type
    if manifest_type == "jobset":
        manifest_file = os.path.join(output_dir, "jobset.yaml")
        with open(manifest_file, "w") as f:
            f.write(jobset_to_yaml(manifest))
    elif manifest_type == "pytorchjob":
        manifest_file = os.path.join(output_dir, "pytorchjob.yaml")
        with open(manifest_file, "w") as f:
            f.write(kubeflow_to_yaml(manifest))
    elif manifest_type == "tfjob":
        manifest_file = os.path.join(output_dir, "tfjob.yaml")
        with open(manifest_file, "w") as f:
            f.write(kubeflow_to_yaml(manifest))
    elif manifest_type == "mpijob":
        manifest_file = os.path.join(output_dir, "mpijob.yaml")
        with open(manifest_file, "w") as f:
            f.write(kubeflow_to_yaml(manifest))
    elif manifest_type == "inferenceservice":
        manifest_file = os.path.join(output_dir, "inferenceservice.yaml")
        with open(manifest_file, "w") as f:
            f.write(kubeflow_to_yaml(manifest))

    # Write Services YAML if any (JobSet only)
    if services:
        services_file = os.path.join(output_dir, "services.yaml")
        with open(services_file, "w") as f:
            f.write(services_to_yaml(services))

    # Copy ConfigMap files
    configmap_name = None
    configmap_files = []
    if "configmap" in job_spec:
        import shutil

        cm_info = job_spec["configmap"]
        configmap_name = cm_info["name"]
        for file_name in cm_info["files"]:
            src_path = os.path.join(config_dir, file_name)
            dst_path = os.path.join(output_dir, file_name)
            shutil.copy(src_path, dst_path)
            configmap_files.append(file_name)

    # Write metadata
    metadata = {
        "job_name": job_spec["name"],
        "namespace": job_spec["namespace"],
        "backend": manifest_type,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "base_dir": base_dir,
        "node_assignments": node_assignments,
        "tasks": [
            {"name": t.get("name"), "containers": len(t.get("containers", []))}
            for t in task_specs
        ],
    }
    metadata_file = os.path.join(output_dir, "metadata.json")
    with open(metadata_file, "w") as f:
        json.dump(metadata, f, indent=2)

    # Generate bash scripts
    storage_pvc = job_spec.get("storage", {}).get(
        "results", f"coldpress-{job_spec['namespace']}-storage"
    )
    write_scripts(
        output_dir,
        job_spec["name"],  # Use original job name, not prefixed
        job_spec["namespace"],
        storage_pvc,
        base_dir,
        configmap_name,
        configmap_files,
        manifest_type,  # Pass manifest type to scripts
    )

    return output_dir


@cli.command()
@click.option(
    "-i",
    "--intent",
    required=True,
    help="Intent file specifying transformations (intent.yaml)",
    type=click.Path(exists=True),
)
def generate(intent):
    """
    Generate JobSet or Kubeflow YAML manifests from intent.yaml.

    The intent file specifies:
    - Target backend (jobset or kubeflow)
    - Transformations to apply to vanilla k8s job-spec.yaml
    - Task replication and dependencies

    The CLI auto-discovers job-spec.yaml in the same directory as intent.yaml.

    Environment Variables:
        COLDPRESS_DISCOVERY_DIR  - Discovery templates directory (default: discovery)
        COLDPRESS_PROJECT_DIR    - Project configs directory (default: projects)
        COLDPRESS_OUTPUT_DIR     - Default output directory (default: output)

    Examples:
        coldpress generate --intent examples/pytorch_ddp_training/intent.yaml
        coldpress generate -i examples/vllm_guidellm_benchmark/intent.yaml
    """
    try:
        # Load and validate intent.yaml
        intent_config = _load_intent(intent)
        intent_dir = os.path.dirname(os.path.abspath(intent))

        # Load vanilla k8s Jobs from job-spec.yaml
        job_spec_path = os.path.join(intent_dir, "job-spec.yaml")
        vk8s_jobs, other_resources = _load_vk8s_jobs(job_spec_path)

        # Load project config
        project_config, namespace = _load_project_config(intent_config.project)

        # Output path
        output_path = os.path.join(OUTPUT_DIR, intent_config.output)

        # Display generation info
        click.echo("Generating manifests")
        click.echo(f"Project: {intent_config.project}")
        click.echo(f"Namespace: {namespace}")
        click.echo(f"Tasks: {len(intent_config.tasks)}")
        for task in intent_config.tasks:
            replicas = task.replicas or 1
            nodes_info = f" (nodes: {task.nodes})" if task.nodes else ""
            click.echo(f"  - {task.name}: {replicas} replica(s){nodes_info}")

        # Use backend from intent.yaml
        backend = intent_config.target
        backend_name_map = {
            "kubeflow": "Kubeflow",
            "kserve": "KServe",
            "jobset": "JobSet",
        }
        backend_name = backend_name_map.get(backend, "JobSet")
        click.echo(f"Target: {backend_name}")

        # Generate manifests based on target
        if backend == "kubeflow":
            # Generate Kubeflow manifest (PyTorchJob)
            from .kubeflow_generator import (
                generate_pytorchjob_from_intent,
                kubeflow_to_yaml,
            )

            manifest, base_dir = generate_pytorchjob_from_intent(
                vk8s_jobs, intent_config, project_config, namespace
            )
            manifest_type = "pytorchjob"
            services = []  # Kubeflow doesn't use separate services
        elif backend == "kserve":
            # Generate KServe manifest (InferenceService)
            from .kubeflow_generator import (
                generate_inferenceservice_from_intent,
                kubeflow_to_yaml,
            )

            manifest, base_dir = generate_inferenceservice_from_intent(
                vk8s_jobs, intent_config, project_config, namespace
            )
            manifest_type = "inferenceservice"
            services = []  # KServe doesn't use separate services
        else:
            # Generate JobSet manifest
            manifest, services, base_dir = generate_jobset_from_intent(
                vk8s_jobs, intent_config, project_config, namespace
            )
            manifest_type = "jobset"

        # Write manifests
        os.makedirs(output_path, exist_ok=True)

        if manifest_type == "jobset":
            manifest_file = os.path.join(output_path, "jobset.yaml")
            with open(manifest_file, "w") as f:
                f.write(jobset_to_yaml(manifest))
        elif manifest_type == "pytorchjob":
            manifest_file = os.path.join(output_path, "pytorchjob.yaml")
            with open(manifest_file, "w") as f:
                f.write(kubeflow_to_yaml(manifest))
        elif manifest_type == "inferenceservice":
            manifest_file = os.path.join(output_path, "kservejob.yaml")
            with open(manifest_file, "w") as f:
                f.write(kubeflow_to_yaml(manifest))

        if services:
            services_file = os.path.join(output_path, "services.yaml")
            with open(services_file, "w") as f:
                f.write(services_to_yaml(services))

        # Copy ConfigMap files
        if intent_config.files:
            import shutil

            for file_name in intent_config.files:
                src_path = os.path.join(intent_dir, file_name)
                dst_path = os.path.join(output_path, file_name)
                if os.path.exists(src_path):
                    shutil.copy(src_path, dst_path)

        # Write metadata
        metadata = {
            "job_name": manifest["metadata"]["name"],
            "namespace": namespace,
            "backend": manifest_type,
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "base_dir": base_dir,
            "tasks": [
                {"name": task.name, "replicas": task.replicas or 1}
                for task in intent_config.tasks
            ],
        }
        metadata_file = os.path.join(output_path, "metadata.json")
        with open(metadata_file, "w") as f:
            json.dump(metadata, f, indent=2)

        # Determine ConfigMap name and files
        configmap_name = None
        configmap_files = []
        if intent_config.files:
            # Extract ConfigMap name from the manifest
            if manifest_type == "jobset":
                # Search for configMap volumes in JobSet manifest
                for replicated_job in manifest.get("spec", {}).get(
                    "replicatedJobs", []
                ):
                    job_template = (
                        replicated_job.get("template", {})
                        .get("spec", {})
                        .get("template", {})
                    )
                    volumes = job_template.get("spec", {}).get("volumes", [])
                    for volume in volumes:
                        if "configMap" in volume:
                            configmap_name = volume["configMap"]["name"]
                            break
                    if configmap_name:
                        break
            elif manifest_type == "pytorchjob":
                # Search for configMap volumes in PyTorchJob manifest
                replica_specs = manifest.get("spec", {}).get("pytorchReplicaSpecs", {})
                for replica_type, replica_spec in replica_specs.items():
                    volumes = (
                        replica_spec.get("template", {})
                        .get("spec", {})
                        .get("volumes", [])
                    )
                    for volume in volumes:
                        if "configMap" in volume:
                            configmap_name = volume["configMap"]["name"]
                            break
                    if configmap_name:
                        break

            # If we found a configmap reference, use the files from intent
            if configmap_name:
                configmap_files = list(intent_config.files)

        # Generate bash scripts
        storage_pvc = project_config.get("storage", {}).get(
            "results", f"coldpress-{namespace}-storage"
        )
        # Strip coldpress- prefix from manifest name for scripts (script_gen will add it back)
        job_name_for_scripts = manifest["metadata"]["name"]
        if job_name_for_scripts.startswith("coldpress-"):
            job_name_for_scripts = job_name_for_scripts[len("coldpress-") :]

        write_scripts(
            output_path,
            job_name_for_scripts,
            namespace,
            storage_pvc,
            base_dir,
            configmap_name,
            configmap_files,
            manifest_type,
        )

        click.echo(
            f"\n{backend_name} manifest generated successfully in: {output_path}/"
        )

        # Show manifest file location
        if manifest_type == "jobset":
            click.echo("  Manifest: jobset.yaml")
        elif manifest_type == "pytorchjob":
            click.echo("  Manifest: pytorchjob.yaml")
        elif manifest_type == "tfjob":
            click.echo("  Manifest: tfjob.yaml")
        elif manifest_type == "mpijob":
            click.echo("  Manifest: mpijob.yaml")
        elif manifest_type == "inferenceservice":
            click.echo("  Manifest: kservejob.yaml")

        click.echo("\nTo run the job:")
        click.echo(f"  cd {output_path}")
        click.echo("  ./run.sh")
        click.echo("\nTo monitor:")
        click.echo("  ./monitor.sh")
        click.echo("\nTo explore results:")
        click.echo("  ./explore.sh")
        click.echo("\nTo cleanup:")
        click.echo("  ./cleanup.sh")

        raise SystemExit(0)

    except (ValueError, FileNotFoundError) as e:
        click.echo(f"Error: {e}", err=True)
        raise SystemExit(1)
    except Exception as e:
        click.echo(f"Error generating JobSet: {e}", err=True)
        import traceback

        traceback.print_exc()
        raise SystemExit(1)


if __name__ == "__main__":
    import sys

    sys.exit(cli())
