# Generated by: Claude Sonnet 4.5
"""Coldpress CLI - Generate JobSet manifests and scripts for AI/HPC workloads."""

import click
import yaml
import os
import json
from datetime import datetime, timezone

from .generator import generate_jobset, jobset_to_yaml, services_to_yaml
from .script_gen import write_scripts
from coldpress_common import validate_config, validate_project_config, validate_task_specs
from pydantic import ValidationError

# Default directories (can be overridden with environment variables)
DISCOVERY_DIR = os.getenv("COLDPRESS_DISCOVERY_DIR", "discovery")
PROJECT_DIR = os.getenv("COLDPRESS_PROJECT_DIR", "projects")
OUTPUT_DIR = os.getenv("COLDPRESS_OUTPUT_DIR", "output")


@click.group()
@click.version_option(version="0.2.0")
def cli():
    """Coldpress - AI/HPC workload orchestration for Kubernetes/OpenShift."""
    pass


def _load_and_validate_config(
    config_path, project_override, discovery_override, output_override
):
    """Load and validate configuration from file and CLI args."""
    with open(config_path, "r") as f:
        config_data = yaml.safe_load(f)

    # Validate config schema
    try:
        validated_config = validate_config(config_data)
    except ValidationError as e:
        raise ValueError(f"Config validation failed: {e}") from e

    config_dir = os.path.dirname(os.path.abspath(config_path))
    project = project_override or validated_config.project

    # Handle discovery - CLI override or config (could be string or DiscoveryConfig)
    if discovery_override:
        # CLI override is always a simple string, convert to DiscoveryConfig format
        discovery = {"template": discovery_override, "tasks": "all"}
    elif validated_config.discovery:
        # From config file - already validated as DiscoveryConfig
        if isinstance(validated_config.discovery, str):
            discovery = {"template": validated_config.discovery, "tasks": "all"}
        else:
            discovery = {
                "template": validated_config.discovery.template,
                "tasks": validated_config.discovery.tasks,
            }
    else:
        discovery = None

    output_name = output_override or validated_config.output
    nodes_from_config = validated_config.nodes

    if not project:
        raise ValueError("Must provide --project or specify 'project' in config")

    return config_data, config_dir, project, discovery, output_name, nodes_from_config


def _load_task_specs(config_dir):
    """Load and validate task specifications from job-spec.yaml."""
    job_spec_path = os.path.join(config_dir, "job-spec.yaml")
    if not os.path.exists(job_spec_path):
        raise FileNotFoundError(f"Could not find job-spec.yaml in {config_dir}")

    with open(job_spec_path, "r") as f:
        task_specs_data = list(yaml.safe_load_all(f))

    if not task_specs_data:
        raise ValueError("Job spec file is empty")

    # Validate task specifications
    try:
        validated_tasks = validate_task_specs(task_specs_data)
    except ValidationError as e:
        raise ValueError(f"Task spec validation failed: {e}") from e

    # Convert back to dict for compatibility with rest of code
    return [
        task.model_dump(by_alias=True, exclude_none=True) for task in validated_tasks
    ]


def _determine_job_name(task_specs):
    """Determine job name from task specifications."""
    if len(task_specs) == 1:
        return task_specs[0]["name"]
    return f"{task_specs[0]['name']}-workflow"


def _load_project_config(project_name):
    """Load project configuration file."""
    project_config_file = os.path.join(PROJECT_DIR, f"{project_name}.yaml")
    if not os.path.exists(project_config_file):
        raise FileNotFoundError(f"Project config not found: {project_config_file}")

    with open(project_config_file, "r") as f:
        project_config_data = yaml.safe_load(f)

    # Validate project config
    try:
        validated_project = validate_project_config(project_config_data)
    except ValidationError as e:
        raise ValueError(f"Project config validation failed: {e}") from e

    # Convert back to dict for compatibility
    project_config = validated_project.model_dump(by_alias=True, exclude_none=True)
    namespace = validated_project.namespace

    return project_config, namespace


def _prepare_configmap_files(config_dir, files_list, job_name):
    """Read and prepare files for ConfigMap."""
    if not files_list:
        return None

    configmap_name = f"{job_name}-files"
    file_data = {}
    for file_name in files_list:
        file_path = os.path.join(config_dir, file_name)
        if not os.path.exists(file_path):
            raise FileNotFoundError(f"File not found: {file_path}")
        with open(file_path, "r") as f:
            file_data[file_name] = f.read()

    return {
        "name": configmap_name,
        "files": list(file_data.keys()),
        "data": file_data,
    }


def _allocate_nodes_for_tasks(task_specs, manual_nodes):
    """Allocate nodes for each task."""
    node_assignments = {}

    if manual_nodes:
        # User provided explicit node assignments
        for task_id, node_id in enumerate(manual_nodes):
            if task_id < len(task_specs):
                node_assignments[task_id] = node_id
        return node_assignments

    # Default: let Kubernetes scheduler decide (use "any" coldpress node)
    for task_id in range(len(task_specs)):
        node_assignments[task_id] = "any"

    return node_assignments


def _write_output_files(
    output_dir,
    jobset,
    services,
    job_spec,
    base_dir,
    config_dir,
    task_specs,
    node_assignments,
):
    """Write all generated files to output directory."""
    os.makedirs(output_dir, exist_ok=True)

    # Write JobSet YAML
    jobset_file = os.path.join(output_dir, "jobset.yaml")
    with open(jobset_file, "w") as f:
        f.write(jobset_to_yaml(jobset))

    # Write Services YAML if any
    if services:
        services_file = os.path.join(output_dir, "services.yaml")
        with open(services_file, "w") as f:
            f.write(services_to_yaml(services))

    # Copy ConfigMap files
    configmap_name = None
    configmap_files = []
    if "configmap" in job_spec:
        import shutil

        cm_info = job_spec["configmap"]
        configmap_name = cm_info["name"]
        for file_name in cm_info["files"]:
            src_path = os.path.join(config_dir, file_name)
            dst_path = os.path.join(output_dir, file_name)
            shutil.copy(src_path, dst_path)
            configmap_files.append(file_name)

    # Write metadata
    metadata = {
        "job_name": job_spec["name"],
        "namespace": job_spec["namespace"],
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "base_dir": base_dir,
        "node_assignments": node_assignments,
        "tasks": [
            {"name": t.get("name"), "containers": len(t.get("containers", []))}
            for t in task_specs
        ],
    }
    metadata_file = os.path.join(output_dir, "metadata.json")
    with open(metadata_file, "w") as f:
        json.dump(metadata, f, indent=2)

    # Generate bash scripts
    storage_pvc = job_spec.get("storage", {}).get(
        "results", f"{job_spec['namespace']}-storage"
    )
    write_scripts(
        output_dir,
        job_spec["name"],
        job_spec["namespace"],
        storage_pvc,
        base_dir,
        configmap_name,
        configmap_files,
    )

    return output_dir


@cli.command()
@click.option(
    "-c",
    "--config",
    required=True,
    help="Config file specifying workloads, project, discovery, and output",
    type=click.Path(exists=True),
)
@click.option(
    "-p",
    "--project",
    help="Override project from config (loads from $COLDPRESS_PROJECT_DIR/{project}.yaml)",
    type=str,
)
@click.option(
    "-d",
    "--discovery",
    help="Override discovery from config (loads from discovery/{name}.yaml)",
    type=str,
)
@click.option(
    "-o", "--output", help="Override output directory from config", type=click.Path()
)
@click.option(
    "--node",
    multiple=True,
    type=int,
    help="Manually assign tasks to specific nodes (--node 0 --node 1 ...)",
)
@click.option(
    "--file",
    multiple=True,
    type=str,
    help="Add files to mount into container (--file train.py --file config.json ...)",
)
def generate(config, project, discovery, output, node, file):
    """
    Generate JobSet YAML and bash scripts from config file.

    The config file specifies project, discovery template, and output directory.
    The CLI auto-discovers job-spec.yaml in the same directory as the config file.

    Environment Variables:
        COLDPRESS_DISCOVERY_DIR  - Discovery templates directory (default: discovery)
        COLDPRESS_PROJECT_DIR    - Project configs directory (default: projects)
        COLDPRESS_OUTPUT_DIR     - Default output directory (default: output)

    Examples:
        coldpress generate --config examples/pytorch_ddp_training/config.yaml
        coldpress generate -c examples/vllm_guidellm_benchmark/config.yaml -p different-project
        coldpress generate -c my-workflow/config.yaml -o custom-output
    """
    try:
        config_data, config_dir, project, discovery, output_name, nodes_from_config = (
            _load_and_validate_config(config, project, discovery, output)
        )
        task_specs = _load_task_specs(config_dir)
        job_name = _determine_job_name(task_specs)
        output_path = os.path.join(OUTPUT_DIR, output_name or job_name)

        project_config, namespace = _load_project_config(project)

        # Build job spec
        job_spec = {
            "name": job_name,
            "tasks": task_specs,
            "namespace": namespace,
            "storage": project_config.get("storage", {}),
        }

        # Add discovery configuration
        if discovery:
            template_name = discovery["template"]
            discovery_template_path = f"{DISCOVERY_DIR}/{template_name}.yaml"
            if not os.path.exists(discovery_template_path):
                raise FileNotFoundError(
                    f"Discovery template not found: {discovery_template_path}"
                )
            job_spec["discovery"] = {
                "template": discovery_template_path,
                "tasks": discovery["tasks"],
            }

        # Prepare ConfigMap files
        files_list = list(config_data.get("files", [])) + list(file)
        configmap_info = _prepare_configmap_files(config_dir, files_list, job_name)
        if configmap_info:
            job_spec["configmap"] = configmap_info

        # Display generation info
        click.echo(f"Generating JobSet for: {job_name}")
        click.echo(f"Project: {project}")
        click.echo(f"Namespace: {namespace}")
        if discovery:
            tasks_info = discovery["tasks"]
            if tasks_info == "all":
                click.echo(f"Discovery: {discovery['template']} (all tasks)")
            else:
                click.echo(f"Discovery: {discovery['template']} (tasks: {tasks_info})")
        click.echo(f"Tasks: {len(task_specs)}")

        # Allocate nodes (priority: CLI --node > config nodes > default scheduler)
        manual_nodes = None
        if node:
            # CLI --node flag takes precedence
            manual_nodes = list(node)
            click.echo(f"Using node assignments from CLI: {dict(enumerate(manual_nodes))}")
        elif nodes_from_config:
            # Use nodes from config file
            manual_nodes = nodes_from_config
            click.echo(f"Using node assignments from config: {dict(enumerate(manual_nodes))}")
        else:
            # Default: let Kubernetes scheduler decide
            click.echo("Node scheduling: Kubernetes will select any coldpress-labeled node")

        node_assignments = _allocate_nodes_for_tasks(task_specs, manual_nodes)

        # Display task info
        if not manual_nodes:
            for task_id, task in enumerate(task_specs):
                req_gpus = sum(
                    int(
                        c.get("resources", {})
                        .get("requests", {})
                        .get("nvidia.com/gpu", "0")
                    )
                    for c in task.get("containers", [])
                )
                click.echo(
                    f"  Task {task_id} ({task.get('name', f'task-{task_id}')}) - GPUs: {req_gpus} (scheduler will pick node)"
                )

        # Generate JobSet
        jobset, services, base_dir = generate_jobset(job_spec, node_assignments)

        # Write all output files
        output_path = _write_output_files(
            output_path,
            jobset,
            services,
            job_spec,
            base_dir,
            config_dir,
            task_specs,
            node_assignments,
        )

        click.echo(f"\nJob manifest generated successfully in: {output_path}/")
        click.echo("\nTo run the job:")
        click.echo(f"  cd {output_path}")
        click.echo("  ./run.sh")
        click.echo("\nTo monitor:")
        click.echo("  ./monitor.sh")
        click.echo("\nTo explore results:")
        click.echo("  ./explore.sh")
        click.echo("\nTo cleanup:")
        click.echo("  ./cleanup.sh")

        return 0

    except (ValueError, FileNotFoundError) as e:
        click.echo(f"Error: {e}", err=True)
        return 1
    except Exception as e:
        click.echo(f"Error generating JobSet: {e}", err=True)
        import traceback

        traceback.print_exc()
        return 1


if __name__ == "__main__":
    cli()
