# Generated by: Claude Sonnet 4.5
"""Coldpress CLI - Generate JobSet manifests and scripts for AI/HPC workloads."""

import click
import yaml
import os
import json
from datetime import datetime, timezone

from .allocator import allocate_node
from .generator import generate_jobset, jobset_to_yaml, services_to_yaml
from .script_gen import write_scripts

# Default directories (can be overridden with environment variables)
DISCOVERY_DIR = os.getenv("COLDPRESS_DISCOVERY_DIR", "discovery")
PROJECT_DIR = os.getenv("COLDPRESS_PROJECT_DIR", "projects")
OUTPUT_DIR = os.getenv("COLDPRESS_OUTPUT_DIR", "output")


@click.group()
@click.version_option(version="2.0.0")
def cli():
    """Coldpress - AI/HPC workload orchestration for Kubernetes/OpenShift."""
    pass


@cli.command()
@click.option(
    "-c",
    "--config",
    required=True,
    help="Config file specifying workloads, project, discovery, and output",
    type=click.Path(exists=True),
)
@click.option(
    "-p",
    "--project",
    help="Override project from config (loads from $COLDPRESS_PROJECT_DIR/{project}.yaml)",
    type=str,
)
@click.option(
    "-d",
    "--discovery",
    help="Override discovery from config (loads from discovery/{name}.yaml)",
    type=str,
)
@click.option(
    "-o",
    "--output",
    help="Override output directory from config",
    type=click.Path(),
)
@click.option(
    "--node",
    multiple=True,
    type=int,
    help="Manually assign tasks to specific nodes (--node 0 --node 1 ...)",
)
@click.option(
    "--file",
    multiple=True,
    type=str,
    help="Add files to mount into container (--file train.py --file config.json ...)",
)
def generate(config, project, discovery, output, node, file):
    """
    Generate JobSet YAML and bash scripts from config file.

    The config file specifies project, discovery template, and output directory.
    The CLI auto-discovers job-spec.yaml in the same directory as the config file.

    Environment Variables:
        COLDPRESS_DISCOVERY_DIR  - Discovery templates directory (default: discovery)
        COLDPRESS_PROJECT_DIR    - Project configs directory (default: projects)
        COLDPRESS_OUTPUT_DIR     - Default output directory (default: output)

    Examples:
        coldpress generate --config examples/pytorch_ddp_training/config.yaml
        coldpress generate -c examples/vllm_guidellm_benchmark/config.yaml -p different-project
        coldpress generate -c my-workflow/config.yaml -o custom-output
    """
    # Load config file
    with open(config, "r") as f:
        config_data = yaml.safe_load(f)

    # Get config directory for resolving relative paths
    config_dir = os.path.dirname(os.path.abspath(config))

    # Override with config values (CLI args take precedence)
    project = project or config_data.get("project")
    discovery = discovery or config_data.get("discovery")
    output_name = output or config_data.get(
        "output"
    )  # Get output name from config or CLI
    # Note: output path will be set after job_name is determined

    # Validate required parameters
    if not project:
        click.echo(
            "Error: Must provide --project or specify 'project' in config", err=True
        )
        return 1

    # Auto-discover job-spec.yaml in the same directory as config.yaml
    job_spec_path = os.path.join(config_dir, "job-spec.yaml")
    if not os.path.exists(job_spec_path):
        click.echo(f"Error: Could not find job-spec.yaml in {config_dir}", err=True)
        click.echo(f"Expected: {job_spec_path}", err=True)
        return 1

    # Load job spec(s) - supports multiple YAML documents separated by ---
    with open(job_spec_path, "r") as f:
        task_specs = list(yaml.safe_load_all(f))

    if not task_specs:
        click.echo("Error: Job spec file is empty", err=True)
        return 1

    # Validate all task specs
    for i, task_spec in enumerate(task_specs):
        if not task_spec.get("name"):
            click.echo(f"Error: Task {i} must include 'name'", err=True)
            return 1
        if not task_spec.get("containers"):
            click.echo(
                f"Error: Task {i} ({task_spec.get('name')}) must include 'containers'",
                err=True,
            )
            return 1

    # Use first task's name as job name, or combine if multiple
    if len(task_specs) == 1:
        job_name = task_specs[0]["name"]
    else:
        # Multi-task: use combined name or first task name
        job_name = f"{task_specs[0]['name']}-workflow"

    # Set output directory (always in OUTPUT_DIR subdirectory)
    output = os.path.join(OUTPUT_DIR, output_name or job_name)

    # Build job spec with tasks array (preserves document order)
    job_spec = {"name": job_name, "tasks": task_specs}

    # Load project configuration
    project_config_file = os.path.join(PROJECT_DIR, f"{project}.yaml")
    if not os.path.exists(project_config_file):
        click.echo(f"Error: Project config not found: {project_config_file}", err=True)
        click.echo(f"Create a project config file at: {project_config_file}", err=True)
        return 1

    with open(project_config_file, "r") as f:
        project_config = yaml.safe_load(f)

    # Inject namespace and storage from project config into job spec
    namespace = project_config.get("namespace")
    if not namespace:
        click.echo("Error: Project config must include 'namespace'", err=True)
        return 1

    job_spec["namespace"] = namespace
    job_spec["storage"] = project_config.get("storage", {})

    # Inject discovery template if specified
    if discovery:
        discovery_template_path = f"{DISCOVERY_DIR}/{discovery}.yaml"
        if not os.path.exists(discovery_template_path):
            click.echo(
                f"Error: Discovery template not found: {discovery_template_path}",
                err=True,
            )
            return 1
        job_spec["discovery"] = {"template": discovery_template_path}

    # Handle files for ConfigMap if specified (merge config and CLI)
    files_list = list(config_data.get("files", []))
    if file:
        files_list.extend(file)

    if files_list:
        configmap_name = f"{job_name}-files"
        # Read files from config directory
        file_data = {}
        for file_name in files_list:
            file_path = os.path.join(config_dir, file_name)
            if not os.path.exists(file_path):
                click.echo(f"Error: File not found: {file_path}", err=True)
                return 1
            with open(file_path, "r") as f:
                file_data[file_name] = f.read()

        # Add ConfigMap info to job spec (will be used by generator)
        job_spec["configmap"] = {
            "name": configmap_name,
            "files": list(file_data.keys()),
            "data": file_data,
        }

    click.echo(f"Generating JobSet for: {job_name}")
    click.echo(f"Project: {project}")
    click.echo(f"Namespace: {namespace}")
    if discovery:
        click.echo(f"Discovery: {discovery}")
    click.echo(f"Tasks: {len(task_specs)}")

    # Allocate nodes for each task
    node_assignments = {}
    if node:
        # Manual node assignment
        for task_id, node_id in enumerate(node):
            if task_id < len(task_specs):
                node_assignments[task_id] = node_id
        click.echo(f"Using manual node assignments: {dict(node_assignments)}")
    else:
        # Automatic allocation
        click.echo("Allocating nodes based on cluster state...")
        for task_id, task in enumerate(task_specs):
            # Extract GPU count from container resources (sum across all containers)
            req_gpus = 0
            containers = task.get("containers", [])
            for container in containers:
                gpu_str = (
                    container.get("resources", {})
                    .get("requests", {})
                    .get("nvidia.com/gpu", "0")
                )
                req_gpus += int(gpu_str)

            req_nics = task.get("roce_nics", 0)

            try:
                allocated_node = allocate_node(req_gpus, req_nics)
                node_assignments[task_id] = int(allocated_node)
                click.echo(
                    f"  Task {task_id} ({task.get('name', f'task-{task_id}')}) → Node {allocated_node} (GPUs: {req_gpus})"
                )
            except Exception as e:
                click.echo(f"Error allocating node for task {task_id}: {e}", err=True)
                return 1

    # Generate JobSet
    try:
        jobset, services, base_dir = generate_jobset(job_spec, node_assignments)
    except Exception as e:
        click.echo(f"Error generating JobSet: {e}", err=True)
        import traceback

        traceback.print_exc()
        return 1

    # Create output directory
    os.makedirs(output, exist_ok=True)

    # Write JobSet YAML
    jobset_file = os.path.join(output, "jobset.yaml")
    with open(jobset_file, "w") as f:
        f.write(jobset_to_yaml(jobset))
    click.echo(f"Generated: {jobset_file}")

    # Write Services YAML if any
    if services:
        services_file = os.path.join(output, "services.yaml")
        with open(services_file, "w") as f:
            f.write(services_to_yaml(services))
        click.echo(f"Generated: {services_file}")

    # Copy files to output directory if specified
    configmap_name = None
    configmap_files = []
    if "configmap" in job_spec:
        import shutil

        cm_info = job_spec["configmap"]
        configmap_name = cm_info["name"]

        # Copy files to output directory
        for file_name in cm_info["files"]:
            src_path = os.path.join(config_dir, file_name)
            dst_path = os.path.join(output, file_name)
            shutil.copy(src_path, dst_path)
            configmap_files.append(file_name)
            click.echo(f"Copied: {dst_path}")

    # Write metadata
    metadata = {
        "job_name": job_name,
        "namespace": namespace,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "base_dir": base_dir,
        "node_assignments": node_assignments,
        "tasks": [
            {"name": t.get("name"), "containers": len(t.get("containers", []))}
            for t in task_specs
        ],
    }
    metadata_file = os.path.join(output, "metadata.json")
    with open(metadata_file, "w") as f:
        json.dump(metadata, f, indent=2)
    click.echo(f"Generated: {metadata_file}")

    # Generate bash scripts
    storage_pvc = job_spec.get("storage", {}).get("results", f"{namespace}-storage")
    write_scripts(
        output,
        job_name,
        namespace,
        storage_pvc,
        base_dir,
        configmap_name,
        configmap_files,
    )
    click.echo(f"Generated: {output}/run.sh")
    click.echo(f"Generated: {output}/cleanup.sh")
    click.echo(f"Generated: {output}/monitor.sh")
    click.echo(f"Generated: {output}/logs.sh")
    click.echo(f"Generated: {output}/explore.sh")

    click.echo(f"\nJob manifest generated successfully in: {output}/")
    click.echo("\nTo run the job:")
    click.echo(f"  cd {output}")
    click.echo("  ./run.sh")
    click.echo("\nTo monitor:")
    click.echo("  ./monitor.sh")
    click.echo("\nTo explore results:")
    click.echo("  ./explore.sh")
    click.echo("\nTo cleanup:")
    click.echo("  ./cleanup.sh")

    return 0


if __name__ == "__main__":
    cli()
