# Generated by: Claude Sonnet 4.5
"""Coldpress constants - centralized configuration values."""

# Version
COLDPRESS_VERSION = "0.2.0"

# Resource naming
COLDPRESS_PREFIX = "coldpress"
COLDPRESS_LABEL_MANAGED_BY = "coldpress"

# Images
MKDIR_IMAGE = "registry.access.redhat.com/ubi9/ubi-minimal:latest"

# Labels
COLDPRESS_LABELS = {
    "app.kubernetes.io/managed-by": COLDPRESS_LABEL_MANAGED_BY,
    "app.kubernetes.io/version": COLDPRESS_VERSION,
}


# Kueue
def get_kueue_queue_label(namespace: str) -> str:
    """Get Kueue local queue label for a namespace."""
    return f"{COLDPRESS_PREFIX}-local-queue-{namespace}"


def get_jobset_name(job_id: str) -> str:
    """Get JobSet name from job ID."""
    return f"{COLDPRESS_PREFIX}-{job_id}"


def get_service_name(jobset_name: str, task_id: int) -> str:
    """Get Service name for a task."""
    return f"{COLDPRESS_PREFIX}-s-{jobset_name}-{task_id}"


def get_pvc_name(namespace: str) -> str:
    """Get default PVC name for a namespace."""
    return f"{COLDPRESS_PREFIX}-{namespace}-storage"
