# Generated by: Claude Sonnet 4.5
"""Common generator utilities for Coldpress."""

import hashlib
from datetime import datetime, timezone

# Standard labels for all Coldpress-managed resources
COLDPRESS_LABELS = {
    "app.kubernetes.io/managed-by": "coldpress",
    "app.kubernetes.io/version": "0.2.0",
}


def generate_configmap(name, namespace, file_data):
    """Generate ConfigMap for mounting files into containers.

    Args:
        name: ConfigMap name
        namespace: Kubernetes namespace
        file_data: Dict mapping filename to file content

    Returns:
        dict: ConfigMap manifest
    """
    return {
        "apiVersion": "v1",
        "kind": "ConfigMap",
        "metadata": {
            "name": name,
            "namespace": namespace,
            "labels": COLDPRESS_LABELS.copy(),
        },
        "data": file_data,
    }


def generate_base_dir(namespace, job_name):
    """
    Generate base directory path with uid and timestamp.

    Format: {namespace}/coldpress_results/{job_name}_{uid}_{timestamp}

    Args:
        namespace: Kubernetes namespace
        job_name: Job name

    Returns:
        str: Base directory path
    """
    # Generate 8-char hex uid from timestamp
    now = datetime.now(timezone.utc)
    uid = hashlib.md5(f"{job_name}{now.isoformat()}".encode()).hexdigest()[:8]
    timestamp = now.strftime("%Y%m%d_%H%M%S")

    return f"{namespace}/coldpress_results/{job_name}-{uid}-{timestamp}"


def extract_container_config(task):
    """Extract container configuration from task.

    Args:
        task: Task specification dict

    Returns:
        dict: Container configuration with keys: image, command, args, env,
              working_dir, resources, gpus
    """
    containers = task.get("containers", [])
    if containers:
        container_def = containers[0]
        return {
            "image": container_def.get("image", "alpine:latest"),
            "command": container_def.get("command"),
            "args": container_def.get("args", []),
            "env": container_def.get("env", []),
            "working_dir": container_def.get("workingDir"),
            "resources": container_def.get("resources", {}),
            "ports": container_def.get("ports", []),
            "readinessProbe": container_def.get("readinessProbe"),
            "gpus": int(
                container_def.get("resources", {})
                .get("requests", {})
                .get("nvidia.com/gpu", "0")
            ),
        }

    # Fallback to old flat format
    return {
        "image": task.get("image", "alpine:latest"),
        "command": task.get("command"),
        "args": task.get("args", []),
        "env": task.get("env", []),
        "working_dir": task.get("workingDir"),
        "resources": task.get("resources", {}),
        "ports": [],
        "readinessProbe": None,
        "gpus": task.get("gpus", 0),
    }


def build_volumes_from_task(task, job_spec):
    """Build volume list from task and job spec.

    Args:
        task: Task specification dict
        job_spec: Job specification dict

    Returns:
        list: List of volume dicts for pod spec
    """
    volumes = []

    # Add volumes from task
    task_volumes = task.get("volumes", [])
    for vol in task_volumes:
        vol_name = vol.get("name")
        vol_type = vol.get("type", "pvc")

        if vol_type == "pvc":
            # Use storage config from job_spec
            storage = job_spec.get("storage", {})
            pvc_name = storage.get(
                vol_name, f"coldpress-{job_spec['namespace']}-{vol_name}"
            )
            volumes.append(
                {"name": vol_name, "persistentVolumeClaim": {"claimName": pvc_name}}
            )
        elif vol_type == "emptyDir":
            volumes.append(
                {
                    "name": vol_name,
                    "emptyDir": {
                        "medium": vol.get("medium", ""),
                        "sizeLimit": vol.get("sizeLimit", ""),
                    },
                }
            )

    return volumes


def build_volume_mounts_from_task(task):
    """Build volume mount list from task.

    Args:
        task: Task specification dict

    Returns:
        list: List of volume mount dicts
    """
    volume_mounts = []

    task_volumes = task.get("volumes", [])
    for vol in task_volumes:
        if "mount" in vol:
            volume_mounts.append({"name": vol["name"], "mountPath": vol["mount"]})

    return volume_mounts


def detect_job_type(task):
    """Detect job type from task configuration.

    Args:
        task: Task specification dict

    Returns:
        str: 'training' or 'inference'
    """
    container_config = extract_container_config(task)

    # Check for readinessProbe - typical of inference services
    if container_config.get("readinessProbe"):
        return "inference"

    # Check image for inference patterns
    image = container_config.get("image", "").lower()
    if any(
        pattern in image
        for pattern in ["serving", "inference", "kserve", "torchserve", "triton"]
    ):
        return "inference"

    # Default to training
    return "training"


def detect_framework(task):
    """Detect ML framework from task configuration.

    Args:
        task: Task specification dict

    Returns:
        str: 'pytorch', 'tensorflow', 'mpi', or None
    """
    container_config = extract_container_config(task)
    image = container_config.get("image", "").lower()
    command = container_config.get("command", [])

    # Check image name
    if "pytorch" in image:
        return "pytorch"
    elif "tensorflow" in image or "tf" in image:
        return "tensorflow"

    # Check command
    command_str = " ".join(command) if isinstance(command, list) else str(command)
    if "torch" in command_str.lower():
        return "pytorch"
    elif "tensorflow" in command_str.lower():
        return "tensorflow"
    elif "mpirun" in command_str.lower():
        return "mpi"

    return None
