# Generated by: Claude Sonnet 4.5
"""JobSet YAML generation for Coldpress jobs."""

import os
import yaml
import hashlib
import shlex
from urllib.parse import urlparse
from datetime import datetime, timezone


def generate_configmap(name, namespace, file_data):
    """Generate ConfigMap for mounting files into containers.

    Args:
        name: ConfigMap name
        namespace: Kubernetes namespace
        file_data: Dict mapping filename to file content

    Returns:
        dict: ConfigMap manifest
    """
    return {
        "apiVersion": "v1",
        "kind": "ConfigMap",
        "metadata": {"name": name, "namespace": namespace},
        "data": file_data,
    }


def generate_base_dir(namespace, job_name):
    """
    Generate base directory path with uid and timestamp.

    Format: {namespace}/coldpress_results/{job_name}_{uid}_{timestamp}

    Args:
        namespace: Kubernetes namespace
        job_name: Job name

    Returns:
        str: Base directory path
    """
    # Generate 8-char hex uid from timestamp
    now = datetime.now(timezone.utc)
    uid = hashlib.md5(f"{job_name}{now.isoformat()}".encode()).hexdigest()[:8]
    timestamp = now.strftime("%Y%m%d_%H%M%S")

    return f"{namespace}/coldpress_results/{job_name}-{uid}-{timestamp}"


def generate_jobset(job_spec, node_assignments):
    """
    Generate JobSet YAML from job specification.

    Args:
        job_spec: Job specification dict with name, namespace, tasks, storage
        node_assignments: Dict mapping task index to node ID

    Returns:
        tuple: (JobSet manifest, services list, base_dir)
    """
    job_id = job_spec["name"]
    namespace = job_spec["namespace"]
    tasks = job_spec.get("tasks", [])
    storage = job_spec.get("storage", {})
    discovery_template = (
        job_spec.get("discovery", {}).get("template")
        if "discovery" in job_spec
        else None
    )

    data_pvc_name = storage.get("results", f"{namespace}-storage")
    model_pvc_name = storage.get("models", "coldpress-model-storage")

    # Generate base directory
    base_dir = generate_base_dir(namespace, job_id)

    replicated_jobs = []
    services = []
    previous_job_name = None
    previous_blocking_type = None

    # Add mkdir job as first task (init job)
    mkdir_job = build_mkdir_job(base_dir, data_pvc_name, namespace)
    replicated_jobs.append(mkdir_job)
    previous_job_name = mkdir_job["name"]
    previous_blocking_type = "completion"

    # Add discovery job if template specified
    if discovery_template:
        discovery_job = build_discovery_job(
            discovery_template,
            base_dir,
            data_pvc_name,
            node_assignments.get(0, 0),  # Run on same node as first task
        )
        if discovery_job:
            # Discovery depends on mkdir
            discovery_job["dependsOn"] = [
                {"name": previous_job_name, "status": "Complete"}
            ]
            replicated_jobs.append(discovery_job)
            previous_job_name = discovery_job["name"]
            previous_blocking_type = "completion"

    # Preprocess tasks: infer blocking type from readinessProbe and prepare DNS substitution
    task_names = {task.get("name"): i for i, task in enumerate(tasks)}

    for task_id, task in enumerate(tasks):
        # Infer blocking type from readinessProbe if not explicitly set
        if "blocking" not in task:
            containers = task.get("containers", [])
            if containers and "readinessProbe" in containers[0]:
                task["blocking"] = "endpoint"
                # Extract health_check URL from readinessProbe using full service DNS name
                probe = containers[0]["readinessProbe"]
                if "httpGet" in probe:
                    http_get = probe["httpGet"]
                    path = http_get.get("path", "/")
                    port = http_get.get("port", 80)
                    scheme = http_get.get("scheme", "HTTP").lower()
                    service_name = f"s-{job_id}-{task_id}.{namespace}.svc"
                    task["health_check"] = f"{scheme}://{service_name}:{port}{path}"
            else:
                task["blocking"] = "completion"

        # Substitute DNS placeholders in args (e.g., http://task-name:port → http://s-job-id-task-id.namespace.svc:port)
        containers = task.get("containers", [])
        if containers and "args" in containers[0]:
            args = containers[0]["args"]
            for i, arg in enumerate(args):
                if isinstance(arg, str):
                    # Check if arg contains a URL with task name
                    for task_name, target_task_id in task_names.items():
                        if (
                            f"http://{task_name}:" in arg
                            or f"https://{task_name}:" in arg
                        ):
                            # Substitute with full service DNS name (includes namespace and .svc)
                            service_name = (
                                f"s-{job_id}-{target_task_id}.{namespace}.svc"
                            )
                            arg = arg.replace(f"://{task_name}:", f"://{service_name}:")
                    args[i] = arg

    # Track which task runs on which node for service DNS
    node_task_map = {}
    for i, task in enumerate(tasks):
        node_id = str(node_assignments.get(i, 0))
        if node_id not in node_task_map:
            node_task_map[node_id] = i

    for task_id, task in enumerate(tasks):
        task_name = task.get("name", f"task-{task_id}")
        node_id = str(node_assignments.get(task_id, 0))

        # Build container spec (pass base_dir for result paths)
        container_spec = build_container_spec(
            task, task_id, job_id, namespace, data_pvc_name, model_pvc_name, base_dir
        )

        # Build pod spec
        configmap_info = job_spec.get("configmap")
        pod_spec = build_pod_spec(
            task,
            task_id,
            job_id,
            node_id,
            container_spec,
            data_pvc_name,
            configmap_info,
            base_dir,
        )

        # Create service if needed (for endpoint blocking)
        blocking_type = task.get("blocking", "completion")
        if blocking_type == "endpoint":
            service = create_service(task, task_id, job_id, namespace)
            if service:
                services.append(service)

        # Build replicated job
        replicated_job = {
            "name": f"task-{task_id}",
            "replicas": 1,
            "template": {
                "spec": {
                    "parallelism": 1,
                    "completions": 1,
                    "backoffLimit": 0,
                    "template": pod_spec,
                }
            },
        }

        # Add dependency on previous task
        if previous_job_name:
            dependency_status = (
                "Ready" if previous_blocking_type == "endpoint" else "Complete"
            )
            replicated_job["dependsOn"] = [
                {"name": previous_job_name, "status": dependency_status}
            ]

        replicated_jobs.append(replicated_job)
        previous_job_name = replicated_job["name"]
        previous_blocking_type = blocking_type

    # Determine which jobs are drivers (completion blocking)
    driver_jobs = [
        f"task-{i}"
        for i, task in enumerate(tasks)
        if task.get("blocking", "completion") == "completion"
    ]

    # Build JobSet spec
    jobset_spec = {"suspend": True, "replicatedJobs": replicated_jobs}

    if driver_jobs:
        jobset_spec["successPolicy"] = {
            "operator": "All",
            "targetReplicatedJobs": driver_jobs,
        }

    # Build JobSet manifest
    jobset = {
        "apiVersion": "jobset.x-k8s.io/v1alpha2",
        "kind": "JobSet",
        "metadata": {
            "name": job_id,
            "namespace": namespace,
            "labels": {"kueue.x-k8s.io/queue-name": f"local-queue-{namespace}"},
            "annotations": {
                "coldpress.io/base-dir": base_dir,
                "coldpress.io/storage-pvc": data_pvc_name,
            },
        },
        "spec": jobset_spec,
    }

    return jobset, services, base_dir


def build_container_spec(
    task, task_id, job_id, namespace, data_pvc_name, model_pvc_name, base_dir
):
    """Build container specification from task."""
    # Extract container details from containers array (use first container)
    containers = task.get("containers", [])
    if containers:
        container_def = containers[0]
        image = container_def.get("image", "alpine:latest")
        command = container_def.get("command")
        args = container_def.get("args", [])
        env = container_def.get("env", [])
        working_dir = container_def.get("workingDir")
        # Extract GPU count from resources
        resources = container_def.get("resources", {})
        gpu_str = resources.get("requests", {}).get("nvidia.com/gpu", "0")
        gpus = int(gpu_str)
    else:
        # Fallback to old flat format for backwards compatibility
        image = task.get("image", "alpine:latest")
        command = task.get("command")
        args = task.get("args", [])
        env = task.get("env", [])
        working_dir = task.get("workingDir")
        gpus = task.get("gpus", 0)
        resources = task.get("resources", {})

    # Build resources (merge with GPU count)
    if not resources.get("limits"):
        resources["limits"] = resources.get("requests", {}).copy()
    if not resources.get("requests"):
        resources["requests"] = {}
    # Ensure GPU is set
    if gpus > 0:
        resources["limits"]["nvidia.com/gpu"] = str(gpus)
        resources["requests"]["nvidia.com/gpu"] = str(gpus)

    # Build volume mounts
    volume_mounts = [{"name": "coldpress-data", "mountPath": "/mnt/coldpress-data"}]

    # Add ephemeral mounts if specified
    # Use base_dir for result path
    result_path = task.get("result_path", f"{base_dir}/{task_id}")
    ephemeral_mounts = task.get("ephemeral_mounts", [])

    # Handle both string and list formats for ephemeral_mounts
    if isinstance(ephemeral_mounts, str):
        ephemeral_mounts = [ephemeral_mounts]

    for mount in ephemeral_mounts:
        # Handle both dict format and string format
        if isinstance(mount, dict):
            target = mount.get("target", "/tmp/result")
        else:
            target = mount

        volume_mounts.append(
            {
                "name": "coldpress-data",
                "mountPath": target,
                "subPath": result_path,
            }
        )

    container = {
        "name": "main",
        "image": image,
        "volumeMounts": volume_mounts,
        "resources": {
            "requests": resources.get("requests", {}),
            "limits": resources.get("limits", {}),
        },
    }

    if working_dir:
        container["workingDir"] = working_dir
    if command:
        container["command"] = (
            command if isinstance(command, list) else shlex.split(command)
        )
    if args:
        container["args"] = args if isinstance(args, list) else shlex.split(args)
    if env:
        container["env"] = (
            [{"name": k, "value": str(v)} for k, v in env.items()]
            if isinstance(env, dict)
            else env
        )

    # Add readiness probe for endpoint blocking
    if task.get("blocking") == "endpoint" and task.get("health_check"):
        health_url = task["health_check"]
        parsed = urlparse(health_url)
        container["readinessProbe"] = {
            "httpGet": {
                "path": parsed.path or "/",
                "port": parsed.port or 8000,
                "scheme": (parsed.scheme or "http").upper(),
            },
            "initialDelaySeconds": 30,
            "periodSeconds": 10,
            "failureThreshold": 10,
        }

    return container


def build_pod_spec(
    task,
    task_id,
    job_id,
    node_id,
    container_spec,
    data_pvc_name,
    configmap_info=None,
    base_dir=None,
):
    """Build pod specification."""
    volumes = [
        {
            "name": "coldpress-data",
            "persistentVolumeClaim": {"claimName": data_pvc_name},
        }
    ]

    # Add ConfigMap volume if files are specified
    if configmap_info:
        volumes.append(
            {"name": "configmap-files", "configMap": {"name": configmap_info["name"]}}
        )
        # Mount each file from ConfigMap to working directory
        for file_name in configmap_info.get("files", []):
            container_spec["volumeMounts"].append(
                {
                    "name": "configmap-files",
                    "mountPath": f"/workspace/{file_name}",
                    "subPath": file_name,
                }
            )

    # Add volumes from task.volumes array
    for vol in task.get("volumes", []):
        vol_name = vol.get("name")
        vol_type = vol.get("type", "pvc")  # default to PVC
        mount_path = vol.get("mount")

        if vol_type == "emptyDir":
            # EmptyDir volume (e.g., for /dev/shm)
            volume_def = {"name": vol_name, "emptyDir": {}}
            if vol.get("medium"):
                volume_def["emptyDir"]["medium"] = vol["medium"]
            if vol.get("sizeLimit"):
                volume_def["emptyDir"]["sizeLimit"] = vol["sizeLimit"]
            volumes.append(volume_def)
        elif vol_name == "results":
            # Results volume mounts to coldpress-data PVC (already added)
            # Just add the volumeMount to container
            pass

        # Add volume mount to container if mount path specified
        if mount_path:
            if vol_name == "results":
                # Use existing coldpress-data volume, mount to base_dir
                container_spec["volumeMounts"].append(
                    {
                        "name": "coldpress-data",
                        "mountPath": mount_path,
                        "subPath": base_dir if base_dir else vol.get("subPath", ""),
                    }
                )
            else:
                container_spec["volumeMounts"].append(
                    {"name": vol_name, "mountPath": mount_path}
                )

    # Add host path mounts if specified
    for i, mount in enumerate(task.get("sys_mounts", [])):
        volumes.append(
            {
                "name": f"sys-{i}",
                "hostPath": {"path": mount["source"], "type": "Directory"},
            }
        )
        container_spec["volumeMounts"].append(
            {
                "name": f"sys-{i}",
                "mountPath": mount["target"],
                "readOnly": mount.get("read_only", False),
            }
        )

    pod_spec = {
        "metadata": {
            "labels": {
                "app": f"task-{task_id}",
                "coldpress/gid": job_id,
            },
            "annotations": task.get("annotations", {}),
        },
        "spec": {
            "nodeSelector": {"coldpress.node": node_id},
            "restartPolicy": "Never",
            "volumes": volumes,
            "containers": [container_spec],
        },
    }

    # Add tolerations if specified
    if task.get("tolerate_all"):
        pod_spec["spec"]["tolerations"] = [{"operator": "Exists"}]

    # Add host network if specified
    if task.get("network_mode") == "host":
        pod_spec["spec"]["hostNetwork"] = True

    # Add privileged security context if specified
    if task.get("privileged"):
        container_spec["securityContext"] = {"privileged": True}

    return pod_spec


def create_service(task, task_id, job_id, namespace):
    """Create Kubernetes Service for endpoint blocking."""
    health_check = task.get("health_check")
    if not health_check:
        return None

    try:
        parsed = urlparse(health_check)
        port = parsed.port or 8000

        service = {
            "apiVersion": "v1",
            "kind": "Service",
            "metadata": {
                "name": f"s-{job_id}-{task_id}",
                "namespace": namespace,
                "labels": {"coldpress/gid": job_id},
            },
            "spec": {
                "selector": {
                    "app": f"task-{task_id}",
                    "coldpress/gid": job_id,
                },
                "ports": [{"port": port, "targetPort": port}],
                "type": "ClusterIP",
            },
        }
        return service
    except Exception:
        return None


def build_mkdir_job(base_dir, data_pvc_name, namespace):
    """
    Build mkdir init job to create base directory.

    Args:
        base_dir: Base directory path
        data_pvc_name: PVC name
        namespace: Kubernetes namespace

    Returns:
        dict: ReplicatedJob for mkdir
    """
    return {
        "name": "mkdir",
        "replicas": 1,
        "template": {
            "spec": {
                "parallelism": 1,
                "completions": 1,
                "backoffLimit": 0,
                "template": {
                    "metadata": {"labels": {"app": "mkdir"}},
                    "spec": {
                        "restartPolicy": "Never",
                        "containers": [
                            {
                                "name": "mkdir",
                                "image": "registry.access.redhat.com/ubi9/ubi-minimal:latest",
                                "command": [
                                    "sh",
                                    "-c",
                                    f"mkdir -p /data/{base_dir} && echo Created directory /data/{base_dir}",
                                ],
                                "volumeMounts": [
                                    {"name": "storage", "mountPath": "/data"}
                                ],
                            }
                        ],
                        "volumes": [
                            {
                                "name": "storage",
                                "persistentVolumeClaim": {"claimName": data_pvc_name},
                            }
                        ],
                    },
                },
            }
        },
    }


def build_discovery_job(template_path, base_dir, data_pvc_name, node_id):
    """
    Build discovery job from template.

    Args:
        template_path: Path to discovery template YAML
        base_dir: Base directory path
        data_pvc_name: PVC name
        node_id: Node ID to run on

    Returns:
        dict: ReplicatedJob for discovery, or None if template not found
    """
    try:
        # Read discovery template
        with open(template_path, "r") as f:
            template = yaml.safe_load(f)

        # Extract Pod spec
        pod_spec = template.get("spec", {})
        containers = pod_spec.get("containers", [])

        if not containers:
            return None

        # Get template name from filename
        template_name = (
            os.path.basename(template_path).replace(".yaml", "").replace(".yml", "")
        )

        # Modify container to write to base_dir
        container = containers[0].copy()

        # Update volume mounts to use PVC
        container["volumeMounts"] = [
            {"name": "storage", "mountPath": "/tmp/result", "subPath": base_dir}
        ]

        # Add rename command to output discovery_{template_name}.json
        original_command = (
            container.get("args", [""])[0] if container.get("args") else ""
        )
        rename_cmd = f"\nif [ -f /tmp/result/discovery.json ]; then mv /tmp/result/discovery.json /tmp/result/discovery_{template_name}.json; fi"

        if container.get("args"):
            container["args"] = [original_command + rename_cmd]

        return {
            "name": "discovery",
            "replicas": 1,
            "template": {
                "spec": {
                    "parallelism": 1,
                    "completions": 1,
                    "backoffLimit": 0,
                    "template": {
                        "metadata": {"labels": {"app": "discovery"}},
                        "spec": {
                            "restartPolicy": "Never",
                            "nodeSelector": {"coldpress.node": str(node_id)},
                            "containers": [container],
                            "volumes": [
                                {
                                    "name": "storage",
                                    "persistentVolumeClaim": {
                                        "claimName": data_pvc_name
                                    },
                                }
                            ],
                            "tolerations": [{"operator": "Exists"}],
                        },
                    },
                }
            },
        }
    except Exception as e:
        print(f"Warning: Could not load discovery template {template_path}: {e}")
        return None


def jobset_to_yaml(jobset):
    """Convert JobSet dict to YAML string."""
    return yaml.dump(jobset, default_flow_style=False, sort_keys=False)


def services_to_yaml(services):
    """Convert list of services to YAML string."""
    if not services:
        return ""
    return yaml.dump_all(services, default_flow_style=False, sort_keys=False)
