# Generated by: Claude Sonnet 4.5
"""JobSet YAML generation for Coldpress jobs."""

import os
import sys
import yaml
import shlex
from urllib.parse import urlparse

# Import common utilities
from .generator import (
    COLDPRESS_LABELS,
    generate_base_dir,
    extract_container_config,
)


def _infer_blocking_type_and_health_check(task, task_id, job_id, namespace):
    """Infer blocking type from readinessProbe if not explicitly set."""
    if "blocking" in task:
        return

    containers = task.get("containers", [])
    if containers and "readinessProbe" in containers[0]:
        task["blocking"] = "endpoint"
        probe = containers[0]["readinessProbe"]
        if "httpGet" in probe:
            http_get = probe["httpGet"]
            path = http_get.get("path", "/")
            port = http_get.get("port", 80)
            scheme = http_get.get("scheme", "HTTP").lower()
            service_name = f"coldpress-s-{job_id}-{task_id}.{namespace}.svc"
            task["health_check"] = f"{scheme}://{service_name}:{port}{path}"
    else:
        task["blocking"] = "completion"


def _substitute_dns_in_args(tasks, job_id, namespace):
    """Substitute DNS placeholders in container args."""
    task_names = {task.get("name"): i for i, task in enumerate(tasks)}

    for task in tasks:
        containers = task.get("containers", [])
        if not containers or "args" not in containers[0]:
            continue

        args = containers[0]["args"]
        for i, arg in enumerate(args):
            if not isinstance(arg, str):
                continue

            for task_name, target_task_id in task_names.items():
                if f"http://{task_name}:" in arg or f"https://{task_name}:" in arg:
                    service_name = (
                        f"coldpress-s-{job_id}-{target_task_id}.{namespace}.svc"
                    )
                    arg = arg.replace(f"://{task_name}:", f"://{service_name}:")
            args[i] = arg


def _build_init_jobs(base_dir, data_pvc_name, num_tasks):
    """Build mkdir initialization job."""
    jobs = []

    # Add mkdir job
    mkdir_job = build_mkdir_job(base_dir, data_pvc_name, "", num_tasks)
    jobs.append(mkdir_job)
    previous_job_name = mkdir_job["name"]
    previous_blocking_type = "completion"

    return jobs, previous_job_name, previous_blocking_type


def _build_task_jobs(
    tasks,
    job_id,
    jobset_name,
    namespace,
    job_spec,
    node_assignments,
    data_pvc_name,
    model_pvc_name,
    base_dir,
    previous_job_name,
    previous_blocking_type,
    discovery_template,
    discovery_task_indices,
):
    """Build replicated jobs for all tasks.

    Args:
        job_id: Base job name for DNS (e.g., "ddp-training")
        jobset_name: Full JobSet name with prefix for labels (e.g., "coldpress-ddp-training")
    """
    replicated_jobs = []
    services = []

    for task_id, task in enumerate(tasks):
        node_id = str(node_assignments.get(task_id, 0))

        container_spec = build_container_spec(
            task, task_id, job_id, namespace, data_pvc_name, model_pvc_name, base_dir
        )

        pod_spec = build_pod_spec(
            task,
            task_id,
            job_id,
            jobset_name,
            node_id,
            container_spec,
            data_pvc_name,
            job_spec.get("configmap"),
            base_dir,
        )

        # Add discovery init container if this task should run discovery
        if task_id in discovery_task_indices and discovery_template:
            init_container = build_discovery_init_container(
                discovery_template, task_id, base_dir, data_pvc_name
            )
            if init_container:
                if "initContainers" not in pod_spec["spec"]:
                    pod_spec["spec"]["initContainers"] = []
                pod_spec["spec"]["initContainers"].append(init_container)

        blocking_type = task.get("blocking", "completion")
        if blocking_type == "endpoint":
            service = create_service(task, task_id, job_id, jobset_name, namespace)
            if service:
                services.append(service)

        replicated_job = {
            "name": f"task-{task_id}",
            "replicas": 1,
            "template": {
                "spec": {
                    "parallelism": 1,
                    "completions": 1,
                    "backoffLimit": 0,
                    "template": pod_spec,
                }
            },
        }

        if previous_job_name:
            dependency_status = (
                "Ready" if previous_blocking_type == "endpoint" else "Complete"
            )
            replicated_job["dependsOn"] = [
                {"name": previous_job_name, "status": dependency_status}
            ]

        replicated_jobs.append(replicated_job)
        previous_job_name = replicated_job["name"]
        previous_blocking_type = blocking_type

    return replicated_jobs, services


def generate_jobset(job_spec, node_assignments):
    """
    Generate JobSet YAML from job specification.

    Args:
        job_spec: Job specification dict with name, namespace, tasks, storage
        node_assignments: Dict mapping task index to node ID

    Returns:
        tuple: (JobSet manifest, services list, base_dir)
    """
    job_id = job_spec["name"]
    jobset_name = f"coldpress-{job_id}"
    namespace = job_spec["namespace"]
    tasks = job_spec.get("tasks", [])
    storage = job_spec.get("storage", {})

    # Extract discovery configuration
    discovery_config = job_spec.get("discovery", {})
    discovery_template = discovery_config.get("template")
    discovery_tasks = discovery_config.get("tasks", "all")

    # Determine which task indices should run discovery
    if discovery_template:
        if discovery_tasks == "all":
            discovery_task_indices = set(range(len(tasks)))
        else:
            discovery_task_indices = set(discovery_tasks)
    else:
        discovery_task_indices = set()

    data_pvc_name = storage.get("results", f"coldpress-{namespace}-storage")
    model_pvc_name = storage.get("models", "coldpress-model-storage")
    base_dir = generate_base_dir(namespace, job_id)

    # Preprocess tasks
    for task_id, task in enumerate(tasks):
        _infer_blocking_type_and_health_check(task, task_id, job_id, namespace)
    _substitute_dns_in_args(tasks, job_id, namespace)

    # Build init jobs (just mkdir, discovery now runs as init containers per task)
    init_jobs, previous_job_name, previous_blocking_type = _build_init_jobs(
        base_dir, data_pvc_name, len(tasks)
    )

    # Build task jobs
    task_jobs, services = _build_task_jobs(
        tasks,
        job_id,
        jobset_name,
        namespace,
        job_spec,
        node_assignments,
        data_pvc_name,
        model_pvc_name,
        base_dir,
        previous_job_name,
        previous_blocking_type,
        discovery_template,
        discovery_task_indices,
    )

    replicated_jobs = init_jobs + task_jobs

    # Determine driver jobs
    driver_jobs = [
        f"task-{i}"
        for i, task in enumerate(tasks)
        if task.get("blocking", "completion") == "completion"
    ]

    # Build JobSet spec
    jobset_spec = {"suspend": True, "replicatedJobs": replicated_jobs}
    if driver_jobs:
        jobset_spec["successPolicy"] = {
            "operator": "All",
            "targetReplicatedJobs": driver_jobs,
        }

    # Build JobSet manifest with standard labels
    jobset_labels = COLDPRESS_LABELS.copy()
    jobset_labels.update(
        {
            "kueue.x-k8s.io/queue-name": f"coldpress-local-queue-{namespace}",
            "coldpress.io/job-id": jobset_name,
        }
    )

    jobset = {
        "apiVersion": "jobset.x-k8s.io/v1alpha2",
        "kind": "JobSet",
        "metadata": {
            "name": jobset_name,
            "namespace": namespace,
            "labels": jobset_labels,
            "annotations": {
                "coldpress.io/base-dir": base_dir,
                "coldpress.io/storage-pvc": data_pvc_name,
            },
        },
        "spec": jobset_spec,
    }

    return jobset, services, base_dir


# Use extract_container_config from common generator.py
_extract_container_config = extract_container_config


def _build_container_resources(resources, gpus):
    """Build resource requests and limits."""
    if not resources.get("limits"):
        resources["limits"] = resources.get("requests", {}).copy()
    if not resources.get("requests"):
        resources["requests"] = {}

    if gpus > 0:
        resources["limits"]["nvidia.com/gpu"] = str(gpus)
        resources["requests"]["nvidia.com/gpu"] = str(gpus)

    return {
        "requests": resources.get("requests", {}),
        "limits": resources.get("limits", {}),
    }


def _build_volume_mounts(task, task_id, base_dir):
    """Build volume mounts for container."""
    volume_mounts = [{"name": "coldpress-data", "mountPath": "/mnt/coldpress-data"}]

    result_path = task.get("result_path", f"{base_dir}/{task_id}")
    ephemeral_mounts = task.get("ephemeral_mounts", [])

    if isinstance(ephemeral_mounts, str):
        ephemeral_mounts = [ephemeral_mounts]

    for mount in ephemeral_mounts:
        target = (
            mount.get("target", "/tmp/result") if isinstance(mount, dict) else mount
        )
        volume_mounts.append(
            {
                "name": "coldpress-data",
                "mountPath": target,
                "subPath": result_path,
            }
        )

    return volume_mounts


def _build_readiness_probe(task):
    """Build readiness probe for endpoint blocking."""
    if task.get("blocking") != "endpoint" or not task.get("health_check"):
        return None

    health_url = task["health_check"]
    parsed = urlparse(health_url)
    return {
        "httpGet": {
            "path": parsed.path or "/",
            "port": parsed.port or 8000,
            "scheme": (parsed.scheme or "http").upper(),
        },
        "initialDelaySeconds": 30,
        "periodSeconds": 10,
        "failureThreshold": 10,
    }


def build_container_spec(
    task, task_id, job_id, namespace, data_pvc_name, model_pvc_name, base_dir
):
    """Build container specification from task."""
    config = _extract_container_config(task)

    container = {
        "name": "main",
        "image": config["image"],
        "volumeMounts": _build_volume_mounts(task, task_id, base_dir),
        "resources": _build_container_resources(config["resources"], config["gpus"]),
    }

    if config["working_dir"]:
        container["workingDir"] = config["working_dir"]
    if config["command"]:
        container["command"] = (
            config["command"]
            if isinstance(config["command"], list)
            else shlex.split(config["command"])
        )
    if config["args"]:
        container["args"] = (
            config["args"]
            if isinstance(config["args"], list)
            else shlex.split(config["args"])
        )
    if config["env"]:
        container["env"] = (
            [{"name": k, "value": str(v)} for k, v in config["env"].items()]
            if isinstance(config["env"], dict)
            else config["env"]
        )

    readiness_probe = _build_readiness_probe(task)
    if readiness_probe:
        container["readinessProbe"] = readiness_probe

    return container


def _add_configmap_volume(volumes, container_spec, configmap_info):
    """Add ConfigMap volume and mounts if specified."""
    if not configmap_info:
        return

    volumes.append(
        {"name": "configmap-files", "configMap": {"name": configmap_info["name"]}}
    )
    for file_name in configmap_info.get("files", []):
        container_spec["volumeMounts"].append(
            {
                "name": "configmap-files",
                "mountPath": f"/workspace/{file_name}",
                "subPath": file_name,
            }
        )


def _add_task_volumes(volumes, container_spec, task, task_id, base_dir):
    """Add volumes from task.volumes array."""
    for vol in task.get("volumes", []):
        vol_name = vol.get("name")
        vol_type = vol.get("type", "pvc")
        mount_path = vol.get("mount")

        if vol_type == "emptyDir":
            volume_def = {"name": vol_name, "emptyDir": {}}
            if vol.get("medium"):
                volume_def["emptyDir"]["medium"] = vol["medium"]
            if vol.get("sizeLimit"):
                volume_def["emptyDir"]["sizeLimit"] = vol["sizeLimit"]
            volumes.append(volume_def)

        if mount_path:
            if vol_name == "results":
                # Mount results to task-specific subdirectory
                task_subpath = (
                    f"{base_dir}/task-{task_id}" if base_dir else vol.get("subPath", "")
                )
                container_spec["volumeMounts"].append(
                    {
                        "name": "coldpress-data",
                        "mountPath": mount_path,
                        "subPath": task_subpath,
                    }
                )
            else:
                container_spec["volumeMounts"].append(
                    {"name": vol_name, "mountPath": mount_path}
                )


def _add_sys_mounts(volumes, container_spec, task):
    """Add host path mounts if specified."""
    for i, mount in enumerate(task.get("sys_mounts", [])):
        volumes.append(
            {
                "name": f"sys-{i}",
                "hostPath": {"path": mount["source"], "type": "Directory"},
            }
        )
        container_spec["volumeMounts"].append(
            {
                "name": f"sys-{i}",
                "mountPath": mount["target"],
                "readOnly": mount.get("read_only", False),
            }
        )


def _apply_pod_options(pod_spec, task, container_spec):
    """Apply optional pod settings like tolerations, network mode, and security context."""
    if task.get("tolerate_all"):
        pod_spec["spec"]["tolerations"] = [{"operator": "Exists"}]

    if task.get("network_mode") == "host":
        pod_spec["spec"]["hostNetwork"] = True

    if task.get("privileged"):
        container_spec["securityContext"] = {"privileged": True}


def build_pod_spec(
    task,
    task_id,
    job_id,
    jobset_name,
    node_id,
    container_spec,
    data_pvc_name,
    configmap_info=None,
    base_dir=None,
):
    """Build pod specification.

    Args:
        job_id: Base job name for DNS
        jobset_name: Full JobSet name with prefix for labels
    """
    volumes = [
        {
            "name": "coldpress-data",
            "persistentVolumeClaim": {"claimName": data_pvc_name},
        }
    ]

    _add_configmap_volume(volumes, container_spec, configmap_info)
    _add_task_volumes(volumes, container_spec, task, task_id, base_dir)
    _add_sys_mounts(volumes, container_spec, task)

    pod_spec = {
        "metadata": {
            "labels": {
                "app": f"task-{task_id}",
                "coldpress/gid": jobset_name,
            },
            "annotations": task.get("annotations", {}),
        },
        "spec": {
            "restartPolicy": "Never",
            "volumes": volumes,
            "containers": [container_spec],
        },
    }

    # Add node selection - either specific node or any coldpress node
    if node_id is not None and node_id != "any":
        # Pin to specific node
        pod_spec["spec"]["nodeSelector"] = {"coldpress.node": node_id}
    else:
        # Let Kubernetes scheduler pick any node with coldpress.node label
        pod_spec["spec"]["affinity"] = {
            "nodeAffinity": {
                "requiredDuringSchedulingIgnoredDuringExecution": {
                    "nodeSelectorTerms": [
                        {
                            "matchExpressions": [
                                {
                                    "key": "coldpress.node",
                                    "operator": "Exists",
                                }
                            ]
                        }
                    ]
                }
            }
        }

    _apply_pod_options(pod_spec, task, container_spec)

    return pod_spec


def create_service(task, task_id, job_id, jobset_name, namespace):
    """Create Kubernetes Service for endpoint blocking.

    Args:
        job_id: Base job name for service naming (e.g., "ddp-training")
        jobset_name: Full JobSet name with prefix for labels (e.g., "coldpress-ddp-training")
    """
    health_check = task.get("health_check")
    if not health_check:
        return None

    try:
        parsed = urlparse(health_check)
        port = parsed.port or 8000

        # Merge standard labels with job-specific labels
        service_labels = COLDPRESS_LABELS.copy()
        service_labels.update(
            {
                "coldpress/gid": jobset_name,
                "coldpress.io/job-id": jobset_name,
            }
        )

        service = {
            "apiVersion": "v1",
            "kind": "Service",
            "metadata": {
                "name": f"coldpress-s-{job_id}-{task_id}",
                "namespace": namespace,
                "labels": service_labels,
            },
            "spec": {
                "selector": {
                    "app": f"task-{task_id}",
                    "coldpress/gid": jobset_name,
                },
                "ports": [{"port": port, "targetPort": port}],
                "type": "ClusterIP",
            },
        }
        return service
    except (ValueError, AttributeError, KeyError) as e:
        # URL parsing failed or service configuration is invalid
        sys.stderr.write(f"Warning: Could not create service for task {task_id}: {e}\n")
        return None


def build_discovery_init_container(template_path, task_id, base_dir, data_pvc_name):
    """
    Build discovery init container from template.

    Args:
        template_path: Path to discovery template YAML
        task_id: Task ID for result path
        base_dir: Base directory path
        data_pvc_name: PVC name

    Returns:
        dict: Init container spec, or None if template not found
    """
    try:
        # Read discovery template
        with open(template_path, "r") as f:
            template = yaml.safe_load(f)

        # Extract Pod spec
        pod_spec = template.get("spec", {})
        containers = pod_spec.get("containers", [])

        if not containers:
            return None

        # Get template name from filename
        template_name = (
            os.path.basename(template_path).replace(".yaml", "").replace(".yml", "")
        )

        # Copy container and modify for init container use
        container = containers[0].copy()
        container["name"] = "discovery"

        # Task-specific output path
        task_result_path = f"{base_dir}/task-{task_id}"

        # Update volume mounts to use PVC with task-specific path
        container["volumeMounts"] = [
            {
                "name": "coldpress-data",
                "mountPath": "/tmp/result",
                "subPath": task_result_path,
            }
        ]

        # Add rename command to output discovery_{template_name}.json
        original_command = (
            container.get("args", [""])[0] if container.get("args") else ""
        )
        rename_cmd = f"\nif [ -f /tmp/result/discovery.json ]; then mv /tmp/result/discovery.json /tmp/result/discovery_{template_name}.json; fi"

        if container.get("args"):
            container["args"] = [original_command + rename_cmd]

        return container
    except (FileNotFoundError, yaml.YAMLError, KeyError, IndexError) as e:
        sys.stderr.write(
            f"Warning: Could not load discovery template {template_path}: {e}\n"
        )
        return None


def build_mkdir_job(base_dir, data_pvc_name, namespace, num_tasks):
    """
    Build mkdir init job to create base directory and task subdirectories.

    Args:
        base_dir: Base directory path
        data_pvc_name: PVC name
        namespace: Kubernetes namespace
        num_tasks: Number of tasks (to create task-N directories)

    Returns:
        dict: ReplicatedJob for mkdir
    """
    # Build command to create base dir and all task subdirectories
    task_dirs = " ".join([f"/data/{base_dir}/task-{i}" for i in range(num_tasks)])
    mkdir_cmd = f"mkdir -p /data/{base_dir} {task_dirs} && echo Created directory /data/{base_dir} with {num_tasks} task subdirectories"

    return {
        "name": "mkdir",
        "replicas": 1,
        "template": {
            "spec": {
                "parallelism": 1,
                "completions": 1,
                "backoffLimit": 0,
                "template": {
                    "metadata": {"labels": {"app": "mkdir"}},
                    "spec": {
                        "restartPolicy": "Never",
                        "containers": [
                            {
                                "name": "mkdir",
                                "image": "registry.access.redhat.com/ubi9/ubi-minimal:latest",
                                "command": ["sh", "-c", mkdir_cmd],
                                "volumeMounts": [
                                    {"name": "storage", "mountPath": "/data"}
                                ],
                            }
                        ],
                        "volumes": [
                            {
                                "name": "storage",
                                "persistentVolumeClaim": {"claimName": data_pvc_name},
                            }
                        ],
                    },
                },
            }
        },
    }


def build_discovery_job(template_path, base_dir, data_pvc_name, node_id):
    """
    Build discovery job from template.

    Args:
        template_path: Path to discovery template YAML
        base_dir: Base directory path
        data_pvc_name: PVC name
        node_id: Node ID to run on

    Returns:
        dict: ReplicatedJob for discovery, or None if template not found
    """
    try:
        # Read discovery template
        with open(template_path, "r") as f:
            template = yaml.safe_load(f)

        # Extract Pod spec
        pod_spec = template.get("spec", {})
        containers = pod_spec.get("containers", [])

        if not containers:
            return None

        # Get template name from filename
        template_name = (
            os.path.basename(template_path).replace(".yaml", "").replace(".yml", "")
        )

        # Modify container to write to base_dir
        container = containers[0].copy()

        # Update volume mounts to use PVC
        container["volumeMounts"] = [
            {"name": "storage", "mountPath": "/tmp/result", "subPath": base_dir}
        ]

        # Add rename command to output discovery_{template_name}.json
        original_command = (
            container.get("args", [""])[0] if container.get("args") else ""
        )
        rename_cmd = f"\nif [ -f /tmp/result/discovery.json ]; then mv /tmp/result/discovery.json /tmp/result/discovery_{template_name}.json; fi"

        if container.get("args"):
            container["args"] = [original_command + rename_cmd]

        # Build pod spec with node selection
        pod_spec = {
            "restartPolicy": "Never",
            "containers": [container],
            "volumes": [
                {
                    "name": "storage",
                    "persistentVolumeClaim": {"claimName": data_pvc_name},
                }
            ],
            "tolerations": [{"operator": "Exists"}],
        }

        # Add node selection - either specific node or any coldpress node
        if node_id is not None and node_id != "any":
            # Pin to specific node
            pod_spec["nodeSelector"] = {"coldpress.node": str(node_id)}
        else:
            # Let Kubernetes scheduler pick any node with coldpress.node label
            pod_spec["affinity"] = {
                "nodeAffinity": {
                    "requiredDuringSchedulingIgnoredDuringExecution": {
                        "nodeSelectorTerms": [
                            {
                                "matchExpressions": [
                                    {
                                        "key": "coldpress.node",
                                        "operator": "Exists",
                                    }
                                ]
                            }
                        ]
                    }
                }
            }

        return {
            "name": "discovery",
            "replicas": 1,
            "template": {
                "spec": {
                    "parallelism": 1,
                    "completions": 1,
                    "backoffLimit": 0,
                    "template": {
                        "metadata": {"labels": {"app": "discovery"}},
                        "spec": pod_spec,
                    },
                }
            },
        }
    except (FileNotFoundError, yaml.YAMLError, KeyError, IndexError) as e:
        sys.stderr.write(
            f"Warning: Could not load discovery template {template_path}: {e}\n"
        )
        return None


def jobset_to_yaml(jobset):
    """Convert JobSet dict to YAML string."""
    return yaml.dump(jobset, default_flow_style=False, sort_keys=False)


def services_to_yaml(services):
    """Convert list of services to YAML string."""
    if not services:
        return ""
    return yaml.dump_all(services, default_flow_style=False, sort_keys=False)
