# Generated by: Claude Sonnet 4.5
"""KubeRay manifest generation for Coldpress jobs.

Transforms single-node Ray Train jobs into distributed RayJob manifests.
"""

import copy
import yaml
from datetime import datetime, timezone
from .constants import (
    COLDPRESS_LABELS,
    MKDIR_IMAGE,
    get_kueue_queue_label,
)
from .utils import (
    apply_arg_overrides,
    apply_env_overrides,
    build_discovery_init_container,
    parse_discovery_config,
    get_storage_pvc_name,
    DANGEROUS_SHELL_CHARS,
)


def generate_rayjob_from_intent(
    vk8s_jobs: dict, intent_config, project_config, namespace: str
):
    """
    Generate RayJob manifest from vanilla k8s Job + intent.

    Takes a single-node Ray Train job and transforms it into a distributed RayJob.

    Note: For RayJob, the entrypoint runs via ray job submit which doesn't have
    access to container mounts (ConfigMaps). Files must be in shared storage or
    included in runtime environment.

    Args:
        vk8s_jobs: Dict mapping job name to vanilla k8s Job manifest
        intent_config: Validated IntentConfig object
        project_config: Project configuration dict
        namespace: Target namespace

    Returns:
        tuple: (RayJob manifest, base_dir)
    """
    # Only support single task for KubeRay
    if len(intent_config.tasks) != 1:
        raise ValueError("KubeRay generation currently only supports single task")

    task_intent = intent_config.tasks[0]
    task_name = task_intent.name

    if task_name not in vk8s_jobs:
        raise ValueError(f"Task '{task_name}' not found in job-spec.yaml")

    vk8s_job = vk8s_jobs[task_name]

    # Determine job name
    job_id = task_name
    rayjob_name = f"coldpress-{job_id}"
    data_pvc_name = get_storage_pvc_name(project_config, namespace)

    # Generate base directory for results
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    short_hash = abs(hash(rayjob_name + timestamp)) % 100000000
    base_dir = f"{namespace}/coldpress_results/{job_id}-{short_hash:08x}-{timestamp}"

    # Extract discovery configuration
    discovery_template_path, discovery_task_names = parse_discovery_config(
        intent_config
    )

    # Extract vk8s Job spec (single-node pod template)
    vk8s_spec = vk8s_job.get("spec", {}).get("template", {}).get("spec", {})
    containers = vk8s_spec.get("containers", [])

    if not containers:
        raise ValueError(
            f"Job {vk8s_job.get('metadata', {}).get('name')} has no containers"
        )

    base_container = copy.deepcopy(containers[0])

    # Get replicas (number of Ray pods to create)
    replicas = task_intent.replicas or 1
    if replicas < 1:
        raise ValueError(f"replicas must be >= 1, got {replicas}")

    # Build macros for RayJob
    macros = {
        "REPLICAS": str(replicas),
        "TASK_NAME": task_name,
    }

    # Build head group spec (rank 0)
    head_container = copy.deepcopy(base_container)
    head_container["name"] = "ray-head"

    # For RayJob, we need to extract and process command/args before removing them
    original_command = copy.deepcopy(head_container.get("command", []))
    original_args = copy.deepcopy(head_container.get("args", []))

    # Apply arg replacements using shared utility
    apply_arg_overrides(head_container, task_intent, macros)

    # Update original_command/original_args for entrypoint generation after overrides
    original_command = copy.deepcopy(head_container.get("command", []))
    original_args = copy.deepcopy(head_container.get("args", []))

    # Substitute /results/output paths to point within coldpress base directory
    # This ensures training outputs are saved in the coldpress workspace
    output_path_substitutions = {
        "/results/output": f"/results/{base_dir}/output",
        "/results/checkpoints": f"/results/{base_dir}/output",
    }

    def substitute_output_paths(args_list):
        """Replace output paths in arguments with coldpress base directory paths"""
        if not args_list:
            return args_list
        substituted = []
        for arg in args_list:
            new_arg = arg
            for old_path, new_path in output_path_substitutions.items():
                if old_path in arg:
                    new_arg = arg.replace(old_path, new_path)
            substituted.append(new_arg)
        return substituted

    original_args = substitute_output_paths(original_args)
    original_command = substitute_output_paths(original_command)

    if "command" in head_container:
        del head_container["command"]
    if "args" in head_container:
        del head_container["args"]

    # Apply env var additions/replacements using shared utility
    head_macros = macros.copy()
    head_macros["INDEX"] = "0"
    head_macros["RANK"] = "0"
    apply_env_overrides(head_container, task_intent, head_macros)

    # Build head pod spec
    head_pod_spec = {
        "containers": [head_container],
    }

    # Copy tolerations
    if vk8s_spec.get("tolerations"):
        head_pod_spec["tolerations"] = vk8s_spec["tolerations"]

    # Copy volumes and add coldpress- prefix to configMap names
    if vk8s_spec.get("volumes"):
        head_pod_spec["volumes"] = copy.deepcopy(vk8s_spec["volumes"])
        for volume in head_pod_spec["volumes"]:
            if "configMap" in volume:
                cm_name = volume["configMap"]["name"]
                if not cm_name.startswith("coldpress-"):
                    volume["configMap"]["name"] = f"coldpress-{cm_name}"

    # Add storage PVC if not already present
    if not any(v.get("name") == "results" for v in head_pod_spec.get("volumes", [])):
        if "volumes" not in head_pod_spec:
            head_pod_spec["volumes"] = []
        head_pod_spec["volumes"].insert(
            0,
            {"name": "results", "persistentVolumeClaim": {"claimName": data_pvc_name}},
        )

    # Build init containers for head
    init_containers = []

    # Validate base_dir contains no shell metacharacters (defense in depth)
    for char in DANGEROUS_SHELL_CHARS:
        if char in base_dir:
            raise ValueError(
                f"Invalid character '{char}' in base_dir '{base_dir}'. "
                f"This could be a security risk."
            )

    # SAFETY: base_dir validated above, replicas is int - safe for shell command
    # Add mkdir init container - create directories for head and all workers
    # Also create workspace and output directories for training files and results
    mkdir_dirs = (
        f"/results/{base_dir} /results/{base_dir}/workspace /results/{base_dir}/output"
    )
    for worker_idx in range(1, replicas):
        mkdir_dirs += f" /results/{base_dir}/worker-{worker_idx}"

    mkdir_init = {
        "name": "mkdir",
        "image": MKDIR_IMAGE,
        "command": ["sh", "-c"],
        "args": [
            f"mkdir -p {mkdir_dirs} && echo Created directories for head and {replicas - 1} workers"
        ],
        "volumeMounts": [{"name": "results", "mountPath": "/results"}],
    }
    init_containers.append(mkdir_init)

    # SAFETY: base_dir validated above - safe for shell command
    # Add init container to copy training files to shared storage
    # This makes them accessible to Ray job submission
    # Use -L to dereference symlinks (ConfigMaps create symlinks)
    copy_files_init = {
        "name": "copy-files",
        "image": base_container["image"],
        "command": ["sh", "-c"],
        "args": [
            f"cp -rL /workspace/* /results/{base_dir}/workspace/ && echo Copied training files to shared storage"
        ],
        "volumeMounts": [
            {"name": "results", "mountPath": "/results"},
            {"name": "training-script", "mountPath": "/workspace"},
        ],
    }
    init_containers.append(copy_files_init)

    # Add discovery init container if specified
    should_run_discovery = discovery_template_path and task_name in discovery_task_names

    if should_run_discovery:
        # Find storage volume name
        storage_volume_name = None
        for volume in head_pod_spec.get("volumes", []):
            if "persistentVolumeClaim" in volume:
                pvc_claim = volume["persistentVolumeClaim"].get("claimName")
                if pvc_claim == data_pvc_name:
                    storage_volume_name = volume.get("name")
                    break

        if storage_volume_name:
            discovery_init = build_discovery_init_container(
                discovery_template_path, base_dir, storage_volume_name
            )
            if discovery_init:
                init_containers.append(discovery_init)

    head_pod_spec["initContainers"] = init_containers

    # Build head group spec
    head_group_spec = {
        "serviceType": "ClusterIP",
        "rayStartParams": {
            "dashboard-host": "0.0.0.0",
        },
        "template": {
            "metadata": {
                "annotations": {"sidecar.istio.io/inject": "false"},
                "labels": COLDPRESS_LABELS.copy(),
            },
            "spec": head_pod_spec,
        },
    }
    head_group_spec["template"]["metadata"]["labels"]["coldpress.io/job-id"] = (
        rayjob_name
    )

    # Build worker group specs if replicas > 1
    worker_group_specs = []

    if replicas > 1:
        # For each worker, create a separate worker group with 1 replica
        for worker_idx in range(1, replicas):
            worker_container = copy.deepcopy(base_container)
            worker_container["name"] = "ray-worker"

            # Apply arg replacements using shared utility
            worker_macros = macros.copy()
            worker_macros["INDEX"] = str(worker_idx)
            apply_arg_overrides(worker_container, task_intent, worker_macros)

            # For RayJob, remove command/args - Ray operator controls container startup
            if "command" in worker_container:
                del worker_container["command"]
            if "args" in worker_container:
                del worker_container["args"]

            # Apply env var additions/replacements using shared utility
            worker_macros = macros.copy()
            worker_macros["INDEX"] = str(worker_idx)
            worker_macros["RANK"] = str(worker_idx)
            apply_env_overrides(worker_container, task_intent, worker_macros)

            # Build worker pod spec
            worker_pod_spec = {
                "containers": [worker_container],
            }

            # Add discovery init container for worker if specified
            should_run_discovery_worker = (
                discovery_template_path and task_name in discovery_task_names
            )

            worker_init_containers = []

            if should_run_discovery_worker:
                # Find storage volume name
                storage_volume_name_worker = None
                if vk8s_spec.get("volumes"):
                    for volume in vk8s_spec["volumes"]:
                        if "persistentVolumeClaim" in volume:
                            pvc_claim = volume["persistentVolumeClaim"].get("claimName")
                            if pvc_claim == data_pvc_name:
                                storage_volume_name_worker = volume.get("name")
                                break

                if storage_volume_name_worker:
                    # Create worker-specific discovery subdirectory
                    worker_base_dir = f"{base_dir}/worker-{worker_idx}"
                    discovery_init_worker = build_discovery_init_container(
                        discovery_template_path,
                        worker_base_dir,
                        storage_volume_name_worker,
                    )
                    if discovery_init_worker:
                        worker_init_containers.append(discovery_init_worker)

            if worker_init_containers:
                worker_pod_spec["initContainers"] = worker_init_containers

            # Copy tolerations
            if vk8s_spec.get("tolerations"):
                worker_pod_spec["tolerations"] = vk8s_spec["tolerations"]

            # Copy volumes
            if vk8s_spec.get("volumes"):
                worker_pod_spec["volumes"] = copy.deepcopy(vk8s_spec["volumes"])
                # Add coldpress- prefix to configMap volume names
                for volume in worker_pod_spec["volumes"]:
                    if "configMap" in volume:
                        cm_name = volume["configMap"]["name"]
                        if not cm_name.startswith("coldpress-"):
                            volume["configMap"]["name"] = f"coldpress-{cm_name}"

            # Add storage PVC if not already present
            if not any(
                v.get("name") == "results" for v in worker_pod_spec.get("volumes", [])
            ):
                if "volumes" not in worker_pod_spec:
                    worker_pod_spec["volumes"] = []
                worker_pod_spec["volumes"].insert(
                    0,
                    {
                        "name": "results",
                        "persistentVolumeClaim": {"claimName": data_pvc_name},
                    },
                )

            worker_group_spec = {
                "groupName": f"worker-group-{worker_idx}",
                "replicas": 1,
                "minReplicas": 1,
                "maxReplicas": 1,
                "rayStartParams": {},
                "template": {
                    "metadata": {
                        "annotations": {"sidecar.istio.io/inject": "false"},
                        "labels": COLDPRESS_LABELS.copy(),
                    },
                    "spec": worker_pod_spec,
                },
            }
            worker_group_spec["template"]["metadata"]["labels"][
                "coldpress.io/job-id"
            ] = rayjob_name

            worker_group_specs.append(worker_group_spec)

    # Build RayCluster spec
    ray_cluster_spec = {
        "headGroupSpec": head_group_spec,
    }

    if worker_group_specs:
        ray_cluster_spec["workerGroupSpecs"] = worker_group_specs

    # Build RayJob labels
    rayjob_labels = COLDPRESS_LABELS.copy()
    rayjob_labels.update(
        {
            "coldpress.io/job-id": rayjob_name,
            "kueue.x-k8s.io/queue-name": get_kueue_queue_label(namespace),
        }
    )

    # Build entrypoint from original command/args
    # For RayJob, use shared storage location where files were copied
    shared_workspace = f"/results/{base_dir}/workspace"

    # Build env var substitution map for entrypoint script
    # RayJob entrypoint runs before Ray connection, so runtimeEnv vars aren't available
    # We need to substitute the values directly into the bash script
    # Use all env vars from head container (includes both job-spec defaults and intent overrides)
    env_substitutions = {}
    env_list = head_container.get("env", [])
    for env_item in env_list:
        env_key = env_item.get("name")
        env_value = env_item.get("value", "")
        if env_key:
            env_substitutions[f"${env_key}"] = str(env_value)

    entrypoint_cmd = ""

    if original_command == ["python"]:
        # Common pattern: command: ["python"], args: ["script.py", "--arg1", ...]
        if original_args:
            entrypoint_cmd = "python " + " ".join(original_args)
    elif original_command in [["bash", "-c"], ["sh", "-c"]]:
        # Shell pattern: command: ["bash", "-c"], args: ["script"]
        # Need to preserve bash -c wrapper for RayJob entrypoint
        # Prepend cd to shared workspace directory
        # Also substitute env var references with actual values
        if original_args:
            shell = "bash" if original_command == ["bash", "-c"] else "sh"
            script = original_args[0]

            # Substitute env var references in the script
            for var_ref, value in env_substitutions.items():
                script = script.replace(var_ref, value)

            script_with_cd = f"cd {shared_workspace} && {script}"
            entrypoint_cmd = f"{shell} -c '{script_with_cd}'"
    else:
        # General case: combine command + args
        if original_command:
            entrypoint_cmd = " ".join(original_command)
        if original_args:
            args_str = " ".join(original_args)
            if entrypoint_cmd:
                entrypoint_cmd = f"{entrypoint_cmd} {args_str}"
            else:
                entrypoint_cmd = args_str

    # Prepend cd to shared workspace directory for non-shell commands
    # Wrap in bash -c since RayJob entrypoint doesn't support shell operators
    if original_command not in [["bash", "-c"], ["sh", "-c"]]:
        entrypoint_cmd = f"cd {shared_workspace} && {entrypoint_cmd}"
        entrypoint_cmd = f"bash -c '{entrypoint_cmd}'"

    # Build runtime env with all env vars from head container
    # (includes both job-spec defaults and intent overrides)
    runtime_env = {}
    env_list = head_container.get("env", [])
    if env_list:
        env_vars = {}
        for env_item in env_list:
            env_key = env_item.get("name")
            env_value = env_item.get("value", "")
            if env_key:
                env_vars[env_key] = str(env_value)

        if env_vars:
            runtime_env["env_vars"] = env_vars

    # Build RayJob manifest
    rayjob = {
        "apiVersion": "ray.io/v1",
        "kind": "RayJob",
        "metadata": {
            "name": rayjob_name,
            "namespace": namespace,
            "labels": rayjob_labels,
            "annotations": {
                "coldpress.io/base-dir": base_dir,
                "coldpress.io/storage-pvc": data_pvc_name,
            },
        },
        "spec": {
            "suspend": True,  # Start suspended for Kueue
            "entrypoint": entrypoint_cmd,
            "rayClusterSpec": ray_cluster_spec,
            "shutdownAfterJobFinishes": True,
            "ttlSecondsAfterFinished": 3600,  # Clean up after 1 hour
        },
    }

    # Add runtime env if we have env vars to pass
    if runtime_env:
        rayjob["spec"]["runtimeEnvYAML"] = yaml.safe_dump(runtime_env)

    return rayjob, base_dir


def kuberay_to_yaml(manifest):
    """Convert KubeRay manifest dict to YAML string.

    Args:
        manifest: KubeRay manifest dict

    Returns:
        str: YAML string
    """
    return yaml.safe_dump(manifest, default_flow_style=False, sort_keys=False)
