# Generated by: Claude Sonnet 4.5
"""Bash script generation for Coldpress jobs."""

from datetime import datetime


def generate_run_script(
    job_name,
    namespace,
    timeout="1h",
    configmap_name=None,
    configmap_files=None,
    manifest_type="jobset",
):
    """
    Generate run.sh script to apply and monitor the job.

    Args:
        job_name: Name of the job
        namespace: Kubernetes namespace
        timeout: Timeout for job completion (default: 1h)
        configmap_name: Optional ConfigMap name
        configmap_files: Optional list of files to include in ConfigMap
        manifest_type: Type of manifest (jobset, pytorchjob, tfjob, mpijob, inferenceservice)

    Returns:
        str: Bash script content
    """
    configmap_apply = ""
    if configmap_name and configmap_files:
        from_files = " ".join([f"--from-file={f}" for f in configmap_files])
        # Add coldpress- prefix if not already present
        if not configmap_name.startswith("coldpress-"):
            actual_configmap_name = f"coldpress-{configmap_name}"
        else:
            actual_configmap_name = configmap_name
        configmap_apply = f"""
# Create ConfigMap from files
echo "Creating ConfigMap from files..."
oc create configmap {actual_configmap_name} -n {namespace} {from_files} --dry-run=client -o yaml | oc apply -f -
"""

    # Generate manifest-specific commands
    if manifest_type == "jobset":
        manifest_file = "jobset.yaml"
        resource_type = "jobset"
        resource_name = f"coldpress-{job_name}"
        apply_cmd = 'echo "Applying JobSet..."\noc apply -f jobset.yaml'
        services_apply = """
# Apply services if they exist
if [ -f services.yaml ]; then
    echo "Applying Services..."
    oc apply -f services.yaml
fi"""
    elif manifest_type == "pytorchjob":
        manifest_file = "pytorchjob.yaml"
        resource_type = "pytorchjob"
        resource_name = f"coldpress-{job_name}"
        apply_cmd = 'echo "Applying PyTorchJob..."\noc apply -f pytorchjob.yaml'
        services_apply = ""
    elif manifest_type == "tfjob":
        manifest_file = "tfjob.yaml"
        resource_type = "tfjob"
        resource_name = f"coldpress-{job_name}"
        apply_cmd = 'echo "Applying TFJob..."\noc apply -f tfjob.yaml'
        services_apply = ""
    elif manifest_type == "mpijob":
        manifest_file = "mpijob.yaml"
        resource_type = "mpijob"
        resource_name = f"coldpress-{job_name}"
        apply_cmd = 'echo "Applying MPIJob..."\noc apply -f mpijob.yaml'
        services_apply = ""
    elif manifest_type == "inferenceservice":
        manifest_file = "kservejob.yaml"
        resource_type = "inferenceservice"
        resource_name = f"coldpress-{job_name}"
        apply_cmd = (
            'echo "Applying KServe InferenceService..."\noc apply -f kservejob.yaml'
        )
        services_apply = ""
    else:
        manifest_file = "manifest.yaml"
        resource_type = manifest_type
        resource_name = f"coldpress-{job_name}"
        apply_cmd = f'echo "Applying {manifest_type}..."\noc apply -f {manifest_file}'
        services_apply = ""

    # Determine wait condition based on resource type
    if manifest_type == "inferenceservice":
        wait_message = (
            f"Waiting for InferenceService to be ready (timeout: {timeout})..."
        )
        wait_cmd = f"oc wait --for=condition=Ready $RESOURCE_TYPE/$JOB_NAME -n $NAMESPACE --timeout={timeout} 2>/dev/null"
        pod_selector = f"serving.kserve.io/inferenceservice={job_name}"
    else:
        wait_message = f"Waiting for job to complete (timeout: {timeout})..."
        wait_cmd = f"oc wait --for=condition=complete $RESOURCE_TYPE/$JOB_NAME -n $NAMESPACE --timeout={timeout} 2>/dev/null"
        pod_selector = f"coldpress.io/job-id={job_name}"

    script = f'''#!/bin/bash
# Generated by coldpress on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

set -e

# Change to script directory to handle relative paths
cd "$(dirname "$0")"

NAMESPACE="{namespace}"
JOB_NAME="{resource_name}"
RESOURCE_TYPE="{resource_type}"
{configmap_apply}
{apply_cmd}
{services_apply}

echo "{wait_message}"
{wait_cmd} || {{
    echo "Job may still be running or condition not supported for $RESOURCE_TYPE"
    echo "Current status:"
    oc get $RESOURCE_TYPE/$JOB_NAME -n $NAMESPACE
    oc get pods -n $NAMESPACE -l training.kubeflow.org/job-name=$JOB_NAME 2>/dev/null || \
    oc get pods -n $NAMESPACE -l {pod_selector} 2>/dev/null || \
    oc get pods -n $NAMESPACE | grep {job_name}
}}

echo "Job applied successfully!"
echo ""
echo "To monitor: ./monitor.sh"
echo "To check logs: ./logs.sh"
echo "To cleanup: ./cleanup.sh"
'''
    return script


def generate_cleanup_script(
    job_name, namespace, configmap_name=None, manifest_type="jobset"
):
    """
    Generate cleanup.sh script to delete job resources.

    Args:
        job_name: Name of the job (without coldpress- prefix)
        namespace: Kubernetes namespace
        configmap_name: Optional ConfigMap name to delete
        manifest_type: Type of manifest (jobset, pytorchjob, tfjob, mpijob, inferenceservice)

    Returns:
        str: Bash script content
    """
    configmap_delete = ""
    if configmap_name:
        # Add coldpress- prefix if not already present
        if not configmap_name.startswith("coldpress-"):
            actual_configmap_name = f"coldpress-{configmap_name}"
        else:
            actual_configmap_name = configmap_name
        configmap_delete = f"""
# Delete ConfigMap
echo "Deleting ConfigMap..."
oc delete configmap/{actual_configmap_name} -n $NAMESPACE --ignore-not-found=true
"""

    # Generate manifest-specific commands
    if manifest_type == "jobset":
        resource_type = "jobset"
        resource_name = f"coldpress-{job_name}"
        delete_cmd = f"oc delete {resource_type}/{resource_name} -n $NAMESPACE --ignore-not-found=true"
        services_delete = f"oc delete services -n $NAMESPACE -l coldpress/gid={resource_name} --ignore-not-found=true"
    elif manifest_type in ["pytorchjob", "tfjob", "mpijob"]:
        resource_name = f"coldpress-{job_name}"
        delete_cmd = f"oc delete {manifest_type}/{resource_name} -n $NAMESPACE --ignore-not-found=true"
        services_delete = ""  # Kubeflow jobs don't create separate services
    elif manifest_type == "inferenceservice":
        resource_name = f"coldpress-{job_name}"
        delete_cmd = f"oc delete {manifest_type}/{resource_name} -n $NAMESPACE --ignore-not-found=true"
        services_delete = ""
    else:
        resource_name = f"coldpress-{job_name}"
        delete_cmd = f"oc delete {manifest_type}/{resource_name} -n $NAMESPACE --ignore-not-found=true"
        services_delete = ""

    services_section = (
        f"""
# Delete Services
echo "Deleting Services..."
{services_delete}
"""
        if services_delete
        else ""
    )

    script = f'''#!/bin/bash
# Generated by coldpress on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

set -e

# Change to script directory to handle relative paths
cd "$(dirname "$0")"

NAMESPACE="{namespace}"
JOB_NAME="{resource_name}"
RESOURCE_TYPE="{manifest_type}"

echo "Cleaning up resources for job: $JOB_NAME"

# Delete main resource (this cascades to Jobs and Pods)
echo "Deleting $RESOURCE_TYPE..."
{delete_cmd}
{services_section}{configmap_delete}

# Delete helper pods (log-saver, coldpress-explorer)
echo "Deleting helper pods..."
oc delete pods -n $NAMESPACE -l app=coldpress-explorer,coldpress.io/job-id=$JOB_NAME --ignore-not-found=true 2>/dev/null || true
oc get pods -n $NAMESPACE --no-headers 2>/dev/null | grep -E "log-saver-${{JOB_NAME}}-|coldpress-explorer-${{JOB_NAME}}-|coldpress-copier-${{JOB_NAME}}-" | awk '{{print $1}}' | xargs -r oc delete pod -n $NAMESPACE --ignore-not-found=true 2>/dev/null || true

echo "Cleanup complete!"
'''
    return script


def generate_monitor_script(job_name, namespace, manifest_type="jobset"):
    """
    Generate monitor.sh script to watch job progress.

    Args:
        job_name: Name of the job
        namespace: Kubernetes namespace
        manifest_type: Type of manifest (jobset, pytorchjob, etc.)

    Returns:
        str: Bash script content
    """
    # Generate manifest-specific commands
    if manifest_type == "jobset":
        resource_type = "jobset"
        resource_name = f"coldpress-{job_name}"
        label_selector = f"coldpress.io/job-id={resource_name}"
    elif manifest_type == "pytorchjob":
        resource_type = "pytorchjob"
        resource_name = f"coldpress-{job_name}"
        label_selector = f"training.kubeflow.org/job-name={resource_name}"
    elif manifest_type == "tfjob":
        resource_type = "tfjob"
        resource_name = f"coldpress-{job_name}"
        label_selector = f"training.kubeflow.org/job-name={resource_name}"
    elif manifest_type == "mpijob":
        resource_type = "mpijob"
        resource_name = f"coldpress-{job_name}"
        label_selector = f"training.kubeflow.org/job-name={resource_name}"
    elif manifest_type == "inferenceservice":
        resource_type = "inferenceservice"
        resource_name = f"coldpress-{job_name}"
        label_selector = f"serving.kserve.io/inferenceservice={resource_name}"
    else:
        resource_type = manifest_type
        resource_name = f"coldpress-{job_name}"
        label_selector = f"coldpress.io/job-id={resource_name}"

    script = f'''#!/bin/bash
# Generated by coldpress on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

NAMESPACE="{namespace}"
JOB_NAME="{resource_name}"
RESOURCE_TYPE="{resource_type}"

echo "Monitoring $RESOURCE_TYPE: $JOB_NAME in namespace: $NAMESPACE"
echo "Press Ctrl+C to exit"
echo ""

watch -n 2 "oc get $RESOURCE_TYPE,job,pod -n $NAMESPACE -l {label_selector}"
'''
    return script


def generate_logs_script(job_name, namespace, storage_pvc, base_dir):
    """
    Generate logs.sh script to save and view logs from all pods.

    Args:
        job_name: Name of the job (without coldpress- prefix)
        namespace: Kubernetes namespace
        storage_pvc: PVC name for results storage
        base_dir: Base directory path in PVC

    Returns:
        str: Bash script content
    """
    full_job_name = f"coldpress-{job_name}"

    script = f'''#!/bin/bash
# Generated by coldpress on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

NAMESPACE="{namespace}"
JOB_NAME="{full_job_name}"
STORAGE_PVC="{storage_pvc}"
BASE_DIR="{base_dir}"
LOGS_DIR="$BASE_DIR/logs"

echo "Fetching and saving logs for job: $JOB_NAME"
echo ""

# Get all pods for this job (try both label formats for compatibility)
PODS=$(oc get pods -n $NAMESPACE -l coldpress.io/job-id=$JOB_NAME -o jsonpath='{{.items[*].metadata.name}}' 2>/dev/null)
if [ -z "$PODS" ]; then
    PODS=$(oc get pods -n $NAMESPACE -l coldpress/gid=$JOB_NAME -o jsonpath='{{.items[*].metadata.name}}' 2>/dev/null)
fi

if [ -z "$PODS" ]; then
    echo "No pods found for job $JOB_NAME"
    exit 1
fi

# Create helper pod to save logs to PVC
POD_NAME="log-saver-${{JOB_NAME}}-$(date +%s)"

# Cleanup function
cleanup() {{
    if [ -n "$POD_NAME" ]; then
        echo ""
        echo "Cleaning up log saver pod..."
        oc delete pod/$POD_NAME -n $NAMESPACE --ignore-not-found=true 2>/dev/null
    fi
}}

# Register cleanup trap for EXIT, INT, TERM
trap cleanup EXIT INT TERM

echo "Creating log saver pod..."
cat <<EOF | oc apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: $POD_NAME
  namespace: $NAMESPACE
spec:
  restartPolicy: Never
  containers:
  - name: saver
    image: registry.access.redhat.com/ubi9/ubi-minimal:latest
    command: ["sleep", "300"]
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: $STORAGE_PVC
EOF

# Wait for pod to be ready
oc wait --for=condition=ready pod/$POD_NAME -n $NAMESPACE --timeout=30s

# Create logs directory
oc exec -n $NAMESPACE $POD_NAME -- mkdir -p /data/$LOGS_DIR

# Fetch and save logs from each pod
for POD in $PODS; do
    echo "===== Saving logs from $POD ====="

    # Get logs and save to PVC (pipe directly to avoid tar dependency)
    oc logs -n $NAMESPACE $POD --all-containers=true 2>&1 | oc exec -i -n $NAMESPACE $POD_NAME -- sh -c "cat > /data/$LOGS_DIR/$POD.log" || echo "Could not save logs from $POD"

    # Also show to stdout
    cat <<LOGEOF
----- $POD -----
$(oc logs -n $NAMESPACE $POD --all-containers=true 2>&1 || echo "Could not fetch logs")

LOGEOF
done

# Create combined log file
echo "Creating combined log file..."
oc exec -n $NAMESPACE $POD_NAME -- sh -c "cat /data/$LOGS_DIR/*.log > /data/$LOGS_DIR/combined.log 2>/dev/null || true"

echo ""
echo "Logs saved to: /data/$LOGS_DIR/"
echo "  - Individual pod logs: *.log"
echo "  - Combined log: combined.log"
'''
    return script


def generate_explore_script(job_name, namespace, storage_pvc, base_dir):
    """
    Generate explore.sh script to interactively explore results directory.

    Creates a temporary helper pod, mounts the PVC, and opens an interactive shell.
    Automatically cleans up the pod when the shell session exits.

    Args:
        job_name: Name of the job (without coldpress- prefix)
        namespace: Kubernetes namespace
        storage_pvc: Name of the storage PVC
        base_dir: Base directory path in PVC

    Returns:
        str: Bash script content
    """
    full_job_name = f"coldpress-{job_name}"

    script = f'''#!/bin/bash
# Generated by coldpress on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

set -e

NAMESPACE="{namespace}"
JOB_NAME="{full_job_name}"
STORAGE_PVC="{storage_pvc}"
BASE_DIR="{base_dir}"
POD_NAME="coldpress-explorer-${{JOB_NAME}}-$(date +%s)"

echo "Starting interactive explorer pod..."
echo "PVC: $STORAGE_PVC"
echo "Base directory: $BASE_DIR"
echo ""

# Create temporary pod with PVC mounted
cat <<EOF | oc apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: $POD_NAME
  namespace: $NAMESPACE
  labels:
    app: coldpress-explorer
    coldpress.io/job-id: $JOB_NAME
spec:
  restartPolicy: Never
  containers:
  - name: explorer
    image: registry.access.redhat.com/ubi9/ubi-minimal:latest
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: $STORAGE_PVC
EOF

# Wait for pod to be ready
echo "Waiting for pod to start..."
oc wait --for=condition=ready pod/$POD_NAME -n $NAMESPACE --timeout=60s

echo ""
echo "===== Interactive Shell ====="
echo "You are now in the explorer pod."
echo "Results directory: /data/$BASE_DIR"
echo "PVC root: /data"
echo ""
echo "Useful commands:"
echo "  cd /data/$BASE_DIR    # Go to results directory"
echo "  ls -lh                # List files"
echo "  cat <file>            # View file contents"
echo "  tree                  # View directory tree (if installed)"
echo ""
echo "Type 'exit' to leave and cleanup the pod."
echo "============================================="
echo ""

# Cleanup function
cleanup() {{
    echo ""
    echo "Cleaning up explorer pod..."
    oc delete pod/$POD_NAME -n $NAMESPACE --ignore-not-found=true
    echo "Done!"
}}

# Register cleanup on exit
trap cleanup EXIT

# Open interactive shell
oc rsh -n $NAMESPACE $POD_NAME
'''
    return script


def generate_copy_script(job_name, namespace, storage_pvc, base_dir):
    """
    Generate cp.sh script to copy results from PVC to local directory.

    Creates a temporary helper pod, mounts the PVC, and copies results using tar.
    Automatically cleans up the pod when the copy is complete.

    Args:
        job_name: Name of the job (without coldpress- prefix)
        namespace: Kubernetes namespace
        storage_pvc: Name of the storage PVC
        base_dir: Base directory path in PVC

    Returns:
        str: Bash script content
    """
    full_job_name = f"coldpress-{job_name}"

    script = f'''#!/bin/bash
# Generated by coldpress on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

set -e

NAMESPACE="{namespace}"
JOB_NAME="{full_job_name}"
STORAGE_PVC="{storage_pvc}"
BASE_DIR="{base_dir}"
POD_NAME="coldpress-copier-${{JOB_NAME}}-$(date +%s)"

# Determine destination directory
DEST_DIR="${{1:-$(dirname "$0")/results}}"

echo "Copying results from PVC to local directory..."
echo "PVC: $STORAGE_PVC"
echo "Source directory: /data/$BASE_DIR"
echo "Destination: $DEST_DIR"
echo ""

# Create temporary pod with PVC mounted
echo "Creating temporary pod..."
cat <<EOF | oc apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: $POD_NAME
  namespace: $NAMESPACE
  labels:
    app: coldpress-copier
    coldpress.io/job-id: $JOB_NAME
spec:
  restartPolicy: Never
  containers:
  - name: copier
    image: registry.access.redhat.com/ubi9/ubi:latest
    command: ["sleep", "300"]
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: $STORAGE_PVC
EOF

# Wait for pod to be ready
echo "Waiting for pod to start..."
oc wait --for=condition=ready pod/$POD_NAME -n $NAMESPACE --timeout=60s

# Cleanup function
cleanup() {{
    echo ""
    echo "Cleaning up temporary pod..."
    oc delete pod/$POD_NAME -n $NAMESPACE --ignore-not-found=true
}}

# Register cleanup on exit
trap cleanup EXIT

# Create destination directory if it doesn't exist
mkdir -p "$DEST_DIR"

echo ""
echo "Copying files..."
# Use tar to copy files (more reliable than rsync)
oc exec -n $NAMESPACE $POD_NAME -- tar czf - -C /data/$BASE_DIR . | tar xzf - -C "$DEST_DIR"

echo ""
echo "===== Copy Complete ====="
echo "Results copied to: $DEST_DIR"
echo "=========================="
'''
    return script


def write_scripts(
    output_dir,
    job_name,
    namespace,
    storage_pvc=None,
    base_dir=None,
    configmap_name=None,
    configmap_files=None,
    manifest_type="jobset",
):
    """
    Write all bash scripts to output directory.

    Args:
        output_dir: Directory to write scripts to
        job_name: Name of the job
        namespace: Kubernetes namespace
        storage_pvc: Name of the storage PVC (optional)
        base_dir: Base directory path in PVC (optional)
        configmap_name: Name of ConfigMap to apply/delete (optional)
        configmap_files: List of files for ConfigMap (optional)
        manifest_type: Type of manifest (jobset, pytorchjob, etc.)
    """
    import os

    scripts = {
        "run.sh": generate_run_script(
            job_name,
            namespace,
            configmap_name=configmap_name,
            configmap_files=configmap_files,
            manifest_type=manifest_type,
        ),
        "cleanup.sh": generate_cleanup_script(
            job_name,
            namespace,
            configmap_name=configmap_name,
            manifest_type=manifest_type,
        ),
        "monitor.sh": generate_monitor_script(
            job_name, namespace, manifest_type=manifest_type
        ),
    }

    # Add logs, explore, and copy scripts if storage info is available
    if storage_pvc and base_dir:
        scripts["logs.sh"] = generate_logs_script(
            job_name, namespace, storage_pvc, base_dir
        )
        scripts["explore.sh"] = generate_explore_script(
            job_name, namespace, storage_pvc, base_dir
        )
        scripts["cp.sh"] = generate_copy_script(
            job_name, namespace, storage_pvc, base_dir
        )

    for filename, content in scripts.items():
        filepath = os.path.join(output_dir, filename)
        with open(filepath, "w") as f:
            f.write(content)
        # Make executable
        os.chmod(filepath, 0o755)
