# Generated by: Claude Sonnet 4.5
"""Bash script generation for Coldpress jobs."""

from datetime import datetime


def generate_run_script(
    job_name, namespace, timeout="1h", configmap_name=None, configmap_files=None
):
    """
    Generate run.sh script to apply and monitor the job.

    Args:
        job_name: Name of the JobSet
        namespace: Kubernetes namespace
        timeout: Timeout for job completion (default: 1h)
        configmap_name: Optional ConfigMap name
        configmap_files: Optional list of files to include in ConfigMap

    Returns:
        str: Bash script content
    """
    configmap_apply = ""
    if configmap_name and configmap_files:
        from_files = " ".join([f"--from-file={f}" for f in configmap_files])
        configmap_apply = f"""
# Create ConfigMap from files
echo "Creating ConfigMap from files..."
oc create configmap {configmap_name} -n {namespace} {from_files} --dry-run=client -o yaml | oc apply -f -
"""

    script = f'''#!/bin/bash
# Generated by coldpress on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

set -e

# Change to script directory to handle relative paths
cd "$(dirname "$0")"

NAMESPACE="{namespace}"
JOBSET_NAME="{job_name}"
{configmap_apply}
echo "Applying JobSet..."
oc apply -f jobset.yaml

# Apply services if they exist
if [ -f services.yaml ]; then
    echo "Applying Services..."
    oc apply -f services.yaml
fi

echo "Waiting for job to complete (timeout: {timeout})..."
oc wait --for=condition=complete jobset/$JOBSET_NAME -n $NAMESPACE --timeout={timeout} || {{
    echo "Job did not complete within {timeout}"
    echo "Current status:"
    oc get jobset/$JOBSET_NAME -n $NAMESPACE
    oc get jobs -n $NAMESPACE -l coldpress/gid=$JOBSET_NAME
    oc get pods -n $NAMESPACE -l coldpress/gid=$JOBSET_NAME
    exit 1
}}

echo "Job completed successfully!"
echo ""
echo "Results are stored in PVC. To extract results, run:"
echo "  oc exec -n $NAMESPACE deployment/<your-pod> -- tar czf - /mnt/coldpress-data/coldpress_results/$JOBSET_NAME | tar xzf -"
'''
    return script


def generate_cleanup_script(job_name, namespace, configmap_name=None):
    """
    Generate cleanup.sh script to delete job resources.

    Args:
        job_name: Name of the JobSet
        namespace: Kubernetes namespace
        configmap_name: Optional ConfigMap name to delete

    Returns:
        str: Bash script content
    """
    configmap_delete = ""
    if configmap_name:
        configmap_delete = f"""
# Delete ConfigMap
echo "Deleting ConfigMap..."
oc delete configmap/{configmap_name} -n $NAMESPACE --ignore-not-found=true
"""

    script = f'''#!/bin/bash
# Generated by coldpress on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

set -e

# Change to script directory to handle relative paths
cd "$(dirname "$0")"

NAMESPACE="{namespace}"
JOBSET_NAME="{job_name}"

echo "Cleaning up resources for job: $JOBSET_NAME"

# Delete JobSet (this cascades to Jobs and Pods)
echo "Deleting JobSet..."
oc delete jobset/$JOBSET_NAME -n $NAMESPACE --ignore-not-found=true

# Delete Services
echo "Deleting Services..."
oc delete services -n $NAMESPACE -l coldpress/gid=$JOBSET_NAME --ignore-not-found=true
{configmap_delete}

# Delete helper pods (log-saver, coldpress-explorer)
echo "Deleting helper pods..."
oc delete pods -n $NAMESPACE -l app=coldpress-explorer,coldpress/gid=$JOBSET_NAME --ignore-not-found=true
oc get pods -n $NAMESPACE --no-headers | grep -E "log-saver-${{JOBSET_NAME}}-|coldpress-explorer-${{JOBSET_NAME}}-" | awk '{{print $1}}' | xargs -r oc delete pod -n $NAMESPACE --ignore-not-found=true

echo "Cleanup complete!"
'''
    return script


def generate_monitor_script(job_name, namespace):
    """
    Generate monitor.sh script to watch job progress.

    Args:
        job_name: Name of the JobSet
        namespace: Kubernetes namespace

    Returns:
        str: Bash script content
    """
    script = f'''#!/bin/bash
# Generated by coldpress on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

NAMESPACE="{namespace}"
JOBSET_NAME="{job_name}"

echo "Monitoring job: $JOBSET_NAME in namespace: $NAMESPACE"
echo "Press Ctrl+C to exit"
echo ""

watch -n 2 "oc get jobset,job,pod -n $NAMESPACE -l coldpress/gid=$JOBSET_NAME"
'''
    return script


def generate_logs_script(job_name, namespace, storage_pvc, base_dir):
    """
    Generate logs.sh script to save and view logs from all pods.

    Args:
        job_name: Name of the JobSet
        namespace: Kubernetes namespace
        storage_pvc: PVC name for results storage
        base_dir: Base directory path in PVC

    Returns:
        str: Bash script content
    """
    script = f'''#!/bin/bash
# Generated by coldpress on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

NAMESPACE="{namespace}"
JOBSET_NAME="{job_name}"
STORAGE_PVC="{storage_pvc}"
BASE_DIR="{base_dir}"
LOGS_DIR="$BASE_DIR/logs"

echo "Fetching and saving logs for job: $JOBSET_NAME"
echo ""

# Get all pods for this job
PODS=$(oc get pods -n $NAMESPACE -l coldpress/gid=$JOBSET_NAME -o jsonpath='{{.items[*].metadata.name}}')

if [ -z "$PODS" ]; then
    echo "No pods found for job $JOBSET_NAME"
    exit 1
fi

# Create helper pod to save logs to PVC
POD_NAME="log-saver-${{JOBSET_NAME}}-$(date +%s)"

# Cleanup function
cleanup() {{
    if [ -n "$POD_NAME" ]; then
        echo ""
        echo "Cleaning up log saver pod..."
        oc delete pod/$POD_NAME -n $NAMESPACE --ignore-not-found=true 2>/dev/null
    fi
}}

# Register cleanup trap for EXIT, INT, TERM
trap cleanup EXIT INT TERM

echo "Creating log saver pod..."
cat <<EOF | oc apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: $POD_NAME
  namespace: $NAMESPACE
spec:
  restartPolicy: Never
  containers:
  - name: saver
    image: registry.access.redhat.com/ubi9/ubi-minimal:latest
    command: ["sleep", "300"]
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: $STORAGE_PVC
EOF

# Wait for pod to be ready
oc wait --for=condition=ready pod/$POD_NAME -n $NAMESPACE --timeout=30s

# Create logs directory
oc exec -n $NAMESPACE $POD_NAME -- mkdir -p /data/$LOGS_DIR

# Fetch and save logs from each pod
for POD in $PODS; do
    echo "===== Saving logs from $POD ====="

    # Get logs and save to PVC (pipe directly to avoid tar dependency)
    oc logs -n $NAMESPACE $POD --all-containers=true 2>&1 | oc exec -i -n $NAMESPACE $POD_NAME -- sh -c "cat > /data/$LOGS_DIR/$POD.log" || echo "Could not save logs from $POD"

    # Also show to stdout
    cat <<LOGEOF
----- $POD -----
$(oc logs -n $NAMESPACE $POD --all-containers=true 2>&1 || echo "Could not fetch logs")

LOGEOF
done

# Create combined log file
echo "Creating combined log file..."
oc exec -n $NAMESPACE $POD_NAME -- sh -c "cat /data/$LOGS_DIR/*.log > /data/$LOGS_DIR/combined.log 2>/dev/null || true"

echo ""
echo "Logs saved to: /data/$LOGS_DIR/"
echo "  - Individual pod logs: *.log"
echo "  - Combined log: combined.log"
'''
    return script


def generate_explore_script(job_name, namespace, storage_pvc, base_dir):
    """
    Generate explore.sh script to interactively explore results directory.

    Creates a temporary helper pod, mounts the PVC, and opens an interactive shell.
    Automatically cleans up the pod when the shell session exits.

    Args:
        job_name: Name of the JobSet
        namespace: Kubernetes namespace
        storage_pvc: Name of the storage PVC
        base_dir: Base directory path in PVC

    Returns:
        str: Bash script content
    """
    script = f'''#!/bin/bash
# Generated by coldpress on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

set -e

NAMESPACE="{namespace}"
JOBSET_NAME="{job_name}"
STORAGE_PVC="{storage_pvc}"
BASE_DIR="{base_dir}"
POD_NAME="coldpress-explorer-${{JOBSET_NAME}}-$(date +%s)"

echo "Starting interactive explorer pod..."
echo "PVC: $STORAGE_PVC"
echo "Base directory: $BASE_DIR"
echo ""

# Create temporary pod with PVC mounted
cat <<EOF | oc apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: $POD_NAME
  namespace: $NAMESPACE
  labels:
    app: coldpress-explorer
    coldpress/gid: $JOBSET_NAME
spec:
  restartPolicy: Never
  containers:
  - name: explorer
    image: registry.access.redhat.com/ubi9/ubi-minimal:latest
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: $STORAGE_PVC
EOF

# Wait for pod to be ready
echo "Waiting for pod to start..."
oc wait --for=condition=ready pod/$POD_NAME -n $NAMESPACE --timeout=60s

echo ""
echo "===== Interactive Shell ====="
echo "You are now in the explorer pod."
echo "Results directory: /data/$BASE_DIR"
echo "PVC root: /data"
echo ""
echo "Useful commands:"
echo "  cd /data/$BASE_DIR    # Go to results directory"
echo "  ls -lh                # List files"
echo "  cat <file>            # View file contents"
echo "  tree                  # View directory tree (if installed)"
echo ""
echo "Type 'exit' to leave and cleanup the pod."
echo "============================================="
echo ""

# Cleanup function
cleanup() {{
    echo ""
    echo "Cleaning up explorer pod..."
    oc delete pod/$POD_NAME -n $NAMESPACE --ignore-not-found=true
    echo "Done!"
}}

# Register cleanup on exit
trap cleanup EXIT

# Open interactive shell
oc rsh -n $NAMESPACE $POD_NAME
'''
    return script


def generate_copy_script(job_name, namespace, storage_pvc, base_dir):
    """
    Generate cp.sh script to copy results from PVC to local directory.

    Creates a temporary helper pod, mounts the PVC, and copies results using tar.
    Automatically cleans up the pod when the copy is complete.

    Args:
        job_name: Name of the JobSet
        namespace: Kubernetes namespace
        storage_pvc: Name of the storage PVC
        base_dir: Base directory path in PVC

    Returns:
        str: Bash script content
    """
    script = f'''#!/bin/bash
# Generated by coldpress on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

set -e

NAMESPACE="{namespace}"
JOBSET_NAME="{job_name}"
STORAGE_PVC="{storage_pvc}"
BASE_DIR="{base_dir}"
POD_NAME="coldpress-copier-${{JOBSET_NAME}}-$(date +%s)"

# Determine destination directory
DEST_DIR="${{1:-$(dirname "$0")/results}}"

echo "Copying results from PVC to local directory..."
echo "PVC: $STORAGE_PVC"
echo "Source directory: /data/$BASE_DIR"
echo "Destination: $DEST_DIR"
echo ""

# Create temporary pod with PVC mounted
echo "Creating temporary pod..."
cat <<EOF | oc apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: $POD_NAME
  namespace: $NAMESPACE
  labels:
    app: coldpress-copier
    coldpress/gid: $JOBSET_NAME
spec:
  restartPolicy: Never
  containers:
  - name: copier
    image: registry.access.redhat.com/ubi9/ubi:latest
    command: ["sleep", "300"]
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: $STORAGE_PVC
EOF

# Wait for pod to be ready
echo "Waiting for pod to start..."
oc wait --for=condition=ready pod/$POD_NAME -n $NAMESPACE --timeout=60s

# Cleanup function
cleanup() {{
    echo ""
    echo "Cleaning up temporary pod..."
    oc delete pod/$POD_NAME -n $NAMESPACE --ignore-not-found=true
}}

# Register cleanup on exit
trap cleanup EXIT

# Create destination directory if it doesn't exist
mkdir -p "$DEST_DIR"

echo ""
echo "Copying files..."
# Use tar to copy files (more reliable than rsync)
oc exec -n $NAMESPACE $POD_NAME -- tar czf - -C /data/$BASE_DIR . | tar xzf - -C "$DEST_DIR"

echo ""
echo "===== Copy Complete ====="
echo "Results copied to: $DEST_DIR"
echo "=========================="
'''
    return script


def write_scripts(
    output_dir,
    job_name,
    namespace,
    storage_pvc=None,
    base_dir=None,
    configmap_name=None,
    configmap_files=None,
):
    """
    Write all bash scripts to output directory.

    Args:
        output_dir: Directory to write scripts to
        job_name: Name of the JobSet
        namespace: Kubernetes namespace
        storage_pvc: Name of the storage PVC (optional)
        base_dir: Base directory path in PVC (optional)
        configmap_name: Name of ConfigMap to apply/delete (optional)
        configmap_files: List of files for ConfigMap (optional)
    """
    import os

    scripts = {
        "run.sh": generate_run_script(
            job_name,
            namespace,
            configmap_name=configmap_name,
            configmap_files=configmap_files,
        ),
        "cleanup.sh": generate_cleanup_script(
            job_name, namespace, configmap_name=configmap_name
        ),
        "monitor.sh": generate_monitor_script(job_name, namespace),
    }

    # Add logs, explore, and copy scripts if storage info is available
    if storage_pvc and base_dir:
        scripts["logs.sh"] = generate_logs_script(
            job_name, namespace, storage_pvc, base_dir
        )
        scripts["explore.sh"] = generate_explore_script(
            job_name, namespace, storage_pvc, base_dir
        )
        scripts["cp.sh"] = generate_copy_script(
            job_name, namespace, storage_pvc, base_dir
        )

    for filename, content in scripts.items():
        filepath = os.path.join(output_dir, filename)
        with open(filepath, "w") as f:
            f.write(content)
        # Make executable
        os.chmod(filepath, 0o755)
