# Generated by: Claude Sonnet 4.5
"""Pydantic models for validating Coldpress YAML configurations.

This module provides validation for all YAML configuration files used by Coldpress tools
(coldpress and coldpress-setup), ensuring schema correctness at load time rather than
during execution.

Usage:
    import yaml
    from coldpress_common import (
        validate_config,
        validate_task_specs,
        validate_project_config,
        validate_user_config
    )

    # Validate config.yaml (workload configuration)
    with open("config.yaml") as f:
        config_data = yaml.safe_load(f)
        config = validate_config(config_data)

    # Validate job-spec.yaml (task specifications)
    with open("job-spec.yaml") as f:
        task_specs = list(yaml.safe_load_all(f))
        validated_tasks = validate_task_specs(task_specs)

    # Validate project config
    with open("projects/my-project.yaml") as f:
        project_data = yaml.safe_load(f)
        project = validate_project_config(project_data)

    # Validate user config
    with open("users/username.yaml") as f:
        user_data = yaml.safe_load(f)
        user = validate_user_config(user_data)

The validation functions raise pydantic.ValidationError with clear error messages
when the YAML structure is invalid, making it easy to catch configuration errors
early rather than during job execution.
"""

from typing import Any, Literal, Optional, Union
from pydantic import BaseModel, Field, field_validator, model_validator


# === Container and Resource Models ===


class ResourceSpec(BaseModel):
    """Resource requests or limits."""

    cpu: Optional[str] = None
    memory: Optional[str] = None
    nvidia_com_gpu: Optional[str] = Field(None, alias="nvidia.com/gpu")

    class Config:
        populate_by_name = True
        extra = "allow"  # Allow additional resource types like RDMA NICs


class ContainerResources(BaseModel):
    """Container resource requirements."""

    requests: Optional[ResourceSpec] = None
    limits: Optional[ResourceSpec] = None


class EnvVar(BaseModel):
    """Environment variable."""

    name: str
    value: str


class PortSpec(BaseModel):
    """Container port specification."""

    containerPort: int
    name: Optional[str] = None
    protocol: Optional[str] = "TCP"


class HTTPGetAction(BaseModel):
    """HTTP GET action for probes."""

    path: str = "/"
    port: Union[int, str] = 80
    scheme: Optional[str] = "HTTP"


class ReadinessProbe(BaseModel):
    """Readiness probe configuration."""

    httpGet: Optional[HTTPGetAction] = None
    initialDelaySeconds: Optional[int] = 30
    periodSeconds: Optional[int] = 10
    failureThreshold: Optional[int] = 10


class ContainerSpec(BaseModel):
    """Container specification within a task."""

    name: str
    image: str
    command: Optional[Union[str, list[str]]] = None
    args: Optional[Union[str, list[str]]] = None
    workingDir: Optional[str] = None
    env: Optional[Union[dict[str, Any], list[EnvVar]]] = None
    resources: Optional[ContainerResources] = None
    ports: Optional[list[PortSpec]] = None
    readinessProbe: Optional[ReadinessProbe] = None


# === Volume Models ===


class VolumeSpec(BaseModel):
    """Volume specification."""

    name: str
    type: Optional[str] = "pvc"  # "pvc", "emptyDir", "configMap"
    mount: Optional[str] = None  # Mount path
    medium: Optional[str] = None  # For emptyDir: "Memory"
    sizeLimit: Optional[str] = None  # For emptyDir
    subPath: Optional[str] = None


class SysMountSpec(BaseModel):
    """System/host path mount specification."""

    source: str
    target: str
    read_only: Optional[bool] = False


# === Task Models ===


class TaskSpec(BaseModel):
    """Task specification from job-spec.yaml."""

    name: str
    containers: list[ContainerSpec]

    # Legacy flat format support
    image: Optional[str] = None
    command: Optional[Union[str, list[str]]] = None
    args: Optional[Union[str, list[str]]] = None
    workingDir: Optional[str] = None
    env: Optional[Union[dict[str, Any], list[EnvVar]]] = None
    resources: Optional[ContainerResources] = None
    gpus: Optional[int] = 0

    # Task behavior
    blocking: Optional[Literal["completion", "endpoint"]] = None
    health_check: Optional[str] = None
    result_path: Optional[str] = None
    roce_nics: Optional[int] = 0

    # Pod configuration
    tolerate_all: Optional[bool] = False
    network_mode: Optional[Literal["host", "default"]] = "default"
    privileged: Optional[bool] = False
    annotations: Optional[dict[str, str]] = None

    # Volume configuration
    volumes: Optional[list[VolumeSpec]] = None
    ephemeral_mounts: Optional[Union[str, list[Union[str, dict]]]] = None
    sys_mounts: Optional[list[SysMountSpec]] = None

    @field_validator("containers", mode="before")
    @classmethod
    def ensure_containers_is_list(cls, v):
        """Ensure containers is a list."""
        if isinstance(v, dict):
            return [v]
        return v

    @model_validator(mode="after")
    def validate_blocking_endpoint(self):
        """Validate endpoint blocking has health_check or readinessProbe."""
        if self.blocking == "endpoint":
            has_health_check = self.health_check is not None
            has_readiness_probe = (
                self.containers
                and len(self.containers) > 0
                and self.containers[0].readinessProbe is not None
            )
            if not has_health_check and not has_readiness_probe:
                raise ValueError(
                    f"Task '{self.name}' has blocking='endpoint' but no health_check or readinessProbe"
                )
        return self


# === Config Models ===


class NodeConfig(BaseModel):
    """Node configuration for cluster setup."""

    hostname: str
    gpus: Optional[int] = 0
    roce_nics: Optional[int] = 0


class ClusterConfig(BaseModel):
    """Cluster configuration from cluster/*.yaml."""

    nodes: list[NodeConfig]
    cluster_queue: Optional[str] = "cluster-queue-default"

    @field_validator("nodes")
    @classmethod
    def ensure_nodes_not_empty(cls, v):
        """Ensure nodes list is not empty."""
        if not v:
            raise ValueError("Cluster config must include at least one node")
        return v


class DiscoveryConfig(BaseModel):
    """Discovery configuration - can be string or dict."""

    template: str
    tasks: Optional[Union[str, list[int]]] = "all"  # "all" or list of task indices

    @field_validator("tasks", mode="before")
    @classmethod
    def parse_tasks(cls, v):
        """Parse tasks field - accept 'all', list of ints, or single int."""
        if v is None:
            return "all"
        if isinstance(v, str):
            return v.lower()
        if isinstance(v, int):
            return [v]
        return v


class WorkloadConfig(BaseModel):
    """Main config.yaml schema."""

    project: Optional[str] = None
    discovery: Optional[Union[str, DiscoveryConfig]] = None
    output: Optional[str] = None
    files: Optional[list[str]] = None
    nodes: Optional[list[int]] = None  # Explicit node assignments for tasks

    @field_validator("discovery", mode="before")
    @classmethod
    def parse_discovery(cls, v):
        """Parse discovery field - accept string or dict."""
        if v is None:
            return None
        if isinstance(v, str):
            # Convert simple string to DiscoveryConfig
            return {"template": v, "tasks": "all"}
        return v

    @model_validator(mode="after")
    def validate_has_project(self):
        """Ensure project is specified (can be overridden via CLI)."""
        # Note: project can be None if provided via CLI --project flag
        return self


class StorageConfig(BaseModel):
    """Storage configuration."""

    results: str
    models: Optional[str] = "coldpress-model-storage"
    size: Optional[str] = "500Gi"


class ProjectConfig(BaseModel):
    """Project configuration from projects/*.yaml."""

    namespace: str
    cluster_queue: Optional[str] = None
    storage_class: Optional[str] = None
    storage: Optional[StorageConfig] = None

    @field_validator("storage", mode="before")
    @classmethod
    def ensure_storage_exists(cls, v):
        """Ensure storage config exists with at least results PVC."""
        if v is None:
            return None
        if isinstance(v, dict) and "results" not in v:
            raise ValueError("Storage configuration must include 'results' PVC")
        return v


class UserConfig(BaseModel):
    """User configuration from users/*.yaml."""

    username: str
    namespaces: list[str]

    @field_validator("namespaces")
    @classmethod
    def ensure_namespaces_not_empty(cls, v):
        """Ensure namespaces list is not empty."""
        if not v:
            raise ValueError("User config must include at least one namespace")
        return v


class JobSpec(BaseModel):
    """Complete job specification built from multiple sources."""

    name: str
    namespace: str
    tasks: list[TaskSpec]
    storage: Optional[dict[str, str]] = None
    discovery: Optional[dict[str, str]] = None
    configmap: Optional[dict[str, Any]] = None


# === Validation Functions ===


def validate_config(config_data: dict) -> WorkloadConfig:
    """
    Validate config.yaml data.

    Args:
        config_data: Raw YAML data from config file

    Returns:
        Validated WorkloadConfig

    Raises:
        ValidationError: If validation fails
    """
    return WorkloadConfig.model_validate(config_data)


def validate_project_config(project_data: dict) -> ProjectConfig:
    """
    Validate project configuration.

    Args:
        project_data: Raw YAML data from project file

    Returns:
        Validated ProjectConfig

    Raises:
        ValidationError: If validation fails
    """
    return ProjectConfig.model_validate(project_data)


def validate_task_specs(task_specs_data: list[dict]) -> list[TaskSpec]:
    """
    Validate job-spec.yaml task specifications.

    Args:
        task_specs_data: List of raw YAML task specs

    Returns:
        List of validated TaskSpec objects

    Raises:
        ValidationError: If validation fails
    """
    validated_tasks = []
    for i, task_data in enumerate(task_specs_data):
        try:
            validated_tasks.append(TaskSpec.model_validate(task_data))
        except Exception as e:
            # Re-raise with task context
            raise ValueError(f"Task {i} validation failed: {e}") from e
    return validated_tasks


def validate_job_spec(job_spec_data: dict) -> JobSpec:
    """
    Validate complete job specification.

    Args:
        job_spec_data: Complete job spec dict

    Returns:
        Validated JobSpec

    Raises:
        ValidationError: If validation fails
    """
    return JobSpec.model_validate(job_spec_data)


def validate_user_config(user_data: dict) -> UserConfig:
    """
    Validate user configuration.

    Args:
        user_data: Raw YAML data from user file

    Returns:
        Validated UserConfig

    Raises:
        ValidationError: If validation fails
    """
    return UserConfig.model_validate(user_data)


def validate_cluster_config(cluster_data: dict) -> ClusterConfig:
    """
    Validate cluster configuration.

    Args:
        cluster_data: Raw YAML data from cluster file

    Returns:
        Validated ClusterConfig

    Raises:
        ValidationError: If validation fails
    """
    return ClusterConfig.model_validate(cluster_data)
