#!/usr/bin/env python3
# Generated by: Claude Sonnet 4.5
"""
coldpress.distributed.run - Run distributed training on Kubernetes

This module can be invoked as:
    python -m coldpress.distributed.run [OPTIONS] script.py [SCRIPT_ARGS]

It creates PyTorchJobs on Kubernetes with Kueue integration.
"""

import sys
from coldpress.distributed.run import main

if __name__ == "__main__":
    sys.exit(main())
