#!/usr/bin/env python3
# Generated by: Claude Sonnet 4.5
"""
coldpress.distributed.run - Run distributed training on Kubernetes

Usage:
    python -m coldpress.distributed.run --nproc_per_node=2 train.py --epochs 10

Mimics torch.distributed.run but runs on cluster instead of locally.
"""

import argparse
import sys
import os
from pathlib import Path
from datetime import datetime, timezone
import yaml
import subprocess
import shutil
import tempfile
import time


def get_kubectl_cmd():
    """Get kubectl or oc command."""
    if shutil.which("oc"):
        return "oc"
    return "kubectl"


def get_current_namespace():
    """Get current Kubernetes namespace from context."""
    kubectl = get_kubectl_cmd()
    try:
        result = subprocess.run(
            [kubectl, "config", "view", "--minify", "-o", "jsonpath={..namespace}"],
            capture_output=True,
            text=True,
            check=True,
        )
        namespace = result.stdout.strip()
        if not namespace:
            namespace = "default"
        return namespace
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "default"


def load_project_config(project_name):
    """Load project configuration."""
    from coldpress_common import validate_project_config
    from pydantic import ValidationError

    # Try home directory first
    home_config = Path.home() / f"{project_name}.yaml"
    if home_config.exists():
        with open(home_config, "r") as f:
            config_data = yaml.safe_load(f)
            try:
                validated = validate_project_config(config_data)
                return validated.model_dump(by_alias=True, exclude_none=True)
            except ValidationError as e:
                print(f"Error: Project config validation failed: {e}", file=sys.stderr)
                sys.exit(1)

    # Try projects directory
    project_dir = Path("projects")
    project_config_file = project_dir / f"{project_name}.yaml"
    if project_config_file.exists():
        with open(project_config_file, "r") as f:
            config_data = yaml.safe_load(f)
            try:
                validated = validate_project_config(config_data)
                return validated.model_dump(by_alias=True, exclude_none=True)
            except ValidationError as e:
                print(f"Error: Project config validation failed: {e}", file=sys.stderr)
                sys.exit(1)

    # Return minimal default config (still validate it)
    default_config = {
        "namespace": project_name,
        "storage": {"results": f"{project_name}-storage"},
    }
    try:
        validated = validate_project_config(default_config)
        return validated.model_dump(by_alias=True, exclude_none=True)
    except ValidationError as e:
        print(f"Error: Default config validation failed: {e}", file=sys.stderr)
        sys.exit(1)


def generate_manifest(
    job_name,
    namespace,
    image,
    script_content,
    script_name,
    script_args,
    nproc_per_node,
    nnodes,
    resources,
    storage_pvc,
    base_dir,
    project_config,
):
    """Generate PyTorchJob manifest."""
    # Build resource spec
    resource_spec = {}
    if resources:
        limits = {}
        requests = {}

        if "nvidia.com/gpu" in resources:
            limits["nvidia.com/gpu"] = resources["nvidia.com/gpu"]
            requests["nvidia.com/gpu"] = resources["nvidia.com/gpu"]

        if "cpu" in resources:
            limits["cpu"] = str(resources["cpu"])
            requests["cpu"] = str(resources["cpu"])

        if "memory" in resources:
            limits["memory"] = resources["memory"]
            requests["memory"] = resources["memory"]

        if limits:
            resource_spec["limits"] = limits
        if requests:
            resource_spec["requests"] = requests

    # Build command
    command_args = [
        "python",
        "-m",
        "torch.distributed.run",
        f"--nproc_per_node={nproc_per_node}",
        f"--nnodes={nnodes}",
        "--node_rank=$(RANK)",
        "--master_addr=$(MASTER_ADDR)",
        "--master_port=$(MASTER_PORT)",
        f"/workspace/{script_name}",
    ]
    command_args.extend(script_args)

    # Build container
    container = {
        "name": "pytorch",
        "image": image,
        "workingDir": "/workspace",
        "command": command_args,
        "env": [
            {"name": "NCCL_DEBUG", "value": "INFO"},
        ],
        "volumeMounts": [
            {"name": "workspace", "mountPath": "/workspace"},
            {"name": "results", "mountPath": "/results"},
            {"name": "dshm", "mountPath": "/dev/shm"},
        ],
    }

    if resource_spec:
        container["resources"] = resource_spec

    # Build ConfigMap
    configmap_name = f"{job_name}-script"
    configmap = {
        "apiVersion": "v1",
        "kind": "ConfigMap",
        "metadata": {
            "name": configmap_name,
            "namespace": namespace,
            "labels": {
                "app.kubernetes.io/managed-by": "coldpress",
                "coldpress.io/job-id": job_name,
            },
        },
        "data": {
            script_name: script_content,
        },
    }

    # Build init container
    mkdir_init = {
        "name": "mkdir",
        "image": "registry.access.redhat.com/ubi9/ubi-minimal:latest",
        "command": ["sh", "-c"],
        "args": [
            f"mkdir -p /results/{base_dir} && echo Created directory /results/{base_dir}"
        ],
        "volumeMounts": [{"name": "results", "mountPath": "/results"}],
    }

    # Build pod template (Kueue will handle node assignment based on ResourceFlavors)
    pod_template = {
        "metadata": {
            "annotations": {"sidecar.istio.io/inject": "false"},
            "labels": {
                "app.kubernetes.io/managed-by": "coldpress",
                "coldpress.io/job-id": job_name,
            },
        },
        "spec": {
            "initContainers": [mkdir_init],
            "containers": [container],
            "restartPolicy": "OnFailure",
            "tolerations": [{"operator": "Exists"}],
            "volumes": [
                {
                    "name": "workspace",
                    "configMap": {"name": configmap_name},
                },
                {
                    "name": "results",
                    "persistentVolumeClaim": {"claimName": storage_pvc},
                },
                {
                    "name": "dshm",
                    "emptyDir": {
                        "medium": "Memory",
                        "sizeLimit": "16Gi",
                    },
                },
            ],
        },
    }

    # Build PyTorchJob
    # Queue name follows standard coldpress naming convention
    queue_name = f"coldpress-local-queue-{namespace}"

    pytorchjob_labels = {
        "app.kubernetes.io/managed-by": "coldpress",
        "coldpress.io/job-id": job_name,
        "kueue.x-k8s.io/queue-name": queue_name,
    }

    pytorchjob = {
        "apiVersion": "kubeflow.org/v1",
        "kind": "PyTorchJob",
        "metadata": {
            "name": job_name,
            "namespace": namespace,
            "labels": pytorchjob_labels,
            "annotations": {
                "coldpress.io/base-dir": base_dir,
                "coldpress.io/storage-pvc": storage_pvc,
                "kueue.x-k8s.io/wait-for-pods-ready-timeout": "20m",
            },
        },
        "spec": {
            "suspend": True,  # Start suspended for Kueue
            "pytorchReplicaSpecs": {
                "Master": {
                    "replicas": 1,
                    "restartPolicy": "OnFailure",
                    "template": pod_template,
                }
            },
        },
    }

    if nnodes > 1:
        pytorchjob["spec"]["pytorchReplicaSpecs"]["Worker"] = {
            "replicas": nnodes - 1,
            "restartPolicy": "OnFailure",
            "template": pod_template,
        }

    return {"configmap": configmap, "pytorchjob": pytorchjob}


def apply_manifest(manifest, namespace):
    """Apply manifest to cluster."""
    kubectl = get_kubectl_cmd()
    with tempfile.NamedTemporaryFile(mode="w", suffix=".yaml", delete=False) as f:
        yaml.safe_dump(
            manifest["configmap"], f, default_flow_style=False, sort_keys=False
        )
        f.write("---\n")
        yaml.safe_dump(
            manifest["pytorchjob"], f, default_flow_style=False, sort_keys=False
        )
        manifest_path = f.name

    try:
        subprocess.run(
            [kubectl, "apply", "-f", manifest_path, "-n", namespace],
            check=True,
            capture_output=True,
            text=True,
        )
    finally:
        Path(manifest_path).unlink(missing_ok=True)


def wait_for_job(job_name, namespace, timeout=300):
    """Wait for job to start running."""
    kubectl = get_kubectl_cmd()
    start_time = time.time()

    while time.time() - start_time < timeout:
        try:
            pod_result = subprocess.run(
                [
                    kubectl,
                    "get",
                    "pods",
                    "-n",
                    namespace,
                    "-l",
                    f"training.kubeflow.org/job-name={job_name}",
                    "-o",
                    "jsonpath={.items[*].status.phase}",
                ],
                capture_output=True,
                text=True,
                check=True,
            )

            phases = pod_result.stdout.strip().split()
            if phases and all(p == "Running" for p in phases):
                return True

            time.sleep(2)
        except subprocess.CalledProcessError:
            time.sleep(2)
            continue

    raise TimeoutError(f"Job {job_name} did not start within {timeout}s")


def stream_logs(job_name, namespace):
    """Stream logs from master pod and return success status."""
    kubectl = get_kubectl_cmd()
    try:
        result = subprocess.run(
            [
                kubectl,
                "get",
                "pods",
                "-n",
                namespace,
                "-l",
                f"training.kubeflow.org/job-name={job_name},training.kubeflow.org/replica-type=master",
                "-o",
                "jsonpath={.items[0].metadata.name}",
            ],
            capture_output=True,
            text=True,
            check=True,
        )
        master_pod = result.stdout.strip()

        if not master_pod:
            print(
                f"Warning: Could not find master pod for job {job_name}",
                file=sys.stderr,
            )
            return False

        subprocess.run(
            [kubectl, "logs", "-f", master_pod, "-n", namespace, "-c", "pytorch"],
            check=False,
        )

        return True

    except subprocess.CalledProcessError as e:
        print(f"Error streaming logs: {e}", file=sys.stderr)
        return False
    except KeyboardInterrupt:
        print("\nLog streaming interrupted by user", file=sys.stderr)
        return False


def check_job_success(job_name, namespace):
    """Check if PyTorchJob succeeded."""
    kubectl = get_kubectl_cmd()

    # Wait up to 30 seconds for the job status to be updated
    for i in range(30):
        try:
            result = subprocess.run(
                [
                    kubectl,
                    "get",
                    "pytorchjob",
                    job_name,
                    "-n",
                    namespace,
                    "-o",
                    "jsonpath={.status.conditions[?(@.type=='Succeeded')].status}",
                ],
                capture_output=True,
                text=True,
                check=True,
            )
            if result.stdout.strip() == "True":
                return True

            # Check if job failed
            result_failed = subprocess.run(
                [
                    kubectl,
                    "get",
                    "pytorchjob",
                    job_name,
                    "-n",
                    namespace,
                    "-o",
                    "jsonpath={.status.conditions[?(@.type=='Failed')].status}",
                ],
                capture_output=True,
                text=True,
                check=True,
            )
            if result_failed.stdout.strip() == "True":
                return False

            # Status not set yet, wait a bit
            time.sleep(1)
        except subprocess.CalledProcessError:
            return False

    # Timeout waiting for status
    return False


def copy_results_from_pvc(base_dir, storage_pvc, namespace, local_output_path):
    """Copy results from PVC to local output directory."""
    kubectl = get_kubectl_cmd()

    # Create local output directory
    local_output = Path(local_output_path)
    local_output.mkdir(parents=True, exist_ok=True)

    # Create a temporary pod to access the PVC
    temp_pod_name = (
        f"coldpress-copy-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}"
    )

    pod_manifest = {
        "apiVersion": "v1",
        "kind": "Pod",
        "metadata": {
            "name": temp_pod_name,
            "namespace": namespace,
        },
        "spec": {
            "containers": [
                {
                    "name": "copy",
                    "image": "registry.access.redhat.com/ubi9/ubi:latest",
                    "command": ["sleep", "infinity"],
                    "volumeMounts": [
                        {
                            "name": "results",
                            "mountPath": "/results",
                        }
                    ],
                }
            ],
            "volumes": [
                {
                    "name": "results",
                    "persistentVolumeClaim": {"claimName": storage_pvc},
                }
            ],
            "restartPolicy": "Never",
        },
    }

    with tempfile.NamedTemporaryFile(mode="w", suffix=".yaml", delete=False) as f:
        yaml.safe_dump(pod_manifest, f)
        pod_file = f.name

    try:
        # Create the pod
        subprocess.run(
            [kubectl, "apply", "-f", pod_file, "-n", namespace],
            check=True,
            capture_output=True,
            text=True,
        )

        # Wait for pod to be ready
        print(f"Copying results from PVC to {local_output}/...")
        pod_ready = False
        for i in range(120):  # Wait up to 2 minutes
            result = subprocess.run(
                [
                    kubectl,
                    "get",
                    "pod",
                    temp_pod_name,
                    "-n",
                    namespace,
                    "-o",
                    "jsonpath={.status.containerStatuses[0].ready}",
                ],
                capture_output=True,
                text=True,
                check=False,
            )
            if result.stdout.strip() == "true":
                pod_ready = True
                break
            time.sleep(1)

        if not pod_ready:
            print("Warning: Copy pod did not become ready", file=sys.stderr)
            return

        # Give it a moment to fully stabilize
        time.sleep(2)

        # First check if the directory exists and list its contents
        check_result = subprocess.run(
            [
                kubectl,
                "exec",
                temp_pod_name,
                "-n",
                namespace,
                "-c",
                "copy",
                "--",
                "sh",
                "-c",
                f"ls -la /results/{base_dir} 2>/dev/null || echo 'Directory not found'",
            ],
            capture_output=True,
            text=True,
            check=False,
        )

        if check_result.returncode == 0:
            print(f"Contents of /results/{base_dir}:")
            print(check_result.stdout)

        # Copy files from pod to local with retry logic
        # Use tar directly to avoid oc cp tar stream issues with large files
        max_retries = 3
        retry_delay = 2

        for attempt in range(max_retries):
            if attempt > 0:
                time.sleep(retry_delay * attempt)  # Exponential backoff

            # Alternative: use tar piping for more reliable large file transfers
            # cd into the target directory and tar current dir to avoid nested paths
            tar_cmd = f"cd /results/{base_dir} && tar czf - ."
            result = subprocess.run(
                f"{kubectl} exec {temp_pod_name} -n {namespace} -c copy -- sh -c '{tar_cmd}' | tar xzf - -C {local_output}",
                shell=True,
                check=False,
                capture_output=True,
                text=True,
                timeout=300,
            )

            if result.returncode == 0:
                # Check if we got any files
                file_count = len(list(local_output.rglob("*")))
                print(f"Results copied to: {local_output}/ ({file_count} files)")
                break

        # Silently skip error output on copy failure if retries exhausted

        # Delete the temporary pod
        subprocess.run(
            [kubectl, "delete", "pod", temp_pod_name, "-n", namespace, "--wait=false"],
            check=False,
            capture_output=True,
            text=True,
            timeout=10,
        )

    except Exception as e:
        print(f"Warning: Error copying results: {e}", file=sys.stderr)
    finally:
        Path(pod_file).unlink(missing_ok=True)


def cleanup_job(job_name, namespace):
    """Delete job and resources."""
    kubectl = get_kubectl_cmd()
    try:
        subprocess.run(
            [kubectl, "delete", "pytorchjob", job_name, "-n", namespace],
            check=True,
            capture_output=True,
            text=True,
        )

        configmap_name = f"{job_name}-script"
        subprocess.run(
            [kubectl, "delete", "configmap", configmap_name, "-n", namespace],
            check=False,
            capture_output=True,
            text=True,
        )

    except subprocess.CalledProcessError as e:
        print(f"Warning: Error during cleanup: {e}", file=sys.stderr)


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Run distributed training on Kubernetes (like torchrun)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    # torchrun-compatible args
    parser.add_argument("--nproc_per_node", "--nproc-per-node", type=int, default=None)
    parser.add_argument("--nnodes", type=int, default=None)

    parser.add_argument("training_script", type=str)
    parser.add_argument("script_args", nargs=argparse.REMAINDER)

    args = parser.parse_args()

    # Detect env vars (like torchrun)
    nproc_per_node = args.nproc_per_node or int(os.getenv("NPROC_PER_NODE", "1"))
    nnodes = args.nnodes or int(os.getenv("NNODES", "1"))

    if not Path(args.training_script).exists():
        print(
            f"Error: Training script not found: {args.training_script}", file=sys.stderr
        )
        return 1

    namespace = get_current_namespace()
    project = namespace
    project_config = load_project_config(project)

    # Default GPU to nproc_per_node
    gpu = nproc_per_node
    image = "pytorch/pytorch:2.2.0-cuda12.1-cudnn8-runtime"
    # Storage is validated by Pydantic - if present, 'results' is required
    storage = project_config.get("storage")
    if storage:
        storage_pvc = storage["results"]
    else:
        storage_pvc = f"{namespace}-storage"

    script_name = Path(args.training_script).stem
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    job_name = f"coldpress-{script_name}-{timestamp}"
    base_dir = f"{namespace}/coldpress_results/{script_name}-{timestamp}"

    # Build resources - match job-spec.yaml defaults
    resources = {}
    if gpu and gpu > 0:
        resources["nvidia.com/gpu"] = gpu
        resources["cpu"] = 8  # Default from job-spec
        resources["memory"] = "16Gi"  # Default from job-spec

    print(f"Generating PyTorchJob: {args.training_script}")
    print(f"  Namespace: {namespace}")
    print(f"  Nodes: {nnodes}")
    print(f"  Processes/node: {nproc_per_node}")
    if gpu:
        print(f"  GPUs/pod: {gpu}")

    with open(args.training_script, "r") as f:
        script_content = f.read()

    # Add --output-dir to script args if not present
    script_args = list(args.script_args)
    if not any("--output-dir" in arg or "--output_dir" in arg for arg in script_args):
        script_args.append(f"--output-dir=/results/{base_dir}")

    manifest = generate_manifest(
        job_name,
        namespace,
        image,
        script_content,
        Path(args.training_script).name,
        script_args,
        nproc_per_node,
        nnodes,
        resources,
        storage_pvc,
        base_dir,
        project_config,
    )

    print(f"\nApplying: {job_name}")
    apply_manifest(manifest, namespace)

    # Always wait and stream logs (like torchrun)
    print("Waiting for job to start...")
    wait_for_job(job_name, namespace)

    print("\n" + "=" * 80)
    print("Logs:")
    print("=" * 80 + "\n")

    stream_logs(job_name, namespace)

    # Check success BEFORE cleanup
    success = check_job_success(job_name, namespace)

    print("\n" + "=" * 80)
    print("Completed successfully!" if success else "Failed")
    print("=" * 80)

    # Copy results from PVC to local output directory
    # Auto-generate: output/{script_name}-{timestamp}
    folder_name = base_dir.split("/")[-1]
    local_output = Path("output") / folder_name

    copy_results_from_pvc(base_dir, storage_pvc, namespace, str(local_output))

    # Always cleanup (ephemeral)
    print(f"\nCleaning up: {job_name}")
    cleanup_job(job_name, namespace)

    print(f"\nResults saved to PVC: {base_dir}")
    print(f"PVC: {storage_pvc}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
